;;;; src/appx.lisp
;;;
;;; Contains error codes related to Side-by-Side (SxS) assemblies,
;;; application packaging (AppX), Windows Eventing, MUI, and more.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; Side-by-Side (SxS) and Manifest Errors (14000-14110)
;;;--------------------------------------------------------------------------

(register-error 14000 :ERROR_SXS_SECTION_NOT_FOUND "The requested section was not present in the activation context.")
(register-error 14001 :ERROR_SXS_CANT_GEN_ACTCTX "The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.")
(register-error 14002 :ERROR_SXS_INVALID_ACTCTXDATA_FORMAT "The application binding data format is invalid.")
(register-error 14003 :ERROR_SXS_ASSEMBLY_NOT_FOUND "The referenced assembly is not installed on your system.")
(register-error 14004 :ERROR_SXS_MANIFEST_FORMAT_ERROR "The manifest file does not begin with the required tag and format information.")
(register-error 14005 :ERROR_SXS_MANIFEST_PARSE_ERROR "The manifest file contains one or more syntax errors.")
(register-error 14006 :ERROR_SXS_ACTIVATION_CONTEXT_DISABLED "The application attempted to activate a disabled activation context.")
(register-error 14007 :ERROR_SXS_KEY_NOT_FOUND "The requested lookup key was not found in any active activation context.")
(register-error 14008 :ERROR_SXS_VERSION_CONFLICT "A component version required by the application conflicts with another component version already active.")
(register-error 14009 :ERROR_SXS_WRONG_SECTION_TYPE "The type requested activation context section does not match the query API used.")
(register-error 14010 :ERROR_SXS_THREAD_QUERIES_DISABLED "Lack of system resources has required isolated activation to be disabled for the current thread of execution.")
(register-error 14011 :ERROR_SXS_PROCESS_DEFAULT_ALREADY_SET "An attempt to set the process default activation context failed because the process default activation context was already set.")
(register-error 14012 :ERROR_SXS_UNKNOWN_ENCODING_GROUP "The encoding group identifier specified is not recognized.")
(register-error 14013 :ERROR_SXS_UNKNOWN_ENCODING "The encoding requested is not recognized.")
(register-error 14014 :ERROR_SXS_INVALID_XML_NAMESPACE_URI "The manifest contains a reference to an invalid URI.")
(register-error 14015 :ERROR_SXS_ROOT_MANIFEST_DEPENDENCY_NOT_INSTALLED "The application manifest contains a reference to a dependent assembly which is not installed.")
(register-error 14016 :ERROR_SXS_LEAF_MANIFEST_DEPENDENCY_NOT_INSTALLED "The manifest for an assembly used by the application has a reference to a dependent assembly which is not installed.")
(register-error 14017 :ERROR_SXS_INVALID_ASSEMBLY_IDENTITY_ATTRIBUTE "The manifest contains an attribute for the assembly identity which is not valid.")
(register-error 14018 :ERROR_SXS_MANIFEST_MISSING_REQUIRED_DEFAULT_NAMESPACE "The manifest is missing the required default namespace specification on the assembly element.")
(register-error 14019 :ERROR_SXS_MANIFEST_INVALID_REQUIRED_DEFAULT_NAMESPACE "The manifest has a default namespace specified on the assembly element but its value is not \"urn:schemas-microsoft-com:asm.v1\".")
(register-error 14020 :ERROR_SXS_PRIVATE_MANIFEST_CROSS_PATH_WITH_REPARSE_POINT "The private manifest probed has crossed a path with an unsupported reparse point.")
(register-error 14021 :ERROR_SXS_DUPLICATE_DLL_NAME "Two or more components referenced directly or indirectly by the application manifest have files by the same name.")
(register-error 14022 :ERROR_SXS_DUPLICATE_WINDOWCLASS_NAME "Two or more components referenced directly or indirectly by the application manifest have window classes with the same name.")
(register-error 14023 :ERROR_SXS_DUPLICATE_CLSID "Two or more components referenced directly or indirectly by the application manifest have the same COM server CLSIDs.")
(register-error 14024 :ERROR_SXS_DUPLICATE_IID "Two or more components referenced directly or indirectly by the application manifest have proxies for the same COM interface IIDs.")
(register-error 14025 :ERROR_SXS_DUPLICATE_TLBID "Two or more components referenced directly or indirectly by the application manifest have the same COM type library TLBIDs.")
(register-error 14026 :ERROR_SXS_DUPLICATE_PROGID "Two or more components referenced directly or indirectly by the application manifest have the same COM ProgIDs.")
(register-error 14027 :ERROR_SXS_DUPLICATE_ASSEMBLY_NAME "Two or more components referenced directly or indirectly by the application manifest are different versions of the same component which is not permitted.")
(register-error 14028 :ERROR_SXS_FILE_HASH_MISMATCH "A component's file does not match the verification information present in the component manifest.")
(register-error 14029 :ERROR_SXS_POLICY_PARSE_ERROR "The policy manifest contains one or more syntax errors.")
(register-error 14030 :ERROR_SXS_XML_E_MISSINGQUOTE "Manifest Parse Error : A string literal was expected, but no opening quote character was found.")
(register-error 14031 :ERROR_SXS_XML_E_COMMENTSYNTAX "Manifest Parse Error : Incorrect syntax was used in a comment.")
(register-error 14032 :ERROR_SXS_XML_E_BADSTARTNAMECHAR "Manifest Parse Error : A name was started with an invalid character.")
(register-error 14033 :ERROR_SXS_XML_E_BADNAMECHAR "Manifest Parse Error : A name contained an invalid character.")
(register-error 14034 :ERROR_SXS_XML_E_BADCHARINSTRING "Manifest Parse Error : A string literal contained an invalid character.")
(register-error 14035 :ERROR_SXS_XML_E_XMLDECLSYNTAX "Manifest Parse Error : Invalid syntax for an xml declaration.")
(register-error 14036 :ERROR_SXS_XML_E_BADCHARDATA "Manifest Parse Error : An Invalid character was found in text content.")
(register-error 14037 :ERROR_SXS_XML_E_MISSINGWHITESPACE "Manifest Parse Error : Required white space was missing.")
(register-error 14038 :ERROR_SXS_XML_E_EXPECTINGTAGEND "Manifest Parse Error : The character '>' was expected.")
(register-error 14039 :ERROR_SXS_XML_E_MISSINGSEMICOLON "Manifest Parse Error : A semi colon character was expected.")
(register-error 14040 :ERROR_SXS_XML_E_UNBALANCEDPAREN "Manifest Parse Error : Unbalanced parentheses.")
(register-error 14041 :ERROR_SXS_XML_E_INTERNALERROR "Manifest Parse Error : Internal error.")
(register-error 14042 :ERROR_SXS_XML_E_UNEXPECTED_WHITESPACE "Manifest Parse Error : Whitespace is not allowed at this location.")
(register-error 14043 :ERROR_SXS_XML_E_INCOMPLETE_ENCODING "Manifest Parse Error : End of file reached in invalid state for current encoding.")
(register-error 14044 :ERROR_SXS_XML_E_MISSING_PAREN "Manifest Parse Error : Missing parenthesis.")
(register-error 14045 :ERROR_SXS_XML_E_EXPECTINGCLOSEQUOTE "Manifest Parse Error : A single or double closing quote character (' or \") is missing.")
(register-error 14046 :ERROR_SXS_XML_E_MULTIPLE_COLONS "Manifest Parse Error : Multiple colons are not allowed in a name.")
(register-error 14047 :ERROR_SXS_XML_E_INVALID_DECIMAL "Manifest Parse Error : Invalid character for decimal digit.")
(register-error 14048 :ERROR_SXS_XML_E_INVALID_HEXIDECIMAL "Manifest Parse Error : Invalid character for hexadecimal digit.")
(register-error 14049 :ERROR_SXS_XML_E_INVALID_UNICODE "Manifest Parse Error : Invalid unicode character value for this platform.")
(register-error 14050 :ERROR_SXS_XML_E_WHITESPACEORQUESTIONMARK "Manifest Parse Error : Expecting whitespace or '?'.")
(register-error 14051 :ERROR_SXS_XML_E_UNEXPECTEDENDTAG "Manifest Parse Error : End tag was not expected at this location.")
(register-error 14052 :ERROR_SXS_XML_E_UNCLOSEDTAG "Manifest Parse Error : The following tags were not closed: %1.")
(register-error 14053 :ERROR_SXS_XML_E_DUPLICATEATTRIBUTE "Manifest Parse Error : Duplicate attribute.")
(register-error 14054 :ERROR_SXS_XML_E_MULTIPLEROOTS "Manifest Parse Error : Only one top level element is allowed in an XML document.")
(register-error 14055 :ERROR_SXS_XML_E_INVALIDATROOTLEVEL "Manifest Parse Error : Invalid at the top level of the document.")
(register-error 14056 :ERROR_SXS_XML_E_BADXMLDECL "Manifest Parse Error : Invalid xml declaration.")
(register-error 14057 :ERROR_SXS_XML_E_MISSINGROOT "Manifest Parse Error : XML document must have a top level element.")
(register-error 14058 :ERROR_SXS_XML_E_UNEXPECTEDEOF "Manifest Parse Error : Unexpected end of file.")
(register-error 14059 :ERROR_SXS_XML_E_BADPEREFINSUBSET "Manifest Parse Error : Parameter entities cannot be used inside markup declarations in an internal subset.")
(register-error 14060 :ERROR_SXS_XML_E_UNCLOSEDSTARTTAG "Manifest Parse Error : Element was not closed.")
(register-error 14061 :ERROR_SXS_XML_E_UNCLOSEDENDTAG "Manifest Parse Error : End element was missing the character '>'.")
(register-error 14062 :ERROR_SXS_XML_E_UNCLOSEDSTRING "Manifest Parse Error : A string literal was not closed.")
(register-error 14063 :ERROR_SXS_XML_E_UNCLOSEDCOMMENT "Manifest Parse Error : A comment was not closed.")
(register-error 14064 :ERROR_SXS_XML_E_UNCLOSEDDECL "Manifest Parse Error : A declaration was not closed.")
(register-error 14065 :ERROR_SXS_XML_E_UNCLOSEDCDATA "Manifest Parse Error : A CDATA section was not closed.")
(register-error 14066 :ERROR_SXS_XML_E_RESERVEDNAMESPACE "Manifest Parse Error : The namespace prefix is not allowed to start with the reserved string \"xml\".")
(register-error 14067 :ERROR_SXS_XML_E_INVALIDENCODING "Manifest Parse Error : System does not support the specified encoding.")
(register-error 14068 :ERROR_SXS_XML_E_INVALIDSWITCH "Manifest Parse Error : Switch from current encoding to specified encoding not supported.")
(register-error 14069 :ERROR_SXS_XML_E_BADXMLCASE "Manifest Parse Error : The name 'xml' is reserved and must be lower case.")
(register-error 14070 :ERROR_SXS_XML_E_INVALID_STANDALONE "Manifest Parse Error : The standalone attribute must have the value 'yes' or 'no'.")
(register-error 14071 :ERROR_SXS_XML_E_UNEXPECTED_STANDALONE "Manifest Parse Error : The standalone attribute cannot be used in external entities.")
(register-error 14072 :ERROR_SXS_XML_E_INVALID_VERSION "Manifest Parse Error : Invalid version number.")
(register-error 14073 :ERROR_SXS_XML_E_MISSINGEQUALS "Manifest Parse Error : Missing equals sign between attribute and attribute value.")
(register-error 14074 :ERROR_SXS_PROTECTION_RECOVERY_FAILED "Assembly Protection Error : Unable to recover the specified assembly.")
(register-error 14075 :ERROR_SXS_PROTECTION_PUBLIC_KEY_TOO_SHORT "Assembly Protection Error : The public key for an assembly was too short to be allowed.")
(register-error 14076 :ERROR_SXS_PROTECTION_CATALOG_NOT_VALID "Assembly Protection Error : The catalog for an assembly is not valid, or does not match the assembly's manifest.")
(register-error 14077 :ERROR_SXS_UNTRANSLATABLE_HRESULT "An HRESULT could not be translated to a corresponding Win32 error code.")
(register-error 14078 :ERROR_SXS_PROTECTION_CATALOG_FILE_MISSING "Assembly Protection Error : The catalog for an assembly is missing.")
(register-error 14079 :ERROR_SXS_MISSING_ASSEMBLY_IDENTITY_ATTRIBUTE "The supplied assembly identity is missing one or more attributes which must be present in this context.")
(register-error 14080 :ERROR_SXS_INVALID_ASSEMBLY_IDENTITY_ATTRIBUTE_NAME "The supplied assembly identity has one or more attribute names that contain characters not permitted in XML names.")
(register-error 14081 :ERROR_SXS_ASSEMBLY_MISSING "The referenced assembly could not be found.")
(register-error 14082 :ERROR_SXS_CORRUPT_ACTIVATION_STACK "The activation context activation stack for the running thread of execution is corrupt.")
(register-error 14083 :ERROR_SXS_CORRUPTION "The application isolation metadata for this process or thread has become corrupt.")
(register-error 14084 :ERROR_SXS_EARLY_DEACTIVATION "The activation context being deactivated is not the most recently activated one.")
(register-error 14085 :ERROR_SXS_INVALID_DEACTIVATION "The activation context being deactivated is not active for the current thread of execution.")
(register-error 14086 :ERROR_SXS_MULTIPLE_DEACTIVATION "The activation context being deactivated has already been deactivated.")
(register-error 14087 :ERROR_SXS_PROCESS_TERMINATION_REQUESTED "A component used by the isolation facility has requested to terminate the process.")
(register-error 14088 :ERROR_SXS_RELEASE_ACTIVATION_CONTEXT "A kernel mode component is releasing a reference on an activation context.")
(register-error 14089 :ERROR_SXS_SYSTEM_DEFAULT_ACTIVATION_CONTEXT_EMPTY "The activation context of system default assembly could not be generated.")
(register-error 14090 :ERROR_SXS_INVALID_IDENTITY_ATTRIBUTE_VALUE "The value of an attribute in an identity is not within the legal range.")
(register-error 14091 :ERROR_SXS_INVALID_IDENTITY_ATTRIBUTE_NAME "The name of an attribute in an identity is not within the legal range.")
(register-error 14092 :ERROR_SXS_IDENTITY_DUPLICATE_ATTRIBUTE "An identity contains two definitions for the same attribute.")
(register-error 14093 :ERROR_SXS_IDENTITY_PARSE_ERROR "The identity string is malformed. This may be due to a trailing comma, more than two unnamed attributes, missing attribute name or missing attribute value.")
(register-error 14094 :ERROR_MALFORMED_SUBSTITUTION_STRING "A string containing localized substitutable content was malformed. Either a dollar sign ($) was followed by something other than a left parenthesis or another dollar sign or an substitution's right parenthesis was not found.")
(register-error 14095 :ERROR_SXS_INCORRECT_PUBLIC_KEY_TOKEN "The public key token does not correspond to the public key specified.")
(register-error 14096 :ERROR_UNMAPPED_SUBSTITUTION_STRING "A substitution string had no mapping.")
(register-error 14097 :ERROR_SXS_ASSEMBLY_NOT_LOCKED "The component must be locked before making the request.")
(register-error 14098 :ERROR_SXS_COMPONENT_STORE_CORRUPT "The component store has been corrupted.")
(register-error 14099 :ERROR_ADVANCED_INSTALLER_FAILED "An advanced installer failed during setup or servicing.")
(register-error 14100 :ERROR_XML_ENCODING_MISMATCH "The character encoding in the XML declaration did not match the encoding used in the document.")
(register-error 14101 :ERROR_SXS_MANIFEST_IDENTITY_SAME_BUT_CONTENTS_DIFFERENT "The identities of the manifests are identical but their contents are different.")
(register-error 14102 :ERROR_SXS_IDENTITIES_DIFFERENT "The component identities are different.")
(register-error 14103 :ERROR_SXS_ASSEMBLY_IS_NOT_A_DEPLOYMENT "The assembly is not a deployment.")
(register-error 14104 :ERROR_SXS_FILE_NOT_PART_OF_ASSEMBLY "The file is not a part of the assembly.")
(register-error 14105 :ERROR_SXS_MANIFEST_TOO_BIG "The size of the manifest exceeds the maximum allowed.")
(register-error 14106 :ERROR_SXS_SETTING_NOT_REGISTERED "The setting is not registered.")
(register-error 14107 :ERROR_SXS_TRANSACTION_CLOSURE_INCOMPLETE "One or more required members of the transaction are not present.")
(register-error 14108 :ERROR_SMI_PRIMITIVE_INSTALLER_FAILED "The SMI primitive installer failed during setup or servicing.")
(register-error 14109 :ERROR_GENERIC_COMMAND_FAILED "A generic command executable returned a result that indicates failure.")
(register-error 14110 :ERROR_SXS_FILE_HASH_MISSING "A component is missing file verification information in its manifest.")

;;;--------------------------------------------------------------------------
;;; Windows Eventing Errors (15000-15085)
;;;--------------------------------------------------------------------------

(register-error 15000 :ERROR_EVT_INVALID_CHANNEL_PATH "The specified channel path is invalid.")
(register-error 15001 :ERROR_EVT_INVALID_QUERY "The specified query is invalid.")
(register-error 15002 :ERROR_EVT_PUBLISHER_METADATA_NOT_FOUND "The publisher metadata cannot be found in the resource.")
(register-error 15003 :ERROR_EVT_EVENT_TEMPLATE_NOT_FOUND "The template for an event definition cannot be found in the resource (error = %1).")
(register-error 15004 :ERROR_EVT_INVALID_PUBLISHER_NAME "The specified publisher name is invalid.")
(register-error 15005 :ERROR_EVT_INVALID_EVENT_DATA "The event data raised by the publisher is not compatible with the event template definition in the publisher's manifest.")
(register-error 15007 :ERROR_EVT_CHANNEL_NOT_FOUND "The specified channel could not be found. Check channel configuration.")
(register-error 15008 :ERROR_EVT_MALFORMED_XML_TEXT "The specified xml text was not well-formed. See Extended Error for more details.")
(register-error 15009 :ERROR_EVT_SUBSCRIPTION_TO_DIRECT_CHANNEL "The caller is trying to subscribe to a direct channel which is not allowed. The events for a direct channel go directly to a logfile and cannot be subscribed to.")
(register-error 15010 :ERROR_EVT_CONFIGURATION_ERROR "Configuration error.")
(register-error 15011 :ERROR_EVT_QUERY_RESULT_STALE "The query result is stale / invalid. This may be due to the log being cleared or rolling over after the query result was created. Users should handle this code by releasing the query result object and reissuing the query.")
(register-error 15012 :ERROR_EVT_QUERY_RESULT_INVALID_POSITION "Query result is currently at an invalid position.")
(register-error 15013 :ERROR_EVT_NON_VALIDATING_MSXML "Registered MSXML doesn't support validation.")
(register-error 15014 :ERROR_EVT_FILTER_ALREADYSCOPED "An expression can only be followed by a change of scope operation if it itself evaluates to a node set and is not already part of some other change of scope operation.")
(register-error 15015 :ERROR_EVT_FILTER_NOTELTSET "Can't perform a step operation from a term that does not represent an element set.")
(register-error 15016 :ERROR_EVT_FILTER_INVARG "Left hand side arguments to binary operators must be either attributes, nodes or variables and right hand side arguments must be constants.")
(register-error 15017 :ERROR_EVT_FILTER_INVTEST "A step operation must involve either a node test or, in the case of a predicate, an algebraic expression against which to test each node in the node set identified by the preceding node set can be evaluated.")
(register-error 15018 :ERROR_EVT_FILTER_INVTYPE "This data type is currently unsupported.")
(register-error 15019 :ERROR_EVT_FILTER_PARSEERR "A syntax error occurred at position %1!d!.")
(register-error 15020 :ERROR_EVT_FILTER_UNSUPPORTEDOP "This operator is unsupported by this implementation of the filter.")
(register-error 15021 :ERROR_EVT_FILTER_UNEXPECTEDTOKEN "The token encountered was unexpected.")
(register-error 15022 :ERROR_EVT_INVALID_OPERATION_OVER_ENABLED_DIRECT_CHANNEL "The requested operation cannot be performed over an enabled direct channel. The channel must first be disabled before performing the requested operation.")
(register-error 15023 :ERROR_EVT_INVALID_CHANNEL_PROPERTY_VALUE "Channel property %1!s! contains invalid value. The value has invalid type, is outside of valid range, can't be updated or is not supported by this type of channel.")
(register-error 15024 :ERROR_EVT_INVALID_PUBLISHER_PROPERTY_VALUE "Publisher property %1!s! contains invalid value. The value has invalid type, is outside of valid range, can't be updated or is not supported by this type of publisher.")
(register-error 15025 :ERROR_EVT_CHANNEL_CANNOT_ACTIVATE "The channel fails to activate.")
(register-error 15026 :ERROR_EVT_FILTER_TOO_COMPLEX "The xpath expression exceeded supported complexity. Please simplify it or split it into two or more simple expressions.")
(register-error 15027 :ERROR_EVT_MESSAGE_NOT_FOUND "the message resource is present but the message is not found in the string/message table.")
(register-error 15028 :ERROR_EVT_MESSAGE_ID_NOT_FOUND "The message id for the desired message could not be found.")
(register-error 15029 :ERROR_EVT_UNRESOLVED_VALUE_INSERT "The substitution string for insert index (%1) could not be found.")
(register-error 15030 :ERROR_EVT_UNRESOLVED_PARAMETER_INSERT "The description string for parameter reference (%1) could not be found.")
(register-error 15031 :ERROR_EVT_MAX_INSERTS_REACHED "The maximum number of replacements has been reached.")
(register-error 15032 :ERROR_EVT_EVENT_DEFINITION_NOT_FOUND "The event definition could not be found for event id (%1).")
(register-error 15033 :ERROR_EVT_MESSAGE_LOCALE_NOT_FOUND "The locale specific resource for the desired message is not present.")
(register-error 15034 :ERROR_EVT_VERSION_TOO_OLD "The resource is too old to be compatible.")
(register-error 15035 :ERROR_EVT_VERSION_TOO_NEW "The resource is too new to be compatible.")
(register-error 15036 :ERROR_EVT_CANNOT_OPEN_CHANNEL_OF_QUERY "The channel at index %1!d! of the query can't be opened.")
(register-error 15037 :ERROR_EVT_PUBLISHER_DISABLED "The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded.")
(register-error 15038 :ERROR_EVT_FILTER_OUT_OF_RANGE "Attempted to create a numeric type that is outside of its valid range.")
(register-error 15080 :ERROR_EC_SUBSCRIPTION_CANNOT_ACTIVATE "The subscription fails to activate.")
(register-error 15081 :ERROR_EC_LOG_DISABLED "The log of the subscription is in disabled state, and cannot be used to forward events to. The log must first be enabled before the subscription can be activated.")
(register-error 15082 :ERROR_EC_CIRCULAR_FORWARDING "When forwarding events from local machine to itself, the query of the subscription can't contain target log of the subscription.")
(register-error 15083 :ERROR_EC_CREDSTORE_FULL "The credential store that is used to save credentials is full.")
(register-error 15084 :ERROR_EC_CRED_NOT_FOUND "The credential used by this subscription can't be found in credential store.")
(register-error 15085 :ERROR_EC_NO_ACTIVE_CHANNEL "No active channel is found for the query.")

;;;--------------------------------------------------------------------------
;;; MUI and Resource Loader Errors (15100-15140)
;;;--------------------------------------------------------------------------

(register-error 15100 :ERROR_MUI_FILE_NOT_FOUND "The resource loader failed to find MUI file.")
(register-error 15101 :ERROR_MUI_INVALID_FILE "The resource loader failed to load MUI file because the file fail to pass validation.")
(register-error 15102 :ERROR_MUI_INVALID_RC_CONFIG "The RC Manifest is corrupted with garbage data or unsupported version or missing required item.")
(register-error 15103 :ERROR_MUI_INVALID_LOCALE_NAME "The RC Manifest has invalid culture name.")
(register-error 15104 :ERROR_MUI_INVALID_ULTIMATEFALLBACK_NAME "The RC Manifest has invalid ultimatefallback name.")
(register-error 15105 :ERROR_MUI_FILE_NOT_LOADED "The resource loader cache doesn't have loaded MUI entry.")
(register-error 15106 :ERROR_RESOURCE_ENUM_USER_STOP "User stopped resource enumeration.")
(register-error 15107 :ERROR_MUI_INTLSETTINGS_UILANG_NOT_INSTALLED "UI language installation failed.")
(register-error 15108 :ERROR_MUI_INTLSETTINGS_INVALID_LOCALE_NAME "Locale installation failed.")
(register-error 15110 :ERROR_MRM_RUNTIME_NO_DEFAULT_OR_NEUTRAL_RESOURCE "A resource does not have default or neutral value.")
(register-error 15111 :ERROR_MRM_INVALID_PRICONFIG "Invalid PRI config file.")
(register-error 15112 :ERROR_MRM_INVALID_FILE_TYPE "Invalid file type.")
(register-error 15113 :ERROR_MRM_UNKNOWN_QUALIFIER "Unknown qualifier.")
(register-error 15114 :ERROR_MRM_INVALID_QUALIFIER_VALUE "Invalid qualifier value.")
(register-error 15115 :ERROR_MRM_NO_CANDIDATE "No Candidate found.")
(register-error 15116 :ERROR_MRM_NO_MATCH_OR_DEFAULT_CANDIDATE "The ResourceMap or NamedResource has an item that does not have default or neutral resource..")
(register-error 15117 :ERROR_MRM_RESOURCE_TYPE_MISMATCH "Invalid ResourceCandidate type.")
(register-error 15118 :ERROR_MRM_DUPLICATE_MAP_NAME "Duplicate Resource Map.")
(register-error 15119 :ERROR_MRM_DUPLICATE_ENTRY "Duplicate Entry.")
(register-error 15120 :ERROR_MRM_INVALID_RESOURCE_IDENTIFIER "Invalid Resource Identifier.")
(register-error 15121 :ERROR_MRM_FILEPATH_TOO_LONG "Filepath too long.")
(register-error 15122 :ERROR_MRM_UNSUPPORTED_DIRECTORY_TYPE "Unsupported directory type.")
(register-error 15126 :ERROR_MRM_INVALID_PRI_FILE "Invalid PRI File.")
(register-error 15127 :ERROR_MRM_NAMED_RESOURCE_NOT_FOUND "NamedResource Not Found.")
(register-error 15135 :ERROR_MRM_MAP_NOT_FOUND "ResourceMap Not Found.")
(register-error 15136 :ERROR_MRM_UNSUPPORTED_PROFILE_TYPE "Unsupported MRT profile type.")
(register-error 15137 :ERROR_MRM_INVALID_QUALIFIER_OPERATOR "Invalid qualifier operator.")
(register-error 15138 :ERROR_MRM_INDETERMINATE_QUALIFIER_VALUE "Unable to determine qualifier value or qualifier value has not been set.")
(register-error 15139 :ERROR_MRM_AUTOMERGE_ENABLED "Automerge is enabled in the PRI file.")
(register-error 15140 :ERROR_MRM_TOO_MANY_RESOURCES "Too many resources defined for package.")

;;;--------------------------------------------------------------------------
;;; Monitor Configuration and GPIO Errors (15200-15327)
;;;--------------------------------------------------------------------------

(register-error 15200 :ERROR_MCA_INVALID_CAPABILITIES_STRING "The monitor returned a DDC/CI capabilities string that did not comply with the ACCESS.bus 3.0, DDC/CI 1.1 or MCCS 2 Revision 1 specification.")
(register-error 15201 :ERROR_MCA_INVALID_VCP_VERSION "The monitor's VCP Version (0xDF) VCP code returned an invalid version value.")
(register-error 15202 :ERROR_MCA_MONITOR_VIOLATES_MCCS_SPECIFICATION "The monitor does not comply with the MCCS specification it claims to support.")
(register-error 15203 :ERROR_MCA_MCCS_VERSION_MISMATCH "The MCCS version in a monitor's mccs_ver capability does not match the MCCS version the monitor reports when the VCP Version (0xDF) VCP code is used.")
(register-error 15204 :ERROR_MCA_UNSUPPORTED_MCCS_VERSION "The Monitor Configuration API only works with monitors that support the MCCS 1.0 specification, MCCS 2.0 specification or the MCCS 2.0 Revision 1 specification.")
(register-error 15205 :ERROR_MCA_INTERNAL_ERROR "An internal Monitor Configuration API error occurred.")
(register-error 15206 :ERROR_MCA_INVALID_TECHNOLOGY_TYPE_RETURNED "The monitor returned an invalid monitor technology type. CRT, Plasma and LCD (TFT) are examples of monitor technology types. This error implies that the monitor violated the MCCS 2.0 or MCCS 2.0 Revision 1 specification.")
(register-error 15207 :ERROR_MCA_UNSUPPORTED_COLOR_TEMPERATURE "The caller of SetMonitorColorTemperature specified a color temperature that the current monitor did not support. This error implies that the monitor violated the MCCS 2.0 or MCCS 2.0 Revision 1 specification.")
(register-error 15250 :ERROR_AMBIGUOUS_SYSTEM_DEVICE "The requested system device cannot be identified due to multiple indistinguishable devices potentially matching the identification criteria.")
(register-error 15299 :ERROR_SYSTEM_DEVICE_NOT_FOUND "The requested system device cannot be found.")
(register-error 15300 :ERROR_HASH_NOT_SUPPORTED "Hash generation for the specified hash version and hash type is not enabled on the server.")
(register-error 15301 :ERROR_HASH_NOT_PRESENT "The hash requested from the server is not available or no longer valid.")
(register-error 15321 :ERROR_SECONDARY_IC_PROVIDER_NOT_REGISTERED "The secondary interrupt controller instance that manages the specified interrupt is not registered.")
(register-error 15322 :ERROR_GPIO_CLIENT_INFORMATION_INVALID "The information supplied by the GPIO client driver is invalid.")
(register-error 15323 :ERROR_GPIO_VERSION_NOT_SUPPORTED "The version specified by the GPIO client driver is not supported.")
(register-error 15324 :ERROR_GPIO_INVALID_REGISTRATION_PACKET "The registration packet supplied by the GPIO client driver is not valid.")
(register-error 15325 :ERROR_GPIO_OPERATION_DENIED "The requested operation is not supported for the specified handle.")
(register-error 15326 :ERROR_GPIO_INCOMPATIBLE_CONNECT_MODE "The requested connect mode conflicts with an existing mode on one or more of the specified pins.")
(register-error 15327 :ERROR_GPIO_INTERRUPT_ALREADY_UNMASKED "The interrupt requested to be unmasked is not masked.")

;;;--------------------------------------------------------------------------
;;; Runlevel and Service Errors (15400-15501)
;;;--------------------------------------------------------------------------

(register-error 15400 :ERROR_CANNOT_SWITCH_RUNLEVEL "The requested run level switch cannot be completed successfully.")
(register-error 15401 :ERROR_INVALID_RUNLEVEL_SETTING "The service has an invalid run level setting. The run level for a service must not be higher than the run level of its dependent services.")
(register-error 15402 :ERROR_RUNLEVEL_SWITCH_TIMEOUT "The requested run level switch cannot be completed successfully since one or more services will not stop or restart within the specified timeout.")
(register-error 15403 :ERROR_RUNLEVEL_SWITCH_AGENT_TIMEOUT "A run level switch agent did not respond within the specified timeout.")
(register-error 15404 :ERROR_RUNLEVEL_SWITCH_IN_PROGRESS "A run level switch is currently in progress.")
(register-error 15405 :ERROR_SERVICES_FAILED_AUTOSTART "One or more services failed to start during the service startup phase of a run level switch.")
(register-error 15501 :ERROR_COM_TASK_STOP_PENDING "The task stop request cannot be completed immediately since task needs more time to shutdown.")

;;;--------------------------------------------------------------------------
;;; Application Installation (AppX) and State Errors (15600-15841)
;;;--------------------------------------------------------------------------

(register-error 15600 :ERROR_INSTALL_OPEN_PACKAGE_FAILED "Package could not be opened.")
(register-error 15601 :ERROR_INSTALL_PACKAGE_NOT_FOUND "Package was not found.")
(register-error 15602 :ERROR_INSTALL_INVALID_PACKAGE "Package data is invalid.")
(register-error 15603 :ERROR_INSTALL_RESOLVE_DEPENDENCY_FAILED "Package failed updates, dependency or conflict validation.")
(register-error 15604 :ERROR_INSTALL_OUT_OF_DISK_SPACE "There is not enough disk space on your computer. Please free up some space and try again.")
(register-error 15605 :ERROR_INSTALL_NETWORK_FAILURE "There was a problem downloading your product.")
(register-error 15606 :ERROR_INSTALL_REGISTRATION_FAILURE "Package could not be registered.")
(register-error 15607 :ERROR_INSTALL_DEREGISTRATION_FAILURE "Package could not be unregistered.")
(register-error 15608 :ERROR_INSTALL_CANCEL "User cancelled the install request.")
(register-error 15609 :ERROR_INSTALL_FAILED "Install failed. Please contact your software vendor.")
(register-error 15610 :ERROR_REMOVE_FAILED "Removal failed. Please contact your software vendor.")
(register-error 15611 :ERROR_PACKAGE_ALREADY_EXISTS "The provided package is already installed, and reinstallation of the package was blocked. Check the AppXDeployment-Server event log for details.")
(register-error 15612 :ERROR_NEEDS_REMEDIATION "The application cannot be started. Try reinstalling the application to fix the problem.")
(register-error 15613 :ERROR_INSTALL_PREREQUISITE_FAILED "A Prerequisite for an install could not be satisfied.")
(register-error 15614 :ERROR_PACKAGE_REPOSITORY_CORRUPTED "The package repository is corrupted.")
(register-error 15615 :ERROR_INSTALL_POLICY_FAILURE "To install this application you need either a Windows developer license or a sideloading-enabled system.")
(register-error 15616 :ERROR_PACKAGE_UPDATING "The application cannot be started because it is currently updating.")
(register-error 15617 :ERROR_DEPLOYMENT_BLOCKED_BY_POLICY "The package deployment operation is blocked by policy. Please contact your system administrator.")
(register-error 15618 :ERROR_PACKAGES_IN_USE "The package could not be installed because resources it modifies are currently in use.")
(register-error 15619 :ERROR_RECOVERY_FILE_CORRUPT "The package could not be recovered because necessary data for recovery have been corrupted.")
(register-error 15620 :ERROR_INVALID_STAGED_SIGNATURE "The signature is invalid. To register in developer mode, AppxSignature.p7x and AppxBlockMap.xml must be valid or should not be present.")
(register-error 15621 :ERROR_DELETING_EXISTING_APPLICATIONDATA_STORE_FAILED "An error occurred while deleting the package's previously existing application data.")
(register-error 15622 :ERROR_INSTALL_PACKAGE_DOWNGRADE "The package could not be installed because a higher version of this package is already installed.")
(register-error 15623 :ERROR_SYSTEM_NEEDS_REMEDIATION "An error in a system binary was detected. Try refreshing the PC to fix the problem.")
(register-error 15624 :ERROR_APPX_INTEGRITY_FAILURE_CLR_NGEN "A corrupted CLR NGEN binary was detected on the system.")
(register-error 15625 :ERROR_RESILIENCY_FILE_CORRUPT "The operation could not be resumed because necessary data for recovery have been corrupted.")
(register-error 15626 :ERROR_INSTALL_FIREWALL_SERVICE_NOT_RUNNING "The package could not be installed because the Windows Firewall service is not running. Enable the Windows Firewall service and try again.")
(register-error 15700 :APPMODEL_ERROR_NO_PACKAGE "The process has no package identity.")
(register-error 15701 :APPMODEL_ERROR_PACKAGE_RUNTIME_CORRUPT "The package runtime information is corrupted.")
(register-error 15702 :APPMODEL_ERROR_PACKAGE_IDENTITY_CORRUPT "The package identity is corrupted.")
(register-error 15703 :APPMODEL_ERROR_NO_APPLICATION "The process has no application identity.")
(register-error 15800 :ERROR_STATE_LOAD_STORE_FAILED "Loading the state store failed.")
(register-error 15801 :ERROR_STATE_GET_VERSION_FAILED "Retrieving the state version for the application failed.")
(register-error 15802 :ERROR_STATE_SET_VERSION_FAILED "Setting the state version for the application failed.")
(register-error 15803 :ERROR_STATE_STRUCTURED_RESET_FAILED "Resetting the structured state of the application failed.")
(register-error 15804 :ERROR_STATE_OPEN_CONTAINER_FAILED "State Manager failed to open the container.")
(register-error 15805 :ERROR_STATE_CREATE_CONTAINER_FAILED "State Manager failed to create the container.")
(register-error 15806 :ERROR_STATE_DELETE_CONTAINER_FAILED "State Manager failed to delete the container.")
(register-error 15807 :ERROR_STATE_READ_SETTING_FAILED "State Manager failed to read the setting.")
(register-error 15808 :ERROR_STATE_WRITE_SETTING_FAILED "State Manager failed to write the setting.")
(register-error 15809 :ERROR_STATE_DELETE_SETTING_FAILED "State Manager failed to delete the setting.")
(register-error 15810 :ERROR_STATE_QUERY_SETTING_FAILED "State Manager failed to query the setting.")
(register-error 15811 :ERROR_STATE_READ_COMPOSITE_SETTING_FAILED "State Manager failed to read the composite setting.")
(register-error 15812 :ERROR_STATE_WRITE_COMPOSITE_SETTING_FAILED "State Manager failed to write the composite setting.")
(register-error 15813 :ERROR_STATE_ENUMERATE_CONTAINER_FAILED "State Manager failed to enumerate the containers.")
(register-error 15814 :ERROR_STATE_ENUMERATE_SETTINGS_FAILED "State Manager failed to enumerate the settings.")
(register-error 15815 :ERROR_STATE_COMPOSITE_SETTING_VALUE_SIZE_LIMIT_EXCEEDED "The size of the state manager composite setting value has exceeded the limit.")
(register-error 15816 :ERROR_STATE_SETTING_VALUE_SIZE_LIMIT_EXCEEDED "The size of the state manager setting value has exceeded the limit.")
(register-error 15817 :ERROR_STATE_SETTING_NAME_SIZE_LIMIT_EXCEEDED "The length of the state manager setting name has exceeded the limit.")
(register-error 15818 :ERROR_STATE_CONTAINER_NAME_SIZE_LIMIT_EXCEEDED "The length of the state manager container name has exceeded the limit.")
(register-error 15841 :ERROR_API_UNAVAILABLE "This API cannot be used in the context of the caller's application type.")

