;;;; src/cluster.lisp
;;;
;;; Contains Failover Clustering error codes.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; Failover Cluster Errors (5001-5972)
;;;--------------------------------------------------------------------------

(register-error 5001 :ERROR_DEPENDENT_RESOURCE_EXISTS "The operation cannot be completed because other resources are dependent on this resource.")
(register-error 5002 :ERROR_DEPENDENCY_NOT_FOUND "The cluster resource dependency cannot be found.")
(register-error 5003 :ERROR_DEPENDENCY_ALREADY_EXISTS "The cluster resource cannot be made dependent on the specified resource because it is already dependent.")
(register-error 5004 :ERROR_RESOURCE_NOT_ONLINE "The cluster resource is not online.")
(register-error 5005 :ERROR_HOST_NODE_NOT_AVAILABLE "A cluster node is not available for this operation.")
(register-error 5006 :ERROR_RESOURCE_NOT_AVAILABLE "The cluster resource is not available.")
(register-error 5007 :ERROR_RESOURCE_NOT_FOUND "The cluster resource could not be found.")
(register-error 5008 :ERROR_SHUTDOWN_CLUSTER "The cluster is being shut down.")
(register-error 5009 :ERROR_CANT_EVICT_ACTIVE_NODE "A cluster node cannot be evicted from the cluster unless the node is down or it is the last node.")
(register-error 5010 :ERROR_OBJECT_ALREADY_EXISTS "The object already exists.")
(register-error 5011 :ERROR_OBJECT_IN_LIST "The object is already in the list.")
(register-error 5012 :ERROR_GROUP_NOT_AVAILABLE "The cluster group is not available for any new requests.")
(register-error 5013 :ERROR_GROUP_NOT_FOUND "The cluster group could not be found.")
(register-error 5014 :ERROR_GROUP_NOT_ONLINE "The operation could not be completed because the cluster group is not online.")
(register-error 5015 :ERROR_HOST_NODE_NOT_RESOURCE_OWNER "The operation failed because either the specified cluster node is not the owner of the resource, or the node is not a possible owner of the resource.")
(register-error 5016 :ERROR_HOST_NODE_NOT_GROUP_OWNER "The operation failed because either the specified cluster node is not the owner of the group, or the node is not a possible owner of the group.")
(register-error 5017 :ERROR_RESMON_CREATE_FAILED "The cluster resource could not be created in the specified resource monitor.")
(register-error 5018 :ERROR_RESMON_ONLINE_FAILED "The cluster resource could not be brought online by the resource monitor.")
(register-error 5019 :ERROR_RESOURCE_ONLINE "The operation could not be completed because the cluster resource is online.")
(register-error 5020 :ERROR_QUORUM_RESOURCE "The cluster resource could not be deleted or brought offline because it is the quorum resource.")
(register-error 5021 :ERROR_NOT_QUORUM_CAPABLE "The cluster could not make the specified resource a quorum resource because it is not capable of being a quorum resource.")
(register-error 5022 :ERROR_CLUSTER_SHUTTING_DOWN "The cluster software is shutting down.")
(register-error 5023 :ERROR_INVALID_STATE "The group or resource is not in the correct state to perform the requested operation.")
(register-error 5024 :ERROR_RESOURCE_PROPERTIES_STORED "The properties were stored but not all changes will take effect until the next time the resource is brought online.")
(register-error 5025 :ERROR_NOT_QUORUM_CLASS "The cluster could not make the specified resource a quorum resource because it does not belong to a shared storage class.")
(register-error 5026 :ERROR_CORE_RESOURCE "The cluster resource could not be deleted since it is a core resource.")
(register-error 5027 :ERROR_QUORUM_RESOURCE_ONLINE_FAILED "The quorum resource failed to come online.")
(register-error 5028 :ERROR_QUORUMLOG_OPEN_FAILED "The quorum log could not be created or mounted successfully.")
(register-error 5029 :ERROR_CLUSTERLOG_CORRUPT "The cluster log is corrupt.")
(register-error 5030 :ERROR_CLUSTERLOG_RECORD_EXCEEDS_MAXSIZE "The record could not be written to the cluster log since it exceeds the maximum size.")
(register-error 5031 :ERROR_CLUSTERLOG_EXCEEDS_MAXSIZE "The cluster log exceeds its maximum size.")
(register-error 5032 :ERROR_CLUSTERLOG_CHKPOINT_NOT_FOUND "No checkpoint record was found in the cluster log.")
(register-error 5033 :ERROR_CLUSTERLOG_NOT_ENOUGH_SPACE "The minimum required disk space needed for logging is not available.")
(register-error 5034 :ERROR_QUORUM_OWNER_ALIVE "The cluster node failed to take control of the quorum resource because the resource is owned by another active node.")
(register-error 5035 :ERROR_NETWORK_NOT_AVAILABLE "A cluster network is not available for this operation.")
(register-error 5036 :ERROR_NODE_NOT_AVAILABLE "A cluster node is not available for this operation.")
(register-error 5037 :ERROR_ALL_NODES_NOT_AVAILABLE "All cluster nodes must be running to perform this operation.")
(register-error 5038 :ERROR_RESOURCE_FAILED "A cluster resource failed.")
(register-error 5039 :ERROR_CLUSTER_INVALID_NODE "The cluster node is not valid.")
(register-error 5040 :ERROR_CLUSTER_NODE_EXISTS "The cluster node already exists.")
(register-error 5041 :ERROR_CLUSTER_JOIN_IN_PROGRESS "A node is in the process of joining the cluster.")
(register-error 5042 :ERROR_CLUSTER_NODE_NOT_FOUND "The cluster node was not found.")
(register-error 5043 :ERROR_CLUSTER_LOCAL_NODE_NOT_FOUND "The cluster local node information was not found.")
(register-error 5044 :ERROR_CLUSTER_NETWORK_EXISTS "The cluster network already exists.")
(register-error 5045 :ERROR_CLUSTER_NETWORK_NOT_FOUND "The cluster network was not found.")
(register-error 5046 :ERROR_CLUSTER_NETINTERFACE_EXISTS "The cluster network interface already exists.")
(register-error 5047 :ERROR_CLUSTER_NETINTERFACE_NOT_FOUND "The cluster network interface was not found.")
(register-error 5048 :ERROR_CLUSTER_INVALID_REQUEST "The cluster request is not valid for this object.")
(register-error 5049 :ERROR_CLUSTER_INVALID_NETWORK_PROVIDER "The cluster network provider is not valid.")
(register-error 5050 :ERROR_CLUSTER_NODE_DOWN "The cluster node is down.")
(register-error 5051 :ERROR_CLUSTER_NODE_UNREACHABLE "The cluster node is not reachable.")
(register-error 5052 :ERROR_CLUSTER_NODE_NOT_MEMBER "The cluster node is not a member of the cluster.")
(register-error 5053 :ERROR_CLUSTER_JOIN_NOT_IN_PROGRESS "A cluster join operation is not in progress.")
(register-error 5054 :ERROR_CLUSTER_INVALID_NETWORK "The cluster network is not valid.")
(register-error 5056 :ERROR_CLUSTER_NODE_UP "The cluster node is up.")
(register-error 5057 :ERROR_CLUSTER_IPADDR_IN_USE "The cluster IP address is already in use.")
(register-error 5058 :ERROR_CLUSTER_NODE_NOT_PAUSED "The cluster node is not paused.")
(register-error 5059 :ERROR_CLUSTER_NO_SECURITY_CONTEXT "No cluster security context is available.")
(register-error 5060 :ERROR_CLUSTER_NETWORK_NOT_INTERNAL "The cluster network is not configured for internal cluster communication.")
(register-error 5061 :ERROR_CLUSTER_NODE_ALREADY_UP "The cluster node is already up.")
(register-error 5062 :ERROR_CLUSTER_NODE_ALREADY_DOWN "The cluster node is already down.")
(register-error 5063 :ERROR_CLUSTER_NETWORK_ALREADY_ONLINE "The cluster network is already online.")
(register-error 5064 :ERROR_CLUSTER_NETWORK_ALREADY_OFFLINE "The cluster network is already offline.")
(register-error 5065 :ERROR_CLUSTER_NODE_ALREADY_MEMBER "The cluster node is already a member of the cluster.")
(register-error 5066 :ERROR_CLUSTER_LAST_INTERNAL_NETWORK "The cluster network is the only one configured for internal cluster communication between two or more active cluster nodes. The internal communication capability cannot be removed from the network.")
(register-error 5067 :ERROR_CLUSTER_NETWORK_HAS_DEPENDENTS "One or more cluster resources depend on the network to provide service to clients. The client access capability cannot be removed from the network.")
(register-error 5068 :ERROR_INVALID_OPERATION_ON_QUORUM "This operation cannot be performed on the cluster resource as it the quorum resource. You may not bring the quorum resource offline or modify its possible owners list.")
(register-error 5069 :ERROR_DEPENDENCY_NOT_ALLOWED "The cluster quorum resource is not allowed to have any dependencies.")
(register-error 5070 :ERROR_CLUSTER_NODE_PAUSED "The cluster node is paused.")
(register-error 5071 :ERROR_NODE_CANT_HOST_RESOURCE "The cluster resource cannot be brought online. The owner node cannot run this resource.")
(register-error 5072 :ERROR_CLUSTER_NODE_NOT_READY "The cluster node is not ready to perform the requested operation.")
(register-error 5073 :ERROR_CLUSTER_NODE_SHUTTING_DOWN "The cluster node is shutting down.")
(register-error 5074 :ERROR_CLUSTER_JOIN_ABORTED "The cluster join operation was aborted.")
(register-error 5075 :ERROR_CLUSTER_INCOMPATIBLE_VERSIONS "The cluster join operation failed due to incompatible software versions between the joining node and its sponsor.")
(register-error 5076 :ERROR_CLUSTER_MAXNUM_OF_RESOURCES_EXCEEDED "This resource cannot be created because the cluster has reached the limit on the number of resources it can monitor.")
(register-error 5077 :ERROR_CLUSTER_SYSTEM_CONFIG_CHANGED "The system configuration changed during the cluster join or form operation. The join or form operation was aborted.")
(register-error 5078 :ERROR_CLUSTER_RESOURCE_TYPE_NOT_FOUND "The specified resource type was not found.")
(register-error 5079 :ERROR_CLUSTER_RESTYPE_NOT_SUPPORTED "The specified node does not support a resource of this type. This may be due to version inconsistencies or due to the absence of the resource DLL on this node.")
(register-error 5080 :ERROR_CLUSTER_RESNAME_NOT_FOUND "The specified resource name is not supported by this resource DLL. This may be due to a bad (or changed) name supplied to the resource DLL.")
(register-error 5081 :ERROR_CLUSTER_NO_RPC_PACKAGES_REGISTERED "No authentication package could be registered with the RPC server.")
(register-error 5082 :ERROR_CLUSTER_OWNER_NOT_IN_PREFLIST "You cannot bring the group online because the owner of the group is not in the preferred list for the group. To change the owner node for the group, move the group.")
(register-error 5083 :ERROR_CLUSTER_DATABASE_SEQMISMATCH "The join operation failed because the cluster database sequence number has changed or is incompatible with the locker node. This may happen during a join operation if the cluster database was changing during the join.")
(register-error 5084 :ERROR_RESMON_INVALID_STATE "The resource monitor will not allow the fail operation to be performed while the resource is in its current state. This may happen if the resource is in a pending state.")
(register-error 5085 :ERROR_CLUSTER_GUM_NOT_LOCKER "A non locker code got a request to reserve the lock for making global updates.")
(register-error 5086 :ERROR_QUORUM_DISK_NOT_FOUND "The quorum disk could not be located by the cluster service.")
(register-error 5087 :ERROR_DATABASE_BACKUP_CORRUPT "The backed up cluster database is possibly corrupt.")
(register-error 5088 :ERROR_CLUSTER_NODE_ALREADY_HAS_DFS_ROOT "A DFS root already exists in this cluster node.")
(register-error 5089 :ERROR_RESOURCE_PROPERTY_UNCHANGEABLE "An attempt to modify a resource property failed because it conflicts with another existing property.")
(register-error 5890 :ERROR_CLUSTER_MEMBERSHIP_INVALID_STATE "An operation was attempted that is incompatible with the current membership state of the node.")
(register-error 5891 :ERROR_CLUSTER_QUORUMLOG_NOT_FOUND "The quorum resource does not contain the quorum log.")
(register-error 5892 :ERROR_CLUSTER_MEMBERSHIP_HALT "The membership engine requested shutdown of the cluster service on this node.")
(register-error 5893 :ERROR_CLUSTER_INSTANCE_ID_MISMATCH "The join operation failed because the cluster instance ID of the joining node does not match the cluster instance ID of the sponsor node.")
(register-error 5894 :ERROR_CLUSTER_NETWORK_NOT_FOUND_FOR_IP "A matching cluster network for the specified IP address could not be found.")
(register-error 5895 :ERROR_CLUSTER_PROPERTY_DATA_TYPE_MISMATCH "The actual data type of the property did not match the expected data type of the property.")
(register-error 5896 :ERROR_CLUSTER_EVICT_WITHOUT_CLEANUP "The cluster node was evicted from the cluster successfully, but the node was not cleaned up. To determine what cleanup steps failed and how to recover, see the Failover Clustering application event log using Event Viewer.")
(register-error 5897 :ERROR_CLUSTER_PARAMETER_MISMATCH "Two or more parameter values specified for a resource's properties are in conflict.")
(register-error 5898 :ERROR_NODE_CANNOT_BE_CLUSTERED "This computer cannot be made a member of a cluster.")
(register-error 5899 :ERROR_CLUSTER_WRONG_OS_VERSION "This computer cannot be made a member of a cluster because it does not have the correct version of Windows installed.")
(register-error 5900 :ERROR_CLUSTER_CANT_CREATE_DUP_CLUSTER_NAME "A cluster cannot be created with the specified cluster name because that cluster name is already in use. Specify a different name for the cluster.")
(register-error 5901 :ERROR_CLUSCFG_ALREADY_COMMITTED "The cluster configuration action has already been committed.")
(register-error 5902 :ERROR_CLUSCFG_ROLLBACK_FAILED "The cluster configuration action could not be rolled back.")
(register-error 5903 :ERROR_CLUSCFG_SYSTEM_DISK_DRIVE_LETTER_CONFLICT "The drive letter assigned to a system disk on one node conflicted with the drive letter assigned to a disk on another node.")
(register-error 5904 :ERROR_CLUSTER_OLD_VERSION "One or more nodes in the cluster are running a version of Windows that does not support this operation.")
(register-error 5905 :ERROR_CLUSTER_MISMATCHED_COMPUTER_ACCT_NAME "The name of the corresponding computer account doesn't match the Network Name for this resource.")
(register-error 5906 :ERROR_CLUSTER_NO_NET_ADAPTERS "No network adapters are available.")
(register-error 5907 :ERROR_CLUSTER_POISONED "The cluster node has been poisoned.")
(register-error 5908 :ERROR_CLUSTER_GROUP_MOVING "The group is unable to accept the request since it is moving to another node.")
(register-error 5909 :ERROR_CLUSTER_RESOURCE_TYPE_BUSY "The resource type cannot accept the request since is too busy performing another operation.")
(register-error 5910 :ERROR_RESOURCE_CALL_TIMED_OUT "The call to the cluster resource DLL timed out.")
(register-error 5911 :ERROR_INVALID_CLUSTER_IPV6_ADDRESS "The address is not valid for an IPv6 Address resource. A global IPv6 address is required, and it must match a cluster network. Compatibility addresses are not permitted.")
(register-error 5912 :ERROR_CLUSTER_INTERNAL_INVALID_FUNCTION "An internal cluster error occurred. A call to an invalid function was attempted.")
(register-error 5913 :ERROR_CLUSTER_PARAMETER_OUT_OF_BOUNDS "A parameter value is out of acceptable range.")
(register-error 5914 :ERROR_CLUSTER_PARTIAL_SEND "A network error occurred while sending data to another node in the cluster. The number of bytes transmitted was less than required.")
(register-error 5915 :ERROR_CLUSTER_REGISTRY_INVALID_FUNCTION "An invalid cluster registry operation was attempted.")
(register-error 5916 :ERROR_CLUSTER_INVALID_STRING_TERMINATION "An input string of characters is not properly terminated.")
(register-error 5917 :ERROR_CLUSTER_INVALID_STRING_FORMAT "An input string of characters is not in a valid format for the data it represents.")
(register-error 5918 :ERROR_CLUSTER_DATABASE_TRANSACTION_IN_PROGRESS "An internal cluster error occurred. A cluster database transaction was attempted while a transaction was already in progress.")
(register-error 5919 :ERROR_CLUSTER_DATABASE_TRANSACTION_NOT_IN_PROGRESS "An internal cluster error occurred. There was an attempt to commit a cluster database transaction while no transaction was in progress.")
(register-error 5920 :ERROR_CLUSTER_NULL_DATA "An internal cluster error occurred. Data was not properly initialized.")
(register-error 5921 :ERROR_CLUSTER_PARTIAL_READ "An error occurred while reading from a stream of data. An unexpected number of bytes was returned.")
(register-error 5922 :ERROR_CLUSTER_PARTIAL_WRITE "An error occurred while writing to a stream of data. The required number of bytes could not be written.")
(register-error 5923 :ERROR_CLUSTER_CANT_DESERIALIZE_DATA "An error occurred while deserializing a stream of cluster data.")
(register-error 5924 :ERROR_DEPENDENT_RESOURCE_PROPERTY_CONFLICT "One or more property values for this resource are in conflict with one or more property values associated with its dependent resource(s).")
(register-error 5925 :ERROR_CLUSTER_NO_QUORUM "A quorum of cluster nodes was not present to form a cluster.")
(register-error 5926 :ERROR_CLUSTER_INVALID_IPV6_NETWORK "The cluster network is not valid for an IPv6 Address resource, or it does not match the configured address.")
(register-error 5927 :ERROR_CLUSTER_INVALID_IPV6_TUNNEL_NETWORK "The cluster network is not valid for an IPv6 Tunnel resource. Check the configuration of the IP Address resource on which the IPv6 Tunnel resource depends.")
(register-error 5928 :ERROR_QUORUM_NOT_ALLOWED_IN_THIS_GROUP "Quorum resource cannot reside in the Available Storage group.")
(register-error 5929 :ERROR_DEPENDENCY_TREE_TOO_COMPLEX "The dependencies for this resource are nested too deeply.")
(register-error 5930 :ERROR_EXCEPTION_IN_RESOURCE_CALL "The call into the resource DLL raised an unhandled exception.")
(register-error 5931 :ERROR_CLUSTER_RHS_FAILED_INITIALIZATION "The RHS process failed to initialize.")
(register-error 5932 :ERROR_CLUSTER_NOT_INSTALLED "The Failover Clustering feature is not installed on this node.")
(register-error 5933 :ERROR_CLUSTER_RESOURCES_MUST_BE_ONLINE_ON_THE_SAME_NODE "The resources must be online on the same node for this operation.")
(register-error 5934 :ERROR_CLUSTER_MAX_NODES_IN_CLUSTER "A new node can not be added since this cluster is already at its maximum number of nodes.")
(register-error 5935 :ERROR_CLUSTER_TOO_MANY_NODES "This cluster can not be created since the specified number of nodes exceeds the maximum allowed limit.")
(register-error 5936 :ERROR_CLUSTER_OBJECT_ALREADY_USED "An attempt to use the specified cluster name failed because an enabled computer object with the given name already exists in the domain.")
(register-error 5937 :ERROR_NONCORE_GROUPS_FOUND "This cluster cannot be destroyed. It has non-core application groups which must be deleted before the cluster can be destroyed.")
(register-error 5938 :ERROR_FILE_SHARE_RESOURCE_CONFLICT "File share associated with file share witness resource cannot be hosted by this cluster or any of its nodes.")
(register-error 5939 :ERROR_CLUSTER_EVICT_INVALID_REQUEST "Eviction of this node is invalid at this time. Due to quorum requirements node eviction will result in cluster shutdown. If it is the last node in the cluster, destroy cluster command should be used.")
(register-error 5940 :ERROR_CLUSTER_SINGLETON_RESOURCE "Only one instance of this resource type is allowed in the cluster.")
(register-error 5941 :ERROR_CLUSTER_GROUP_SINGLETON_RESOURCE "Only one instance of this resource type is allowed per resource group.")
(register-error 5942 :ERROR_CLUSTER_RESOURCE_PROVIDER_FAILED "The resource failed to come online due to the failure of one or more provider resources.")
(register-error 5943 :ERROR_CLUSTER_RESOURCE_CONFIGURATION_ERROR "The resource has indicated that it cannot come online on any node.")
(register-error 5944 :ERROR_CLUSTER_GROUP_BUSY "The current operation cannot be performed on this group at this time.")
(register-error 5945 :ERROR_CLUSTER_NOT_SHARED_VOLUME "The directory or file is not located on a cluster shared volume.")
(register-error 5946 :ERROR_CLUSTER_INVALID_SECURITY_DESCRIPTOR "The Security Descriptor does not meet the requirements for a cluster.")
(register-error 5947 :ERROR_CLUSTER_SHARED_VOLUMES_IN_USE "There is one or more shared volumes resources configured in the cluster. Those resources must be moved to available storage in order for operation to succeed.")
(register-error 5948 :ERROR_CLUSTER_USE_SHARED_VOLUMES_API "This group or resource cannot be directly manipulated. Use shared volume APIs to perform desired operation.")
(register-error 5949 :ERROR_CLUSTER_BACKUP_IN_PROGRESS "Back up is in progress. Please wait for backup completion before trying this operation again.")
(register-error 5950 :ERROR_NON_CSV_PATH "The path does not belong to a cluster shared volume.")
(register-error 5951 :ERROR_CSV_VOLUME_NOT_LOCAL "The cluster shared volume is not locally mounted on this node.")
(register-error 5952 :ERROR_CLUSTER_WATCHDOG_TERMINATING "The cluster watchdog is terminating.")
(register-error 5953 :ERROR_CLUSTER_RESOURCE_VETOED_MOVE_INCOMPATIBLE_NODES "A resource vetoed a move between two nodes because they are incompatible.")
(register-error 5954 :ERROR_CLUSTER_INVALID_NODE_WEIGHT "The request is invalid either because node weight cannot be changed while the cluster is in disk-only quorum mode, or because changing the node weight would violate the minimum cluster quorum requirements.")
(register-error 5955 :ERROR_CLUSTER_RESOURCE_VETOED_CALL "The resource vetoed the call.")
(register-error 5956 :ERROR_RESMON_SYSTEM_RESOURCES_LACKING "Resource could not start or run because it could not reserve sufficient system resources.")
(register-error 5957 :ERROR_CLUSTER_RESOURCE_VETOED_MOVE_NOT_ENOUGH_RESOURCES_ON_DESTINATION "A resource vetoed a move between two nodes because the destination currently does not have enough resources to complete the operation.")
(register-error 5958 :ERROR_CLUSTER_RESOURCE_VETOED_MOVE_NOT_ENOUGH_RESOURCES_ON_SOURCE "A resource vetoed a move between two nodes because the source currently does not have enough resources to complete the operation.")
(register-error 5959 :ERROR_CLUSTER_GROUP_QUEUED "The requested operation can not be completed because the group is queued for an operation.")
(register-error 5960 :ERROR_CLUSTER_RESOURCE_LOCKED_STATUS "The requested operation can not be completed because a resource has locked status.")
(register-error 5961 :ERROR_CLUSTER_SHARED_VOLUME_FAILOVER_NOT_ALLOWED "The resource cannot move to another node because a cluster shared volume vetoed the operation.")
(register-error 5962 :ERROR_CLUSTER_NODE_DRAIN_IN_PROGRESS "A node drain is already in progress.")
(register-error 5963 :ERROR_CLUSTER_DISK_NOT_CONNECTED "Clustered storage is not connected to the node.")
(register-error 5964 :ERROR_DISK_NOT_CSV_CAPABLE "The disk is not configured in a way to be used with CSV. CSV disks must have at least one partition that is formatted with NTFS.")
(register-error 5965 :ERROR_RESOURCE_NOT_IN_AVAILABLE_STORAGE "The resource must be part of the Available Storage group to complete this action.")
(register-error 5966 :ERROR_CLUSTER_SHARED_VOLUME_REDIRECTED "CSVFS failed operation as volume is in redirected mode.")
(register-error 5967 :ERROR_CLUSTER_SHARED_VOLUME_NOT_REDIRECTED "CSVFS failed operation as volume is not in redirected mode.")
(register-error 5968 :ERROR_CLUSTER_CANNOT_RETURN_PROPERTIES "Cluster properties cannot be returned at this time.")
(register-error 5969 :ERROR_CLUSTER_RESOURCE_CONTAINS_UNSUPPORTED_DIFF_AREA_FOR_SHARED_VOLUMES "The clustered disk resource contains software snapshot diff area that are not supported for Cluster Shared Volumes.")
(register-error 5970 :ERROR_CLUSTER_RESOURCE_IS_IN_MAINTENANCE_MODE "The operation cannot be completed because the resource is in maintenance mode.")
(register-error 5971 :ERROR_CLUSTER_AFFINITY_CONFLICT "The operation cannot be completed because of cluster affinity conflicts.")
(register-error 5972 :ERROR_CLUSTER_RESOURCE_IS_REPLICA_VIRTUAL_MACHINE "The operation cannot be completed because the resource is a replica virtual machine.")

