;;;; src/dns.lisp
;;;
;;; Contains Domain Name System (DNS) related error codes.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; DNS Errors (9001-9906)
;;;--------------------------------------------------------------------------

(register-error 9001 :DNS_ERROR_RCODE_FORMAT_ERROR "DNS server unable to interpret format.")
(register-error 9002 :DNS_ERROR_RCODE_SERVER_FAILURE "DNS server failure.")
(register-error 9003 :DNS_ERROR_RCODE_NAME_ERROR "DNS name does not exist.")
(register-error 9004 :DNS_ERROR_RCODE_NOT_IMPLEMENTED "DNS request not supported by name server.")
(register-error 9005 :DNS_ERROR_RCODE_REFUSED "DNS operation refused.")
(register-error 9006 :DNS_ERROR_RCODE_YXDOMAIN "DNS name that ought not exist, does exist.")
(register-error 9007 :DNS_ERROR_RCODE_YXRRSET "DNS RR set that ought not exist, does exist.")
(register-error 9008 :DNS_ERROR_RCODE_NXRRSET "DNS RR set that ought to exist, does not exist.")
(register-error 9009 :DNS_ERROR_RCODE_NOTAUTH "DNS server not authoritative for zone.")
(register-error 9010 :DNS_ERROR_RCODE_NOTZONE "DNS name in update or prereq is not in zone.")
(register-error 9016 :DNS_ERROR_RCODE_BADSIG "DNS signature failed to verify.")
(register-error 9017 :DNS_ERROR_RCODE_BADKEY "DNS bad key.")
(register-error 9018 :DNS_ERROR_RCODE_BADTIME "DNS signature validity expired.")
(register-error 9101 :DNS_ERROR_KEYMASTER_REQUIRED "Only the DNS server acting as the key master for the zone may perform this operation.")
(register-error 9102 :DNS_ERROR_NOT_ALLOWED_ON_SIGNED_ZONE "This operation is not allowed on a zone that is signed or has signing keys.")
(register-error 9103 :DNS_ERROR_NSEC3_INCOMPATIBLE_WITH_RSA_SHA1 "NSEC3 is not compatible with the RSA-SHA-1 algorithm. Choose a different algorithm or use NSEC.")
(register-error 9104 :DNS_ERROR_NOT_ENOUGH_SIGNING_KEY_DESCRIPTORS "The zone does not have enough signing keys. There must be at least one key signing key (KSK) and at least one zone signing key (ZSK).")
(register-error 9105 :DNS_ERROR_UNSUPPORTED_ALGORITHM "The specified algorithm is not supported.")
(register-error 9106 :DNS_ERROR_INVALID_KEY_SIZE "The specified key size is not supported.")
(register-error 9107 :DNS_ERROR_SIGNING_KEY_NOT_ACCESSIBLE "One or more of the signing keys for a zone are not accessible to the DNS server. Zone signing will not be operational until this error is resolved.")
(register-error 9108 :DNS_ERROR_KSP_DOES_NOT_SUPPORT_PROTECTION "The specified key storage provider does not support DPAPI++ data protection. Zone signing will not be operational until this error is resolved.")
(register-error 9109 :DNS_ERROR_UNEXPECTED_DATA_PROTECTION_ERROR "An unexpected DPAPI++ error was encountered. Zone signing will not be operational until this error is resolved.")
(register-error 9110 :DNS_ERROR_UNEXPECTED_CNG_ERROR "An unexpected crypto error was encountered. Zone signing may not be operational until this error is resolved.")
(register-error 9111 :DNS_ERROR_UNKNOWN_SIGNING_PARAMETER_VERSION "The DNS server encountered a signing key with an unknown version. Zone signing will not be operational until this error is resolved.")
(register-error 9112 :DNS_ERROR_KSP_NOT_ACCESSIBLE "The specified key service provider cannot be opened by the DNS server.")
(register-error 9113 :DNS_ERROR_TOO_MANY_SKDS "The DNS server cannot accept any more signing keys with the specified algorithm and KSK flag value for this zone.")
(register-error 9114 :DNS_ERROR_INVALID_ROLLOVER_PERIOD "The specified rollover period is invalid.")
(register-error 9115 :DNS_ERROR_INVALID_INITIAL_ROLLOVER_OFFSET "The specified initial rollover offset is invalid.")
(register-error 9116 :DNS_ERROR_ROLLOVER_IN_PROGRESS "The specified signing key is already in process of rolling over keys.")
(register-error 9117 :DNS_ERROR_STANDBY_KEY_NOT_PRESENT "The specified signing key does not have a standby key to revoke.")
(register-error 9118 :DNS_ERROR_NOT_ALLOWED_ON_ZSK "This operation is not allowed on a zone signing key (ZSK).")
(register-error 9119 :DNS_ERROR_NOT_ALLOWED_ON_ACTIVE_SKD "This operation is not allowed on an active signing key.")
(register-error 9120 :DNS_ERROR_ROLLOVER_ALREADY_QUEUED "The specified signing key is already queued for rollover.")
(register-error 9121 :DNS_ERROR_NOT_ALLOWED_ON_UNSIGNED_ZONE "This operation is not allowed on an unsigned zone.")
(register-error 9122 :DNS_ERROR_BAD_KEYMASTER "This operation could not be completed because the DNS server listed as the current key master for this zone is down or misconfigured. Resolve the problem on the current key master for this zone or use another DNS server to seize the key master role.")
(register-error 9123 :DNS_ERROR_INVALID_SIGNATURE_VALIDITY_PERIOD "The specified signature validity period is invalid.")
(register-error 9124 :DNS_ERROR_INVALID_NSEC3_ITERATION_COUNT "The specified NSEC3 iteration count is higher than allowed by the minimum key length used in the zone.")
(register-error 9125 :DNS_ERROR_DNSSEC_IS_DISABLED "This operation could not be completed because the DNS server has been configured with DNSSEC features disabled. Enable DNSSEC on the DNS server.")
(register-error 9126 :DNS_ERROR_INVALID_XML "This operation could not be completed because the XML stream received is empty or syntactically invalid.")
(register-error 9127 :DNS_ERROR_NO_VALID_TRUST_ANCHORS "This operation completed, but no trust anchors were added because all of the trust anchors received were either invalid, unsupported, expired, or would not become valid in less than 30 days.")
(register-error 9128 :DNS_ERROR_ROLLOVER_NOT_POKEABLE "The specified signing key is not waiting for parental DS update.")
(register-error 9129 :DNS_ERROR_NSEC3_NAME_COLLISION "Hash collision detected during NSEC3 signing. Specify a different user-provided salt, or use a randomly generated salt, and attempt to sign the zone again.")
(register-error 9130 :DNS_ERROR_NSEC_INCOMPATIBLE_WITH_NSEC3_RSA_SHA1 "NSEC is not compatible with the NSEC3-RSA-SHA-1 algorithm. Choose a different algorithm or use NSEC3.")
(register-error 9501 :DNS_INFO_NO_RECORDS "No records found for given DNS query.")
(register-error 9502 :DNS_ERROR_BAD_PACKET "Bad DNS packet.")
(register-error 9503 :DNS_ERROR_NO_PACKET "No DNS packet.")
(register-error 9504 :DNS_ERROR_RCODE "DNS error, check rcode.")
(register-error 9505 :DNS_ERROR_UNSECURE_PACKET "Unsecured DNS packet.")
(register-error 9506 :DNS_REQUEST_PENDING "DNS query request is pending.")
(register-error 9551 :DNS_ERROR_INVALID_TYPE "Invalid DNS type.")
(register-error 9552 :DNS_ERROR_INVALID_IP_ADDRESS "Invalid IP address.")
(register-error 9553 :DNS_ERROR_INVALID_PROPERTY "Invalid property.")
(register-error 9554 :DNS_ERROR_TRY_AGAIN_LATER "Try DNS operation again later.")
(register-error 9555 :DNS_ERROR_NOT_UNIQUE "Record for given name and type is not unique.")
(register-error 9556 :DNS_ERROR_NON_RFC_NAME "DNS name does not comply with RFC specifications.")
(register-error 9557 :DNS_STATUS_FQDN "DNS name is a fully-qualified DNS name.")
(register-error 9558 :DNS_STATUS_DOTTED_NAME "DNS name is dotted (multi-label).")
(register-error 9559 :DNS_STATUS_SINGLE_PART_NAME "DNS name is a single-part name.")
(register-error 9560 :DNS_ERROR_INVALID_NAME_CHAR "DNS name contains an invalid character.")
(register-error 9561 :DNS_ERROR_NUMERIC_NAME "DNS name is entirely numeric.")
(register-error 9562 :DNS_ERROR_NOT_ALLOWED_ON_ROOT_SERVER "The operation requested is not permitted on a DNS root server.")
(register-error 9563 :DNS_ERROR_NOT_ALLOWED_UNDER_DELEGATION "The record could not be created because this part of the DNS namespace has been delegated to another server.")
(register-error 9564 :DNS_ERROR_CANNOT_FIND_ROOT_HINTS "The DNS server could not find a set of root hints.")
(register-error 9565 :DNS_ERROR_INCONSISTENT_ROOT_HINTS "The DNS server found root hints but they were not consistent across all adapters.")
(register-error 9566 :DNS_ERROR_DWORD_VALUE_TOO_SMALL "The specified value is too small for this parameter.")
(register-error 9567 :DNS_ERROR_DWORD_VALUE_TOO_LARGE "The specified value is too large for this parameter.")
(register-error 9568 :DNS_ERROR_BACKGROUND_LOADING "This operation is not allowed while the DNS server is loading zones in the background. Please try again later.")
(register-error 9569 :DNS_ERROR_NOT_ALLOWED_ON_RODC "The operation requested is not permitted on against a DNS server running on a read-only DC.")
(register-error 9570 :DNS_ERROR_NOT_ALLOWED_UNDER_DNAME "No data is allowed to exist underneath a DNAME record.")
(register-error 9571 :DNS_ERROR_DELEGATION_REQUIRED "This operation requires credentials delegation.")
(register-error 9572 :DNS_ERROR_INVALID_POLICY_TABLE "Name resolution policy table has been corrupted. DNS resolution will fail until it is fixed. Contact your network administrator.")
(register-error 9601 :DNS_ERROR_ZONE_DOES_NOT_EXIST "DNS zone does not exist.")
(register-error 9602 :DNS_ERROR_NO_ZONE_INFO "DNS zone information not available.")
(register-error 9603 :DNS_ERROR_INVALID_ZONE_OPERATION "Invalid operation for DNS zone.")
(register-error 9604 :DNS_ERROR_ZONE_CONFIGURATION_ERROR "Invalid DNS zone configuration.")
(register-error 9605 :DNS_ERROR_ZONE_HAS_NO_SOA_RECORD "DNS zone has no start of authority (SOA) record.")
(register-error 9606 :DNS_ERROR_ZONE_HAS_NO_NS_RECORDS "DNS zone has no Name Server (NS) record.")
(register-error 9607 :DNS_ERROR_ZONE_LOCKED "DNS zone is locked.")
(register-error 9608 :DNS_ERROR_ZONE_CREATION_FAILED "DNS zone creation failed.")
(register-error 9609 :DNS_ERROR_ZONE_ALREADY_EXISTS "DNS zone already exists.")
(register-error 9610 :DNS_ERROR_AUTOZONE_ALREADY_EXISTS "DNS automatic zone already exists.")
(register-error 9611 :DNS_ERROR_INVALID_ZONE_TYPE "Invalid DNS zone type.")
(register-error 9612 :DNS_ERROR_SECONDARY_REQUIRES_MASTER_IP "Secondary DNS zone requires master IP address.")
(register-error 9613 :DNS_ERROR_ZONE_NOT_SECONDARY "DNS zone not secondary.")
(register-error 9614 :DNS_ERROR_NEED_SECONDARY_ADDRESSES "Need secondary IP address.")
(register-error 9615 :DNS_ERROR_WINS_INIT_FAILED "WINS initialization failed.")
(register-error 9616 :DNS_ERROR_NEED_WINS_SERVERS "Need WINS servers.")
(register-error 9617 :DNS_ERROR_NBSTAT_INIT_FAILED "NBTSTAT initialization call failed.")
(register-error 9618 :DNS_ERROR_SOA_DELETE_INVALID "Invalid delete of start of authority (SOA).")
(register-error 9619 :DNS_ERROR_FORWARDER_ALREADY_EXISTS "A conditional forwarding zone already exists for that name.")
(register-error 9620 :DNS_ERROR_ZONE_REQUIRES_MASTER_IP "This zone must be configured with one or more master DNS server IP addresses.")
(register-error 9621 :DNS_ERROR_ZONE_IS_SHUTDOWN "The operation cannot be performed because this zone is shut down.")
(register-error 9622 :DNS_ERROR_ZONE_LOCKED_FOR_SIGNING "This operation cannot be performed because the zone is currently being signed. Please try again later.")
(register-error 9651 :DNS_ERROR_PRIMARY_REQUIRES_DATAFILE "Primary DNS zone requires datafile.")
(register-error 9652 :DNS_ERROR_INVALID_DATAFILE_NAME "Invalid datafile name for DNS zone.")
(register-error 9653 :DNS_ERROR_DATAFILE_OPEN_FAILURE "Failed to open datafile for DNS zone.")
(register-error 9654 :DNS_ERROR_FILE_WRITEBACK_FAILED "Failed to write datafile for DNS zone.")
(register-error 9655 :DNS_ERROR_DATAFILE_PARSING "Failure while reading datafile for DNS zone.")
(register-error 9701 :DNS_ERROR_RECORD_DOES_NOT_EXIST "DNS record does not exist.")
(register-error 9702 :DNS_ERROR_RECORD_FORMAT "DNS record format error.")
(register-error 9703 :DNS_ERROR_NODE_CREATION_FAILED "Node creation failure in DNS.")
(register-error 9704 :DNS_ERROR_UNKNOWN_RECORD_TYPE "Unknown DNS record type.")
(register-error 9705 :DNS_ERROR_RECORD_TIMED_OUT "DNS record timed out.")
(register-error 9706 :DNS_ERROR_NAME_NOT_IN_ZONE "Name not in DNS zone.")
(register-error 9707 :DNS_ERROR_CNAME_LOOP "CNAME loop detected.")
(register-error 9708 :DNS_ERROR_NODE_IS_CNAME "Node is a CNAME DNS record.")
(register-error 9709 :DNS_ERROR_CNAME_COLLISION "A CNAME record already exists for given name.")
(register-error 9710 :DNS_ERROR_RECORD_ONLY_AT_ZONE_ROOT "Record only at DNS zone root.")
(register-error 9711 :DNS_ERROR_RECORD_ALREADY_EXISTS "DNS record already exists.")
(register-error 9712 :DNS_ERROR_SECONDARY_DATA "Secondary DNS zone data error.")
(register-error 9713 :DNS_ERROR_NO_CREATE_CACHE_DATA "Could not create DNS cache data.")
(register-error 9714 :DNS_ERROR_NAME_DOES_NOT_EXIST "DNS name does not exist.")
(register-error 9715 :DNS_WARNING_PTR_CREATE_FAILED "Could not create pointer (PTR) record.")
(register-error 9716 :DNS_WARNING_DOMAIN_UNDELETED "DNS domain was undeleted.")
(register-error 9717 :DNS_ERROR_DS_UNAVAILABLE "The directory service is unavailable.")
(register-error 9718 :DNS_ERROR_DS_ZONE_ALREADY_EXISTS "DNS zone already exists in the directory service.")
(register-error 9719 :DNS_ERROR_NO_BOOTFILE_IF_DS_ZONE "DNS server not creating or reading the boot file for the directory service integrated DNS zone.")
(register-error 9720 :DNS_ERROR_NODE_IS_DNAME "Node is a DNAME DNS record.")
(register-error 9721 :DNS_ERROR_DNAME_COLLISION "A DNAME record already exists for given name.")
(register-error 9722 :DNS_ERROR_ALIAS_LOOP "An alias loop has been detected with either CNAME or DNAME records.")
(register-error 9751 :DNS_INFO_AXFR_COMPLETE "DNS AXFR (zone transfer) complete.")
(register-error 9752 :DNS_ERROR_AXFR "DNS zone transfer failed.")
(register-error 9753 :DNS_INFO_ADDED_LOCAL_WINS "Added local WINS server.")
(register-error 9801 :DNS_STATUS_CONTINUE_NEEDED "Secure update call needs to continue update request.")
(register-error 9851 :DNS_ERROR_NO_TCPIP "TCP/IP network protocol not installed.")
(register-error 9852 :DNS_ERROR_NO_DNS_SERVERS "No DNS servers configured for local system.")
(register-error 9901 :DNS_ERROR_DP_DOES_NOT_EXIST "The specified directory partition does not exist.")
(register-error 9902 :DNS_ERROR_DP_ALREADY_EXISTS "The specified directory partition already exists.")
(register-error 9903 :DNS_ERROR_DP_NOT_ENLISTED "This DNS server is not enlisted in the specified directory partition.")
(register-error 9904 :DNS_ERROR_DP_ALREADY_ENLISTED "This DNS server is already enlisted in the specified directory partition.")
(register-error 9905 :DNS_ERROR_DP_NOT_AVAILABLE "The directory partition is not available at this time. Please wait a few minutes and try again.")
(register-error 9906 :DNS_ERROR_DP_FSMO_ERROR "The operation failed because the domain naming master FSMO role could not be reached. The domain controller holding the domain naming master FSMO role is down or unable to service the request or is not running Windows Server 2003 or later.")

