;;;; src/ds.lisp
;;;
;;; Contains Directory Service (Active Directory) related error codes.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; Directory Service Errors (8200-8646)
;;;--------------------------------------------------------------------------

(register-error 8200 :ERROR_DS_NOT_INSTALLED "An error occurred while installing the directory service. For more information, see the event log.")
(register-error 8201 :ERROR_DS_MEMBERSHIP_EVALUATED_LOCALLY "The directory service evaluated group memberships locally.")
(register-error 8202 :ERROR_DS_NO_ATTRIBUTE_OR_VALUE "The specified directory service attribute or value does not exist.")
(register-error 8203 :ERROR_DS_INVALID_ATTRIBUTE_SYNTAX "The attribute syntax specified to the directory service is invalid.")
(register-error 8204 :ERROR_DS_ATTRIBUTE_TYPE_UNDEFINED "The attribute type specified to the directory service is not defined.")
(register-error 8205 :ERROR_DS_ATTRIBUTE_OR_VALUE_EXISTS "The specified directory service attribute or value already exists.")
(register-error 8206 :ERROR_DS_BUSY "The directory service is busy.")
(register-error 8207 :ERROR_DS_UNAVAILABLE "The directory service is unavailable.")
(register-error 8208 :ERROR_DS_NO_RIDS_ALLOCATED "The directory service was unable to allocate a relative identifier.")
(register-error 8209 :ERROR_DS_NO_MORE_RIDS "The directory service has exhausted the pool of relative identifiers.")
(register-error 8210 :ERROR_DS_INCORRECT_ROLE_OWNER "The requested operation could not be performed because the directory service is not the master for that type of operation.")
(register-error 8211 :ERROR_DS_RIDMGR_INIT_ERROR "The directory service was unable to initialize the subsystem that allocates relative identifiers.")
(register-error 8212 :ERROR_DS_OBJ_CLASS_VIOLATION "The requested operation did not satisfy one or more constraints associated with the class of the object.")
(register-error 8213 :ERROR_DS_CANT_ON_NON_LEAF "The directory service can perform the requested operation only on a leaf object.")
(register-error 8214 :ERROR_DS_CANT_ON_RDN "The directory service cannot perform the requested operation on the RDN attribute of an object.")
(register-error 8215 :ERROR_DS_CANT_MOD_OBJ_CLASS "The directory service detected an attempt to modify the object class of an object.")
(register-error 8216 :ERROR_DS_CROSS_DOM_MOVE_ERROR "The requested cross-domain move operation could not be performed.")
(register-error 8217 :ERROR_DS_GC_NOT_AVAILABLE "Unable to contact the global catalog server.")
(register-error 8218 :ERROR_SHARED_POLICY "The policy object is shared and can only be modified at the root.")
(register-error 8219 :ERROR_POLICY_OBJECT_NOT_FOUND "The policy object does not exist.")
(register-error 8220 :ERROR_POLICY_ONLY_IN_DS "The requested policy information is only in the directory service.")
(register-error 8221 :ERROR_PROMOTION_ACTIVE "A domain controller promotion is currently active.")
(register-error 8222 :ERROR_NO_PROMOTION_ACTIVE "A domain controller promotion is not currently active.")
(register-error 8224 :ERROR_DS_OPERATIONS_ERROR "An operations error occurred.")
(register-error 8225 :ERROR_DS_PROTOCOL_ERROR "A protocol error occurred.")
(register-error 8226 :ERROR_DS_TIMELIMIT_EXCEEDED "The time limit for this request was exceeded.")
(register-error 8227 :ERROR_DS_SIZELIMIT_EXCEEDED "The size limit for this request was exceeded.")
(register-error 8228 :ERROR_DS_ADMIN_LIMIT_EXCEEDED "The administrative limit for this request was exceeded.")
(register-error 8229 :ERROR_DS_COMPARE_FALSE "The compare response was false.")
(register-error 8230 :ERROR_DS_COMPARE_TRUE "The compare response was true.")
(register-error 8231 :ERROR_DS_AUTH_METHOD_NOT_SUPPORTED "The requested authentication method is not supported by the server.")
(register-error 8232 :ERROR_DS_STRONG_AUTH_REQUIRED "A more secure authentication method is required for this server.")
(register-error 8233 :ERROR_DS_INAPPROPRIATE_AUTH "Inappropriate authentication.")
(register-error 8234 :ERROR_DS_AUTH_UNKNOWN "The authentication mechanism is unknown.")
(register-error 8235 :ERROR_DS_REFERRAL "A referral was returned from the server.")
(register-error 8236 :ERROR_DS_UNAVAILABLE_CRIT_EXTENSION "The server does not support the requested critical extension.")
(register-error 8237 :ERROR_DS_CONFIDENTIALITY_REQUIRED "This request requires a secure connection.")
(register-error 8238 :ERROR_DS_INAPPROPRIATE_MATCHING "Inappropriate matching.")
(register-error 8239 :ERROR_DS_CONSTRAINT_VIOLATION "A constraint violation occurred.")
(register-error 8240 :ERROR_DS_NO_SUCH_OBJECT "There is no such object on the server.")
(register-error 8241 :ERROR_DS_ALIAS_PROBLEM "There is an alias problem.")
(register-error 8242 :ERROR_DS_INVALID_DN_SYNTAX "An invalid dn syntax has been specified.")
(register-error 8243 :ERROR_DS_IS_LEAF "The object is a leaf object.")
(register-error 8244 :ERROR_DS_ALIAS_DEREF_PROBLEM "There is an alias dereferencing problem.")
(register-error 8245 :ERROR_DS_UNWILLING_TO_PERFORM "The server is unwilling to process the request.")
(register-error 8246 :ERROR_DS_LOOP_DETECT "A loop has been detected.")
(register-error 8247 :ERROR_DS_NAMING_VIOLATION "There is a naming violation.")
(register-error 8248 :ERROR_DS_OBJECT_RESULTS_TOO_LARGE "The result set is too large.")
(register-error 8249 :ERROR_DS_AFFECTS_MULTIPLE_DSAS "The operation affects multiple DSAs.")
(register-error 8250 :ERROR_DS_SERVER_DOWN "The server is not operational.")
(register-error 8251 :ERROR_DS_LOCAL_ERROR "A local error has occurred.")
(register-error 8252 :ERROR_DS_ENCODING_ERROR "An encoding error has occurred.")
(register-error 8253 :ERROR_DS_DECODING_ERROR "A decoding error has occurred.")
(register-error 8254 :ERROR_DS_FILTER_UNKNOWN "The search filter cannot be recognized.")
(register-error 8255 :ERROR_DS_PARAM_ERROR "One or more parameters are illegal.")
(register-error 8256 :ERROR_DS_NOT_SUPPORTED "The specified method is not supported.")
(register-error 8257 :ERROR_DS_NO_RESULTS_RETURNED "No results were returned.")
(register-error 8258 :ERROR_DS_CONTROL_NOT_FOUND "The specified control is not supported by the server.")
(register-error 8259 :ERROR_DS_CLIENT_LOOP "A referral loop was detected by the client.")
(register-error 8260 :ERROR_DS_REFERRAL_LIMIT_EXCEEDED "The preset referral limit was exceeded.")
(register-error 8261 :ERROR_DS_SORT_CONTROL_MISSING "The search requires a SORT control.")
(register-error 8262 :ERROR_DS_OFFSET_RANGE_ERROR "The search results exceed the offset range specified.")
(register-error 8263 :ERROR_DS_RIDMGR_DISABLED "The directory service detected the subsystem that allocates relative identifiers is disabled. This can occur as a protective mechanism when the system determines a significant portion of relative identifiers (RIDs) have been exhausted. Please see https://go.microsoft.com/fwlink/p/?linkid=228610 for recommended diagnostic steps and the procedure to re-enable account creation.")
(register-error 8301 :ERROR_DS_ROOT_MUST_BE_NC "The root object must be the head of a naming context. The root object cannot have an instantiated parent.")
(register-error 8302 :ERROR_DS_ADD_REPLICA_INHIBITED "The add replica operation cannot be performed. The naming context must be writeable in order to create the replica.")
(register-error 8303 :ERROR_DS_ATT_NOT_DEF_IN_SCHEMA "A reference to an attribute that is not defined in the schema occurred.")
(register-error 8304 :ERROR_DS_MAX_OBJ_SIZE_EXCEEDED "The maximum size of an object has been exceeded.")
(register-error 8305 :ERROR_DS_OBJ_STRING_NAME_EXISTS "An attempt was made to add an object to the directory with a name that is already in use.")
(register-error 8306 :ERROR_DS_NO_RDN_DEFINED_IN_SCHEMA "An attempt was made to add an object of a class that does not have an RDN defined in the schema.")
(register-error 8307 :ERROR_DS_RDN_DOESNT_MATCH_SCHEMA "An attempt was made to add an object using an RDN that is not the RDN defined in the schema.")
(register-error 8308 :ERROR_DS_NO_REQUESTED_ATTS_FOUND "None of the requested attributes were found on the objects.")
(register-error 8309 :ERROR_DS_USER_BUFFER_TO_SMALL "The user buffer is too small.")
(register-error 8310 :ERROR_DS_ATT_IS_NOT_ON_OBJ "The attribute specified in the operation is not present on the object.")
(register-error 8311 :ERROR_DS_ILLEGAL_MOD_OPERATION "Illegal modify operation. Some aspect of the modification is not permitted.")
(register-error 8312 :ERROR_DS_OBJ_TOO_LARGE "The specified object is too large.")
(register-error 8313 :ERROR_DS_BAD_INSTANCE_TYPE "The specified instance type is not valid.")
(register-error 8314 :ERROR_DS_MASTERDSA_REQUIRED "The operation must be performed at a master DSA.")
(register-error 8315 :ERROR_DS_OBJECT_CLASS_REQUIRED "The object class attribute must be specified.")
(register-error 8316 :ERROR_DS_MISSING_REQUIRED_ATT "A required attribute is missing.")
(register-error 8317 :ERROR_DS_ATT_NOT_DEF_FOR_CLASS "An attempt was made to modify an object to include an attribute that is not legal for its class.")
(register-error 8318 :ERROR_DS_ATT_ALREADY_EXISTS "The specified attribute is already present on the object.")
(register-error 8320 :ERROR_DS_CANT_ADD_ATT_VALUES "The specified attribute is not present, or has no values.")
(register-error 8321 :ERROR_DS_SINGLE_VALUE_CONSTRAINT "Multiple values were specified for an attribute that can have only one value.")
(register-error 8322 :ERROR_DS_RANGE_CONSTRAINT "A value for the attribute was not in the acceptable range of values.")
(register-error 8323 :ERROR_DS_ATT_VAL_ALREADY_EXISTS "The specified value already exists.")
(register-error 8324 :ERROR_DS_CANT_REM_MISSING_ATT "The attribute cannot be removed because it is not present on the object.")
(register-error 8325 :ERROR_DS_CANT_REM_MISSING_ATT_VAL "The attribute value cannot be removed because it is not present on the object.")
(register-error 8326 :ERROR_DS_ROOT_CANT_BE_SUBREF "The specified root object cannot be a subref.")
(register-error 8327 :ERROR_DS_NO_CHAINING "Chaining is not permitted.")
(register-error 8328 :ERROR_DS_NO_CHAINED_EVAL "Chained evaluation is not permitted.")
(register-error 8329 :ERROR_DS_NO_PARENT_OBJECT "The operation could not be performed because the object's parent is either uninstantiated or deleted.")
(register-error 8330 :ERROR_DS_PARENT_IS_AN_ALIAS "Having a parent that is an alias is not permitted. Aliases are leaf objects.")
(register-error 8331 :ERROR_DS_CANT_MIX_MASTER_AND_REPS "The object and parent must be of the same type, either both masters or both replicas.")
(register-error 8332 :ERROR_DS_CHILDREN_EXIST "The operation cannot be performed because child objects exist. This operation can only be performed on a leaf object.")
(register-error 8333 :ERROR_DS_OBJ_NOT_FOUND "Directory object not found.")
(register-error 8334 :ERROR_DS_ALIASED_OBJ_MISSING "The aliased object is missing.")
(register-error 8335 :ERROR_DS_BAD_NAME_SYNTAX "The object name has bad syntax.")
(register-error 8336 :ERROR_DS_ALIAS_POINTS_TO_ALIAS "It is not permitted for an alias to refer to another alias.")
(register-error 8337 :ERROR_DS_CANT_DEREF_ALIAS "The alias cannot be dereferenced.")
(register-error 8338 :ERROR_DS_OUT_OF_SCOPE "The operation is out of scope.")
(register-error 8339 :ERROR_DS_OBJECT_BEING_REMOVED "The operation cannot continue because the object is in the process of being removed.")
(register-error 8340 :ERROR_DS_CANT_DELETE_DSA_OBJ "The DSA object cannot be deleted.")
(register-error 8341 :ERROR_DS_GENERIC_ERROR "A directory service error has occurred.")
(register-error 8342 :ERROR_DS_DSA_MUST_BE_INT_MASTER "The operation can only be performed on an internal master DSA object.")
(register-error 8343 :ERROR_DS_CLASS_NOT_DSA "The object must be of class DSA.")
(register-error 8344 :ERROR_DS_INSUFF_ACCESS_RIGHTS "Insufficient access rights to perform the operation.")
(register-error 8345 :ERROR_DS_ILLEGAL_SUPERIOR "The object cannot be added because the parent is not on the list of possible superiors.")
(register-error 8346 :ERROR_DS_ATTRIBUTE_OWNED_BY_SAM "Access to the attribute is not permitted because the attribute is owned by the Security Accounts Manager (SAM).")
(register-error 8347 :ERROR_DS_NAME_TOO_MANY_PARTS "The name has too many parts.")
(register-error 8348 :ERROR_DS_NAME_TOO_LONG "The name is too long.")
(register-error 8349 :ERROR_DS_NAME_VALUE_TOO_LONG "The name value is too long.")
(register-error 8350 :ERROR_DS_NAME_UNPARSEABLE "The directory service encountered an error parsing a name.")
(register-error 8351 :ERROR_DS_NAME_TYPE_UNKNOWN "The directory service cannot get the attribute type for a name.")
(register-error 8352 :ERROR_DS_NOT_AN_OBJECT "The name does not identify an object; the name identifies a phantom.")
(register-error 8353 :ERROR_DS_SEC_DESC_TOO_SHORT "The security descriptor is too short.")
(register-error 8354 :ERROR_DS_SEC_DESC_INVALID "The security descriptor is invalid.")
(register-error 8355 :ERROR_DS_NO_DELETED_NAME "Failed to create name for deleted object.")
(register-error 8356 :ERROR_DS_SUBREF_MUST_HAVE_PARENT "The parent of a new subref must exist.")
(register-error 8357 :ERROR_DS_NCNAME_MUST_BE_NC "The object must be a naming context.")
(register-error 8358 :ERROR_DS_CANT_ADD_SYSTEM_ONLY "It is not permitted to add an attribute which is owned by the system.")
(register-error 8359 :ERROR_DS_CLASS_MUST_BE_CONCRETE "The class of the object must be structural; you cannot instantiate an abstract class.")
(register-error 8360 :ERROR_DS_INVALID_DMD "The schema object could not be found.")
(register-error 8361 :ERROR_DS_OBJ_GUID_EXISTS "A local object with this GUID (dead or alive) already exists.")
(register-error 8362 :ERROR_DS_NOT_ON_BACKLINK "The operation cannot be performed on a back link.")
(register-error 8363 :ERROR_DS_NO_CROSSREF_FOR_NC "The cross reference for the specified naming context could not be found.")
(register-error 8364 :ERROR_DS_SHUTTING_DOWN "The operation could not be performed because the directory service is shutting down.")
(register-error 8365 :ERROR_DS_UNKNOWN_OPERATION "The directory service request is invalid.")
(register-error 8366 :ERROR_DS_INVALID_ROLE_OWNER "The role owner attribute could not be read.")
(register-error 8367 :ERROR_DS_COULDNT_CONTACT_FSMO "The requested FSMO operation failed. The current FSMO holder could not be contacted.")
(register-error 8368 :ERROR_DS_CROSS_NC_DN_RENAME "Modification of a DN across a naming context is not permitted.")
(register-error 8369 :ERROR_DS_CANT_MOD_SYSTEM_ONLY "The attribute cannot be modified because it is owned by the system.")
(register-error 8370 :ERROR_DS_REPLICATOR_ONLY "Only the replicator can perform this function.")
(register-error 8371 :ERROR_DS_OBJ_CLASS_NOT_DEFINED "The specified class is not defined.")
(register-error 8372 :ERROR_DS_OBJ_CLASS_NOT_SUBCLASS "The specified class is not a subclass.")
(register-error 8373 :ERROR_DS_NAME_REFERENCE_INVALID "The name reference is invalid.")
(register-error 8374 :ERROR_DS_CROSS_REF_EXISTS "A cross reference already exists.")
(register-error 8375 :ERROR_DS_CANT_DEL_MASTER_CROSSREF "It is not permitted to delete a master cross reference.")
(register-error 8376 :ERROR_DS_SUBTREE_NOTIFY_NOT_NC_HEAD "Subtree notifications are only supported on NC heads.")
(register-error 8377 :ERROR_DS_NOTIFY_FILTER_TOO_COMPLEX "Notification filter is too complex.")
(register-error 8378 :ERROR_DS_DUP_RDN "Schema update failed: duplicate RDN.")
(register-error 8379 :ERROR_DS_DUP_OID "Schema update failed: duplicate OID.")
(register-error 8380 :ERROR_DS_DUP_MAPI_ID "Schema update failed: duplicate MAPI identifier.")
(register-error 8381 :ERROR_DS_DUP_SCHEMA_ID_GUID "Schema update failed: duplicate schema-id GUID.")
(register-error 8382 :ERROR_DS_DUP_LDAP_DISPLAY_NAME "Schema update failed: duplicate LDAP display name.")
(register-error 8383 :ERROR_DS_SEMANTIC_ATT_TEST "Schema update failed: range-lower less than range upper.")
(register-error 8384 :ERROR_DS_SYNTAX_MISMATCH "Schema update failed: syntax mismatch.")
(register-error 8385 :ERROR_DS_EXISTS_IN_MUST_HAVE "Schema deletion failed: attribute is used in must-contain.")
(register-error 8386 :ERROR_DS_EXISTS_IN_MAY_HAVE "Schema deletion failed: attribute is used in may-contain.")
(register-error 8387 :ERROR_DS_NONEXISTENT_MAY_HAVE "Schema update failed: attribute in may-contain does not exist.")
(register-error 8388 :ERROR_DS_NONEXISTENT_MUST_HAVE "Schema update failed: attribute in must-contain does not exist.")
(register-error 8389 :ERROR_DS_AUX_CLS_TEST_FAIL "Schema update failed: class in aux-class list does not exist or is not an auxiliary class.")
(register-error 8390 :ERROR_DS_NONEXISTENT_POSS_SUP "Schema update failed: class in poss-superiors does not exist.")
(register-error 8391 :ERROR_DS_SUB_CLS_TEST_FAIL "Schema update failed: class in subclassof list does not exist or does not satisfy hierarchy rules.")
(register-error 8392 :ERROR_DS_BAD_RDN_ATT_ID_SYNTAX "Schema update failed: Rdn-Att-Id has wrong syntax.")
(register-error 8393 :ERROR_DS_EXISTS_IN_AUX_CLS "Schema deletion failed: class is used as auxiliary class.")
(register-error 8394 :ERROR_DS_EXISTS_IN_SUB_CLS "Schema deletion failed: class is used as sub class.")
(register-error 8395 :ERROR_DS_EXISTS_IN_POSS_SUP "Schema deletion failed: class is used as poss superior.")
(register-error 8396 :ERROR_DS_RECALCSCHEMA_FAILED "Schema update failed in recalculating validation cache.")
(register-error 8397 :ERROR_DS_TREE_DELETE_NOT_FINISHED "The tree deletion is not finished. The request must be made again to continue deleting the tree.")
(register-error 8398 :ERROR_DS_CANT_DELETE "The requested delete operation could not be performed.")
(register-error 8399 :ERROR_DS_ATT_SCHEMA_REQ_ID "Cannot read the governs class identifier for the schema record.")
(register-error 8400 :ERROR_DS_BAD_ATT_SCHEMA_SYNTAX "The attribute schema has bad syntax.")
(register-error 8401 :ERROR_DS_CANT_CACHE_ATT "The attribute could not be cached.")
(register-error 8402 :ERROR_DS_CANT_CACHE_CLASS "The class could not be cached.")
(register-error 8403 :ERROR_DS_CANT_REMOVE_ATT_CACHE "The attribute could not be removed from the cache.")
(register-error 8404 :ERROR_DS_CANT_REMOVE_CLASS_CACHE "The class could not be removed from the cache.")
(register-error 8405 :ERROR_DS_CANT_RETRIEVE_DN "The distinguished name attribute could not be read.")
(register-error 8406 :ERROR_DS_MISSING_SUPREF "No superior reference has been configured for the directory service. The directory service is therefore unable to issue referrals to objects outside this forest.")
(register-error 8407 :ERROR_DS_CANT_RETRIEVE_INSTANCE "The instance type attribute could not be retrieved.")
(register-error 8408 :ERROR_DS_CODE_INCONSISTENCY "An internal error has occurred.")
(register-error 8409 :ERROR_DS_DATABASE_ERROR "A database error has occurred.")
(register-error 8410 :ERROR_DS_GOVERNSID_MISSING "The attribute GOVERNSID is missing.")
(register-error 8411 :ERROR_DS_MISSING_EXPECTED_ATT "An expected attribute is missing.")
(register-error 8412 :ERROR_DS_NCNAME_MISSING_CR_REF "The specified naming context is missing a cross reference.")
(register-error 8413 :ERROR_DS_SECURITY_CHECKING_ERROR "A security checking error has occurred.")
(register-error 8414 :ERROR_DS_SCHEMA_NOT_LOADED "The schema is not loaded.")
(register-error 8415 :ERROR_DS_SCHEMA_ALLOC_FAILED "Schema allocation failed. Please check if the machine is running low on memory.")
(register-error 8416 :ERROR_DS_ATT_SCHEMA_REQ_SYNTAX "Failed to obtain the required syntax for the attribute schema.")
(register-error 8417 :ERROR_DS_GCVERIFY_ERROR "The global catalog verification failed. The global catalog is not available or does not support the operation. Some part of the directory is currently not available.")
(register-error 8418 :ERROR_DS_DRA_SCHEMA_MISMATCH "The replication operation failed because of a schema mismatch between the servers involved.")
(register-error 8419 :ERROR_DS_CANT_FIND_DSA_OBJ "The DSA object could not be found.")
(register-error 8420 :ERROR_DS_CANT_FIND_EXPECTED_NC "The naming context could not be found.")
(register-error 8421 :ERROR_DS_CANT_FIND_NC_IN_CACHE "The naming context could not be found in the cache.")
(register-error 8422 :ERROR_DS_CANT_RETRIEVE_CHILD "The child object could not be retrieved.")
(register-error 8423 :ERROR_DS_SECURITY_ILLEGAL_MODIFY "The modification was not permitted for security reasons.")
(register-error 8424 :ERROR_DS_CANT_REPLACE_HIDDEN_REC "The operation cannot replace the hidden record.")
(register-error 8425 :ERROR_DS_BAD_HIERARCHY_FILE "The hierarchy file is invalid.")
(register-error 8426 :ERROR_DS_BUILD_HIERARCHY_TABLE_FAILED "The attempt to build the hierarchy table failed.")
(register-error 8427 :ERROR_DS_CONFIG_PARAM_MISSING "The directory configuration parameter is missing from the registry.")
(register-error 8428 :ERROR_DS_COUNTING_AB_INDICES_FAILED "The attempt to count the address book indices failed.")
(register-error 8429 :ERROR_DS_HIERARCHY_TABLE_MALLOC_FAILED "The allocation of the hierarchy table failed.")
(register-error 8430 :ERROR_DS_INTERNAL_FAILURE "The directory service encountered an internal failure.")
(register-error 8431 :ERROR_DS_UNKNOWN_ERROR "The directory service encountered an unknown failure.")
(register-error 8432 :ERROR_DS_ROOT_REQUIRES_CLASS_TOP "A root object requires a class of 'top'.")
(register-error 8433 :ERROR_DS_REFUSING_FSMO_ROLES "This directory server is shutting down, and cannot take ownership of new floating single-master operation roles.")
(register-error 8434 :ERROR_DS_MISSING_FSMO_SETTINGS "The directory service is missing mandatory configuration information, and is unable to determine the ownership of floating single-master operation roles.")
(register-error 8435 :ERROR_DS_UNABLE_TO_SURRENDER_ROLES "The directory service was unable to transfer ownership of one or more floating single-master operation roles to other servers.")
(register-error 8436 :ERROR_DS_DRA_GENERIC "The replication operation failed.")
(register-error 8437 :ERROR_DS_DRA_INVALID_PARAMETER "An invalid parameter was specified for this replication operation.")
(register-error 8438 :ERROR_DS_DRA_BUSY "The directory service is too busy to complete the replication operation at this time.")
(register-error 8439 :ERROR_DS_DRA_BAD_DN "The distinguished name specified for this replication operation is invalid.")
(register-error 8440 :ERROR_DS_DRA_BAD_NC "The naming context specified for this replication operation is invalid.")
(register-error 8441 :ERROR_DS_DRA_DN_EXISTS "The distinguished name specified for this replication operation already exists.")
(register-error 8442 :ERROR_DS_DRA_INTERNAL_ERROR "The replication system encountered an internal error.")
(register-error 8443 :ERROR_DS_DRA_INCONSISTENT_DIT "The replication operation encountered a database inconsistency.")
(register-error 8444 :ERROR_DS_DRA_CONNECTION_FAILED "The server specified for this replication operation could not be contacted.")
(register-error 8445 :ERROR_DS_DRA_BAD_INSTANCE_TYPE "The replication operation encountered an object with an invalid instance type.")
(register-error 8446 :ERROR_DS_DRA_OUT_OF_MEM "The replication operation failed to allocate memory.")
(register-error 8447 :ERROR_DS_DRA_MAIL_PROBLEM "The replication operation encountered an error with the mail system.")
(register-error 8448 :ERROR_DS_DRA_REF_ALREADY_EXISTS "The replication reference information for the target server already exists.")
(register-error 8449 :ERROR_DS_DRA_REF_NOT_FOUND "The replication reference information for the target server does not exist.")
(register-error 8450 :ERROR_DS_DRA_OBJ_IS_REP_SOURCE "The naming context cannot be removed because it is replicated to another server.")
(register-error 8451 :ERROR_DS_DRA_DB_ERROR "The replication operation encountered a database error.")
(register-error 8452 :ERROR_DS_DRA_NO_REPLICA "The naming context is in the process of being removed or is not replicated from the specified server.")
(register-error 8453 :ERROR_DS_DRA_ACCESS_DENIED "Replication access was denied.")
(register-error 8454 :ERROR_DS_DRA_NOT_SUPPORTED "The requested operation is not supported by this version of the directory service.")
(register-error 8455 :ERROR_DS_DRA_RPC_CANCELLED "The replication remote procedure call was cancelled.")
(register-error 8456 :ERROR_DS_DRA_SOURCE_DISABLED "The source server is currently rejecting replication requests.")
(register-error 8457 :ERROR_DS_DRA_SINK_DISABLED "The destination server is currently rejecting replication requests.")
(register-error 8458 :ERROR_DS_DRA_NAME_COLLISION "The replication operation failed due to a collision of object names.")
(register-error 8459 :ERROR_DS_DRA_SOURCE_REINSTALLED "The replication source has been reinstalled.")
(register-error 8460 :ERROR_DS_DRA_MISSING_PARENT "The replication operation failed because a required parent object is missing.")
(register-error 8461 :ERROR_DS_DRA_PREEMPTED "The replication operation was preempted.")
(register-error 8462 :ERROR_DS_DRA_ABANDON_SYNC "The replication synchronization attempt was abandoned because of a lack of updates.")
(register-error 8463 :ERROR_DS_DRA_SHUTDOWN "The replication operation was terminated because the system is shutting down.")
(register-error 8464 :ERROR_DS_DRA_INCOMPATIBLE_PARTIAL_SET "Synchronization attempt failed because the destination DC is currently waiting to synchronize new partial attributes from source. This condition is normal if a recent schema change modified the partial attribute set. The destination partial attribute set is not a subset of source partial attribute set.")
(register-error 8465 :ERROR_DS_DRA_SOURCE_IS_PARTIAL_REPLICA "The replication synchronization attempt failed because a master replica attempted to sync from a partial replica.")
(register-error 8466 :ERROR_DS_DRA_EXTN_CONNECTION_FAILED "The server specified for this replication operation was contacted, but that server was unable to contact an additional server needed to complete the operation.")
(register-error 8467 :ERROR_DS_INSTALL_SCHEMA_MISMATCH "The version of the directory service schema of the source forest is not compatible with the version of directory service on this computer.")
(register-error 8468 :ERROR_DS_DUP_LINK_ID "Schema update failed: An attribute with the same link identifier already exists.")
(register-error 8469 :ERROR_DS_NAME_ERROR_RESOLVING "Name translation: Generic processing error.")
(register-error 8470 :ERROR_DS_NAME_ERROR_NOT_FOUND "Name translation: Could not find the name or insufficient right to see name.")
(register-error 8471 :ERROR_DS_NAME_ERROR_NOT_UNIQUE "Name translation: Input name mapped to more than one output name.")
(register-error 8472 :ERROR_DS_NAME_ERROR_NO_MAPPING "Name translation: Input name found, but not the associated output format.")
(register-error 8473 :ERROR_DS_NAME_ERROR_DOMAIN_ONLY "Name translation: Unable to resolve completely, only the domain was found.")
(register-error 8474 :ERROR_DS_NAME_ERROR_NO_SYNTACTICAL_MAPPING "Name translation: Unable to perform purely syntactical mapping at the client without going out to the wire.")
(register-error 8475 :ERROR_DS_CONSTRUCTED_ATT_MOD "Modification of a constructed attribute is not allowed.")
(register-error 8476 :ERROR_DS_WRONG_OM_OBJ_CLASS "The OM-Object-Class specified is incorrect for an attribute with the specified syntax.")
(register-error 8477 :ERROR_DS_DRA_REPL_PENDING "The replication request has been posted; waiting for reply.")
(register-error 8478 :ERROR_DS_DS_REQUIRED "The requested operation requires a directory service, and none was available.")
(register-error 8479 :ERROR_DS_INVALID_LDAP_DISPLAY_NAME "The LDAP display name of the class or attribute contains non-ASCII characters.")
(register-error 8480 :ERROR_DS_NON_BASE_SEARCH "The requested search operation is only supported for base searches.")
(register-error 8481 :ERROR_DS_CANT_RETRIEVE_ATTS "The search failed to retrieve attributes from the database.")
(register-error 8482 :ERROR_DS_BACKLINK_WITHOUT_LINK "The schema update operation tried to add a backward link attribute that has no corresponding forward link.")
(register-error 8483 :ERROR_DS_EPOCH_MISMATCH "Source and destination of a cross-domain move do not agree on the object's epoch number. Either source or destination does not have the latest version of the object.")
(register-error 8484 :ERROR_DS_SRC_NAME_MISMATCH "Source and destination of a cross-domain move do not agree on the object's current name. Either source or destination does not have the latest version of the object.")
(register-error 8485 :ERROR_DS_SRC_AND_DST_NC_IDENTICAL "Source and destination for the cross-domain move operation are identical. Caller should use local move operation instead of cross-domain move operation.")
(register-error 8486 :ERROR_DS_DST_NC_MISMATCH "Source and destination for a cross-domain move are not in agreement on the naming contexts in the forest. Either source or destination does not have the latest version of the Partitions container.")
(register-error 8487 :ERROR_DS_NOT_AUTHORITIVE_FOR_DST_NC "Destination of a cross-domain move is not authoritative for the destination naming context.")
(register-error 8488 :ERROR_DS_SRC_GUID_MISMATCH "Source and destination of a cross-domain move do not agree on the identity of the source object. Either source or destination does not have the latest version of the source object.")
(register-error 8489 :ERROR_DS_CANT_MOVE_DELETED_OBJECT "Object being moved across-domains is already known to be deleted by the destination server. The source server does not have the latest version of the source object.")
(register-error 8490 :ERROR_DS_PDC_OPERATION_IN_PROGRESS "Another operation which requires exclusive access to the PDC FSMO is already in progress.")
(register-error 8491 :ERROR_DS_CROSS_DOMAIN_CLEANUP_REQD "A cross-domain move operation failed such that two versions of the moved object exist - one each in the source and destination domains. The destination object needs to be removed to restore the system to a consistent state.")
(register-error 8492 :ERROR_DS_ILLEGAL_XDOM_MOVE_OPERATION "This object may not be moved across domain boundaries either because cross-domain moves for this class are disallowed, or the object has some special characteristics, e.g.: trust account or restricted RID, which prevent its move.")
(register-error 8493 :ERROR_DS_CANT_WITH_ACCT_GROUP_MEMBERSHPS "Can't move objects with memberships across domain boundaries as once moved, this would violate the membership conditions of the account group. Remove the object from any account group memberships and retry.")
(register-error 8494 :ERROR_DS_NC_MUST_HAVE_NC_PARENT "A naming context head must be the immediate child of another naming context head, not of an interior node.")
(register-error 8495 :ERROR_DS_CR_IMPOSSIBLE_TO_VALIDATE "The directory cannot validate the proposed naming context name because it does not hold a replica of the naming context above the proposed naming context. Please ensure that the domain naming master role is held by a server that is configured as a global catalog server, and that the server is up to date with its replication partners. (Applies only to Windows 2000 Domain Naming masters.)")
(register-error 8496 :ERROR_DS_DST_DOMAIN_NOT_NATIVE "Destination domain must be in native mode.")
(register-error 8497 :ERROR_DS_MISSING_INFRASTRUCTURE_CONTAINER "The operation cannot be performed because the server does not have an infrastructure container in the domain of interest.")
(register-error 8498 :ERROR_DS_CANT_MOVE_ACCOUNT_GROUP "Cross-domain move of non-empty account groups is not allowed.")
(register-error 8499 :ERROR_DS_CANT_MOVE_RESOURCE_GROUP "Cross-domain move of non-empty resource groups is not allowed.")
(register-error 8500 :ERROR_DS_INVALID_SEARCH_FLAG "The search flags for the attribute are invalid. The ANR bit is valid only on attributes of Unicode or Teletex strings.")
(register-error 8501 :ERROR_DS_NO_TREE_DELETE_ABOVE_NC "Tree deletions starting at an object which has an NC head as a descendant are not allowed.")
(register-error 8502 :ERROR_DS_COULDNT_LOCK_TREE_FOR_DELETE "The directory service failed to lock a tree in preparation for a tree deletion because the tree was in use.")
(register-error 8503 :ERROR_DS_COULDNT_IDENTIFY_OBJECTS_FOR_TREE_DELETE "The directory service failed to identify the list of objects to delete while attempting a tree deletion.")
(register-error 8504 :ERROR_DS_SAM_INIT_FAILURE "Security Accounts Manager initialization failed because of the following error: %1. Error Status: 0x%2. Please shutdown this system and reboot into Directory Services Restore Mode, check the event log for more detailed information.")
(register-error 8505 :ERROR_DS_SENSITIVE_GROUP_VIOLATION "Only an administrator can modify the membership list of an administrative group.")
(register-error 8506 :ERROR_DS_CANT_MOD_PRIMARYGROUPID "Cannot change the primary group ID of a domain controller account.")
(register-error 8507 :ERROR_DS_ILLEGAL_BASE_SCHEMA_MOD "An attempt is made to modify the base schema.")
(register-error 8508 :ERROR_DS_NONSAFE_SCHEMA_CHANGE "Adding a new mandatory attribute to an existing class, deleting a mandatory attribute from an existing class, or adding an optional attribute to the special class Top that is not a backlink attribute (directly or through inheritance, for example, by adding or deleting an auxiliary class) is not allowed.")
(register-error 8509 :ERROR_DS_SCHEMA_UPDATE_DISALLOWED "Schema update is not allowed on this DC because the DC is not the schema FSMO Role Owner.")
(register-error 8510 :ERROR_DS_CANT_CREATE_UNDER_SCHEMA "An object of this class cannot be created under the schema container. You can only create attribute-schema and class-schema objects under the schema container.")
(register-error 8511 :ERROR_DS_INSTALL_NO_SRC_SCH_VERSION "The replica/child install failed to get the objectVersion attribute on the schema container on the source DC. Either the attribute is missing on the schema container or the credentials supplied do not have permission to read it.")
(register-error 8512 :ERROR_DS_INSTALL_NO_SCH_VERSION_IN_INIFILE "The replica/child install failed to read the objectVersion attribute in the SCHEMA section of the file schema.ini in the system32 directory.")
(register-error 8513 :ERROR_DS_INVALID_GROUP_TYPE "The specified group type is invalid.")
(register-error 8514 :ERROR_DS_NO_NEST_GLOBALGROUP_IN_MIXEDDOMAIN "You cannot nest global groups in a mixed domain if the group is security-enabled.")
(register-error 8515 :ERROR_DS_NO_NEST_LOCALGROUP_IN_MIXEDDOMAIN "You cannot nest local groups in a mixed domain if the group is security-enabled.")
(register-error 8516 :ERROR_DS_GLOBAL_CANT_HAVE_LOCAL_MEMBER "A global group cannot have a local group as a member.")
(register-error 8517 :ERROR_DS_GLOBAL_CANT_HAVE_UNIVERSAL_MEMBER "A global group cannot have a universal group as a member.")
(register-error 8518 :ERROR_DS_UNIVERSAL_CANT_HAVE_LOCAL_MEMBER "A universal group cannot have a local group as a member.")
(register-error 8519 :ERROR_DS_GLOBAL_CANT_HAVE_CROSSDOMAIN_MEMBER "A global group cannot have a cross-domain member.")
(register-error 8520 :ERROR_DS_LOCAL_CANT_HAVE_CROSSDOMAIN_LOCAL_MEMBER "A local group cannot have another cross domain local group as a member.")
(register-error 8521 :ERROR_DS_HAVE_PRIMARY_MEMBERS "A group with primary members cannot change to a security-disabled group.")
(register-error 8522 :ERROR_DS_STRING_SD_CONVERSION_FAILED "The schema cache load failed to convert the string default SD on a class-schema object.")
(register-error 8523 :ERROR_DS_NAMING_MASTER_GC "Only DSAs configured to be Global Catalog servers should be allowed to hold the Domain Naming Master FSMO role. (Applies only to Windows 2000 servers.)")
(register-error 8524 :ERROR_DS_DNS_LOOKUP_FAILURE "The DSA operation is unable to proceed because of a DNS lookup failure.")
(register-error 8525 :ERROR_DS_COULDNT_UPDATE_SPNS "While processing a change to the DNS Host Name for an object, the Service Principal Name values could not be kept in sync.")
(register-error 8526 :ERROR_DS_CANT_RETRIEVE_SD "The Security Descriptor attribute could not be read.")
(register-error 8527 :ERROR_DS_KEY_NOT_UNIQUE "The object requested was not found, but an object with that key was found.")
(register-error 8528 :ERROR_DS_WRONG_LINKED_ATT_SYNTAX "The syntax of the linked attribute being added is incorrect. Forward links can only have syntax 2.5.5.1, 2.5.5.7, and 2.5.5.14, and backlinks can only have syntax 2.5.5.1.")
(register-error 8529 :ERROR_DS_SAM_NEED_BOOTKEY_PASSWORD "Security Account Manager needs to get the boot password.")
(register-error 8530 :ERROR_DS_SAM_NEED_BOOTKEY_FLOPPY "Security Account Manager needs to get the boot key from floppy disk.")
(register-error 8531 :ERROR_DS_CANT_START "Directory Service cannot start.")
(register-error 8532 :ERROR_DS_INIT_FAILURE "Directory Services could not start.")
(register-error 8533 :ERROR_DS_NO_PKT_PRIVACY_ON_CONNECTION "The connection between client and server requires packet privacy or better.")
(register-error 8534 :ERROR_DS_SOURCE_DOMAIN_IN_FOREST "The source domain may not be in the same forest as destination.")
(register-error 8535 :ERROR_DS_DESTINATION_DOMAIN_NOT_IN_FOREST "The destination domain must be in the forest.")
(register-error 8536 :ERROR_DS_DESTINATION_AUDITING_NOT_ENABLED "The operation requires that destination domain auditing be enabled.")
(register-error 8537 :ERROR_DS_CANT_FIND_DC_FOR_SRC_DOMAIN "The operation couldn't locate a DC for the source domain.")
(register-error 8538 :ERROR_DS_SRC_OBJ_NOT_GROUP_OR_USER "The source object must be a group or user.")
(register-error 8539 :ERROR_DS_SRC_SID_EXISTS_IN_FOREST "The source object's SID already exists in destination forest.")
(register-error 8540 :ERROR_DS_SRC_AND_DST_OBJECT_CLASS_MISMATCH "The source and destination object must be of the same type.")
(register-error 8541 :ERROR_SAM_INIT_FAILURE "Security Accounts Manager initialization failed because of the following error: %1. Error Status: 0x%2. Click OK to shut down the system and reboot into Safe Mode. Check the event log for detailed information.")
(register-error 8542 :ERROR_DS_DRA_SCHEMA_INFO_SHIP "Schema information could not be included in the replication request.")
(register-error 8543 :ERROR_DS_DRA_SCHEMA_CONFLICT "The replication operation could not be completed due to a schema incompatibility.")
(register-error 8544 :ERROR_DS_DRA_EARLIER_SCHEMA_CONFLICT "The replication operation could not be completed due to a previous schema incompatibility.")
(register-error 8545 :ERROR_DS_DRA_OBJ_NC_MISMATCH "The replication update could not be applied because either the source or the destination has not yet received information regarding a recent cross-domain move operation.")
(register-error 8546 :ERROR_DS_NC_STILL_HAS_DSAS "The requested domain could not be deleted because there exist domain controllers that still host this domain.")
(register-error 8547 :ERROR_DS_GC_REQUIRED "The requested operation can be performed only on a global catalog server.")
(register-error 8548 :ERROR_DS_LOCAL_MEMBER_OF_LOCAL_ONLY "A local group can only be a member of other local groups in the same domain.")
(register-error 8549 :ERROR_DS_NO_FPO_IN_UNIVERSAL_GROUPS "Foreign security principals cannot be members of universal groups.")
(register-error 8550 :ERROR_DS_CANT_ADD_TO_GC "The attribute is not allowed to be replicated to the GC because of security reasons.")
(register-error 8551 :ERROR_DS_NO_CHECKPOINT_WITH_PDC "The checkpoint with the PDC could not be taken because there too many modifications being processed currently.")
(register-error 8552 :ERROR_DS_SOURCE_AUDITING_NOT_ENABLED "The operation requires that source domain auditing be enabled.")
(register-error 8553 :ERROR_DS_CANT_CREATE_IN_NONDOMAIN_NC "Security principal objects can only be created inside domain naming contexts.")
(register-error 8554 :ERROR_DS_INVALID_NAME_FOR_SPN "A Service Principal Name (SPN) could not be constructed because the provided hostname is not in the necessary format.")
(register-error 8555 :ERROR_DS_FILTER_USES_CONTRUCTED_ATTRS "A Filter was passed that uses constructed attributes.")
(register-error 8556 :ERROR_DS_UNICODEPWD_NOT_IN_QUOTES "The unicodePwd attribute value must be enclosed in double quotes.")
(register-error 8557 :ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED "Your computer could not be joined to the domain. You have exceeded the maximum number of computer accounts you are allowed to create in this domain. Contact your system administrator to have this limit reset or increased.")
(register-error 8558 :ERROR_DS_MUST_BE_RUN_ON_DST_DC "For security reasons, the operation must be run on the destination DC.")
(register-error 8559 :ERROR_DS_SRC_DC_MUST_BE_SP4_OR_GREATER "For security reasons, the source DC must be NT4SP4 or greater.")
(register-error 8560 :ERROR_DS_CANT_TREE_DELETE_CRITICAL_OBJ "Critical Directory Service System objects cannot be deleted during tree delete operations. The tree delete may have been partially performed.")
(register-error 8561 :ERROR_DS_INIT_FAILURE_CONSOLE "Directory Services could not start because of the following error: %1. Error Status: 0x%2. Please click OK to shutdown the system. You can use the recovery console to diagnose the system further.")
(register-error 8562 :ERROR_DS_SAM_INIT_FAILURE_CONSOLE "Security Accounts Manager initialization failed because of the following error: %1. Error Status: 0x%2. Please click OK to shutdown the system. You can use the recovery console to diagnose the system further.")
(register-error 8563 :ERROR_DS_FOREST_VERSION_TOO_HIGH "The version of the operating system is incompatible with the current AD DS forest functional level or AD LDS Configuration Set functional level. You must upgrade to a new version of the operating system before this server can become an AD DS Domain Controller or add an AD LDS Instance in this AD DS Forest or AD LDS Configuration Set.")
(register-error 8564 :ERROR_DS_DOMAIN_VERSION_TOO_HIGH "The version of the operating system installed is incompatible with the current domain functional level. You must upgrade to a new version of the operating system before this server can become a domain controller in this domain.")
(register-error 8565 :ERROR_DS_FOREST_VERSION_TOO_LOW "The version of the operating system installed on this server no longer supports the current AD DS Forest functional level or AD LDS Configuration Set functional level. You must raise the AD DS Forest functional level or AD LDS Configuration Set functional level before this server can become an AD DS Domain Controller or an AD LDS Instance in this Forest or Configuration Set.")
(register-error 8566 :ERROR_DS_DOMAIN_VERSION_TOO_LOW "The version of the operating system installed on this server no longer supports the current domain functional level. You must raise the domain functional level before this server can become a domain controller in this domain.")
(register-error 8567 :ERROR_DS_INCOMPATIBLE_VERSION "The version of the operating system installed on this server is incompatible with the functional level of the domain or forest.")
(register-error 8568 :ERROR_DS_LOW_DSA_VERSION "The functional level of the domain (or forest) cannot be raised to the requested value, because there exist one or more domain controllers in the domain (or forest) that are at a lower incompatible functional level.")
(register-error 8569 :ERROR_DS_NO_BEHAVIOR_VERSION_IN_MIXEDDOMAIN "The forest functional level cannot be raised to the requested value since one or more domains are still in mixed domain mode. All domains in the forest must be in native mode, for you to raise the forest functional level.")
(register-error 8570 :ERROR_DS_NOT_SUPPORTED_SORT_ORDER "The sort order requested is not supported.")
(register-error 8571 :ERROR_DS_NAME_NOT_UNIQUE "The requested name already exists as a unique identifier.")
(register-error 8572 :ERROR_DS_MACHINE_ACCOUNT_CREATED_PRENT4 "The machine account was created pre-NT4. The account needs to be recreated.")
(register-error 8573 :ERROR_DS_OUT_OF_VERSION_STORE "The database is out of version store.")
(register-error 8574 :ERROR_DS_INCOMPATIBLE_CONTROLS_USED "Unable to continue operation because multiple conflicting controls were used.")
(register-error 8575 :ERROR_DS_NO_REF_DOMAIN "Unable to find a valid security descriptor reference domain for this partition.")
(register-error 8576 :ERROR_DS_RESERVED_LINK_ID "Schema update failed: The link identifier is reserved.")
(register-error 8577 :ERROR_DS_LINK_ID_NOT_AVAILABLE "Schema update failed: There are no link identifiers available.")
(register-error 8578 :ERROR_DS_AG_CANT_HAVE_UNIVERSAL_MEMBER "An account group cannot have a universal group as a member.")
(register-error 8579 :ERROR_DS_MODIFYDN_DISALLOWED_BY_INSTANCE_TYPE "Rename or move operations on naming context heads or read-only objects are not allowed.")
(register-error 8580 :ERROR_DS_NO_OBJECT_MOVE_IN_SCHEMA_NC "Move operations on objects in the schema naming context are not allowed.")
(register-error 8581 :ERROR_DS_MODIFYDN_DISALLOWED_BY_FLAG "A system flag has been set on the object and does not allow the object to be moved or renamed.")
(register-error 8582 :ERROR_DS_MODIFYDN_WRONG_GRANDPARENT "This object is not allowed to change its grandparent container. Moves are not forbidden on this object, but are restricted to sibling containers.")
(register-error 8583 :ERROR_DS_NAME_ERROR_TRUST_REFERRAL "Unable to resolve completely, a referral to another forest is generated.")
(register-error 8584 :ERROR_NOT_SUPPORTED_ON_STANDARD_SERVER "The requested action is not supported on standard server.")
(register-error 8585 :ERROR_DS_CANT_ACCESS_REMOTE_PART_OF_AD "Could not access a partition of the directory service located on a remote server. Make sure at least one server is running for the partition in question.")
(register-error 8586 :ERROR_DS_CR_IMPOSSIBLE_TO_VALIDATE_V2 "The directory cannot validate the proposed naming context (or partition) name because it does not hold a replica nor can it contact a replica of the naming context above the proposed naming context. Please ensure that the parent naming context is properly registered in DNS, and at least one replica of this naming context is reachable by the Domain Naming master.")
(register-error 8587 :ERROR_DS_THREAD_LIMIT_EXCEEDED "The thread limit for this request was exceeded.")
(register-error 8588 :ERROR_DS_NOT_CLOSEST "The Global catalog server is not in the closest site.")
(register-error 8589 :ERROR_DS_CANT_DERIVE_SPN_WITHOUT_SERVER_REF "The DS cannot derive a service principal name (SPN) with which to mutually authenticate the target server because the corresponding server object in the local DS database has no serverReference attribute.")
(register-error 8590 :ERROR_DS_SINGLE_USER_MODE_FAILED "The Directory Service failed to enter single user mode.")
(register-error 8591 :ERROR_DS_NTDSCRIPT_SYNTAX_ERROR "The Directory Service cannot parse the script because of a syntax error.")
(register-error 8592 :ERROR_DS_NTDSCRIPT_PROCESS_ERROR "The Directory Service cannot process the script because of an error.")
(register-error 8593 :ERROR_DS_DIFFERENT_REPL_EPOCHS "The directory service cannot perform the requested operation because the servers involved are of different replication epochs (which is usually related to a domain rename that is in progress).")
(register-error 8594 :ERROR_DS_DRS_EXTENSIONS_CHANGED "The directory service binding must be renegotiated due to a change in the server extensions information.")
(register-error 8595 :ERROR_DS_REPLICA_SET_CHANGE_NOT_ALLOWED_ON_DISABLED_CR "Operation not allowed on a disabled cross ref.")
(register-error 8596 :ERROR_DS_NO_MSDS_INTID "Schema update failed: No values for msDS-IntId are available.")
(register-error 8597 :ERROR_DS_DUP_MSDS_INTID "Schema update failed: Duplicate msDS-INtId. Retry the operation.")
(register-error 8598 :ERROR_DS_EXISTS_IN_RDNATTID "Schema deletion failed: attribute is used in rDNAttID.")
(register-error 8599 :ERROR_DS_AUTHORIZATION_FAILED "The directory service failed to authorize the request.")
(register-error 8600 :ERROR_DS_INVALID_SCRIPT "The Directory Service cannot process the script because it is invalid.")
(register-error 8601 :ERROR_DS_REMOTE_CROSSREF_OP_FAILED "The remote create cross reference operation failed on the Domain Naming Master FSMO. The operation's error is in the extended data.")
(register-error 8602 :ERROR_DS_CROSS_REF_BUSY "A cross reference is in use locally with the same name.")
(register-error 8603 :ERROR_DS_CANT_DERIVE_SPN_FOR_DELETED_DOMAIN "The DS cannot derive a service principal name (SPN) with which to mutually authenticate the target server because the server's domain has been deleted from the forest.")
(register-error 8604 :ERROR_DS_CANT_DEMOTE_WITH_WRITEABLE_NC "Writeable NCs prevent this DC from demoting.")
(register-error 8605 :ERROR_DS_DUPLICATE_ID_FOUND "The requested object has a non-unique identifier and cannot be retrieved.")
(register-error 8606 :ERROR_DS_INSUFFICIENT_ATTR_TO_CREATE_OBJECT "Insufficient attributes were given to create an object. This object may not exist because it may have been deleted and already garbage collected.")
(register-error 8607 :ERROR_DS_GROUP_CONVERSION_ERROR "The group cannot be converted due to attribute restrictions on the requested group type.")
(register-error 8608 :ERROR_DS_CANT_MOVE_APP_BASIC_GROUP "Cross-domain move of non-empty basic application groups is not allowed.")
(register-error 8609 :ERROR_DS_CANT_MOVE_APP_QUERY_GROUP "Cross-domain move of non-empty query based application groups is not allowed.")
(register-error 8610 :ERROR_DS_ROLE_NOT_VERIFIED "The FSMO role ownership could not be verified because its directory partition has not replicated successfully with at least one replication partner.")
(register-error 8611 :ERROR_DS_WKO_CONTAINER_CANNOT_BE_SPECIAL "The target container for a redirection of a well known object container cannot already be a special container.")
(register-error 8612 :ERROR_DS_DOMAIN_RENAME_IN_PROGRESS "The Directory Service cannot perform the requested operation because a domain rename operation is in progress.")
(register-error 8613 :ERROR_DS_EXISTING_AD_CHILD_NC "The directory service detected a child partition below the requested partition name. The partition hierarchy must be created in a top down method.")
(register-error 8614 :ERROR_DS_REPL_LIFETIME_EXCEEDED "The directory service cannot replicate with this server because the time since the last replication with this server has exceeded the tombstone lifetime.")
(register-error 8615 :ERROR_DS_DISALLOWED_IN_SYSTEM_CONTAINER "The requested operation is not allowed on an object under the system container.")
(register-error 8616 :ERROR_DS_LDAP_SEND_QUEUE_FULL "The LDAP servers network send queue has filled up because the client is not processing the results of its requests fast enough. No more requests will be processed until the client catches up. If the client does not catch up then it will be disconnected.")
(register-error 8617 :ERROR_DS_DRA_OUT_SCHEDULE_WINDOW "The scheduled replication did not take place because the system was too busy to execute the request within the schedule window. The replication queue is overloaded. Consider reducing the number of partners or decreasing the scheduled replication frequency.")
(register-error 8618 :ERROR_DS_POLICY_NOT_KNOWN "At this time, it cannot be determined if the branch replication policy is available on the hub domain controller. Please retry at a later time to account for replication latencies.")
(register-error 8619 :ERROR_NO_SITE_SETTINGS_OBJECT "The site settings object for the specified site does not exist.")
(register-error 8620 :ERROR_NO_SECRETS "The local account store does not contain secret material for the specified account.")
(register-error 8621 :ERROR_NO_WRITABLE_DC_FOUND "Could not find a writable domain controller in the domain.")
(register-error 8622 :ERROR_DS_NO_SERVER_OBJECT "The server object for the domain controller does not exist.")
(register-error 8623 :ERROR_DS_NO_NTDSA_OBJECT "The NTDS Settings object for the domain controller does not exist.")
(register-error 8624 :ERROR_DS_NON_ASQ_SEARCH "The requested search operation is not supported for ASQ searches.")
(register-error 8625 :ERROR_DS_AUDIT_FAILURE "A required audit event could not be generated for the operation.")
(register-error 8626 :ERROR_DS_INVALID_SEARCH_FLAG_SUBTREE "The search flags for the attribute are invalid. The subtree index bit is valid only on single valued attributes.")
(register-error 8627 :ERROR_DS_INVALID_SEARCH_FLAG_TUPLE "The search flags for the attribute are invalid. The tuple index bit is valid only on attributes of Unicode strings.")
(register-error 8628 :ERROR_DS_HIERARCHY_TABLE_TOO_DEEP "The address books are nested too deeply. Failed to build the hierarchy table.")
(register-error 8629 :ERROR_DS_DRA_CORRUPT_UTD_VECTOR "The specified up-to-date-ness vector is corrupt.")
(register-error 8630 :ERROR_DS_DRA_SECRETS_DENIED "The request to replicate secrets is denied.")
(register-error 8631 :ERROR_DS_RESERVED_MAPI_ID "Schema update failed: The MAPI identifier is reserved.")
(register-error 8632 :ERROR_DS_MAPI_ID_NOT_AVAILABLE "Schema update failed: There are no MAPI identifiers available.")
(register-error 8633 :ERROR_DS_DRA_MISSING_KRBTGT_SECRET "The replication operation failed because the required attributes of the local krbtgt object are missing.")
(register-error 8634 :ERROR_DS_DOMAIN_NAME_EXISTS_IN_FOREST "The domain name of the trusted domain already exists in the forest.")
(register-error 8635 :ERROR_DS_FLAT_NAME_EXISTS_IN_FOREST "The flat name of the trusted domain already exists in the forest.")
(register-error 8636 :ERROR_INVALID_USER_PRINCIPAL_NAME "The User Principal Name (UPN) is invalid.")
(register-error 8637 :ERROR_DS_OID_MAPPED_GROUP_CANT_HAVE_MEMBERS "OID mapped groups cannot have members.")
(register-error 8638 :ERROR_DS_OID_NOT_FOUND "The specified OID cannot be found.")
(register-error 8639 :ERROR_DS_DRA_RECYCLED_TARGET "The replication operation failed because the target object referred by a link value is recycled.")
(register-error 8640 :ERROR_DS_DISALLOWED_NC_REDIRECT "The redirect operation failed because the target object is in a NC different from the domain NC of the current domain controller.")
(register-error 8641 :ERROR_DS_HIGH_ADLDS_FFL "The functional level of the AD LDS configuration set cannot be lowered to the requested value.")
(register-error 8642 :ERROR_DS_HIGH_DSA_VERSION "The functional level of the domain (or forest) cannot be lowered to the requested value.")
(register-error 8643 :ERROR_DS_LOW_ADLDS_FFL "The functional level of the AD LDS configuration set cannot be raised to the requested value, because there exist one or more ADLDS instances that are at a lower incompatible functional level.")
(register-error 8644 :ERROR_DOMAIN_SID_SAME_AS_LOCAL_WORKSTATION "The domain join cannot be completed because the SID of the domain you attempted to join was identical to the SID of this machine. This is a symptom of an improperly cloned operating system install. You should run sysprep on this machine in order to generate a new machine SID. Please see https://go.microsoft.com/fwlink/p/?linkid=168895 for more information.")
(register-error 8645 :ERROR_DS_UNDELETE_SAM_VALIDATION_FAILED "The undelete operation failed because the Sam Account Name or Additional Sam Account Name of the object being undeleted conflicts with an existing live object.")
(register-error 8646 :ERROR_INCORRECT_ACCOUNT_TYPE "The system is not authoritative for the specified account and therefore cannot complete the operation. Please retry the operation using the provider associated with this account. If this is an online provider please use the provider's online site.")

