;;;; src/extended.lisp
;;;
;;; Contains miscellaneous system error codes for various services like
;;; EFS, WINS, WMI, RDP, FRS, and more.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; Encrypting File System (EFS) Errors (6000-6022)
;;;--------------------------------------------------------------------------

(register-error 6000 :ERROR_ENCRYPTION_FAILED "The specified file could not be encrypted.")
(register-error 6001 :ERROR_DECRYPTION_FAILED "The specified file could not be decrypted.")
(register-error 6002 :ERROR_FILE_ENCRYPTED "The specified file is encrypted and the user does not have the ability to decrypt it.")
(register-error 6003 :ERROR_NO_RECOVERY_POLICY "There is no valid encryption recovery policy configured for this system.")
(register-error 6004 :ERROR_NO_EFS "The required encryption driver is not loaded for this system.")
(register-error 6005 :ERROR_WRONG_EFS "The file was encrypted with a different encryption driver than is currently loaded.")
(register-error 6006 :ERROR_NO_USER_KEYS "There are no EFS keys defined for the user.")
(register-error 6007 :ERROR_FILE_NOT_ENCRYPTED "The specified file is not encrypted.")
(register-error 6008 :ERROR_NOT_EXPORT_FORMAT "The specified file is not in the defined EFS export format.")
(register-error 6009 :ERROR_FILE_READ_ONLY "The specified file is read only.")
(register-error 6010 :ERROR_DIR_EFS_DISALLOWED "The directory has been disabled for encryption.")
(register-error 6011 :ERROR_EFS_SERVER_NOT_TRUSTED "The server is not trusted for remote encryption operation.")
(register-error 6012 :ERROR_BAD_RECOVERY_POLICY "Recovery policy configured for this system contains invalid recovery certificate.")
(register-error 6013 :ERROR_EFS_ALG_BLOB_TOO_BIG "The encryption algorithm used on the source file needs a bigger key buffer than the one on the destination file.")
(register-error 6014 :ERROR_VOLUME_NOT_SUPPORT_EFS "The disk partition does not support file encryption.")
(register-error 6015 :ERROR_EFS_DISABLED "This machine is disabled for file encryption.")
(register-error 6016 :ERROR_EFS_VERSION_NOT_SUPPORT "A newer system is required to decrypt this encrypted file.")
(register-error 6017 :ERROR_CS_ENCRYPTION_INVALID_SERVER_RESPONSE "The remote server sent an invalid response for a file being opened with Client Side Encryption.")
(register-error 6018 :ERROR_CS_ENCRYPTION_UNSUPPORTED_SERVER "Client Side Encryption is not supported by the remote server even though it claims to support it.")
(register-error 6019 :ERROR_CS_ENCRYPTION_EXISTING_ENCRYPTED_FILE "File is encrypted and should be opened in Client Side Encryption mode.")
(register-error 6020 :ERROR_CS_ENCRYPTION_NEW_ENCRYPTED_FILE "A new encrypted file is being created and a $EFS needs to be provided.")
(register-error 6021 :ERROR_CS_ENCRYPTION_FILE_NOT_CSE "The SMB client requested a CSE FSCTL on a non-CSE file.")
(register-error 6022 :ERROR_ENCRYPTION_POLICY_DENIES_OPERATION "The requested operation was blocked by policy. For more information, contact your system administrator.")

;;;--------------------------------------------------------------------------
;;; Browser Service Errors (6118)
;;;--------------------------------------------------------------------------

(register-error 6118 :ERROR_NO_BROWSER_SERVERS_FOUND "The list of servers for this workgroup is not currently available.")

;;;--------------------------------------------------------------------------
;;; Task Scheduler Errors (6200)
;;;--------------------------------------------------------------------------

(register-error 6200 :SCHED_E_SERVICE_NOT_LOCALSYSTEM "The Task Scheduler service must be configured to run in the System account to function properly. Individual tasks may be configured to run in other accounts.")

;;;--------------------------------------------------------------------------
;;; Remote Desktop and Terminal Services Errors (7001-7070)
;;;--------------------------------------------------------------------------

(register-error 7001 :ERROR_CTX_WINSTATION_NAME_INVALID "The specified session name is invalid.")
(register-error 7002 :ERROR_CTX_INVALID_PD "The specified protocol driver is invalid.")
(register-error 7003 :ERROR_CTX_PD_NOT_FOUND "The specified protocol driver was not found in the system path.")
(register-error 7004 :ERROR_CTX_WD_NOT_FOUND "The specified terminal connection driver was not found in the system path.")
(register-error 7005 :ERROR_CTX_CANNOT_MAKE_EVENTLOG_ENTRY "A registry key for event logging could not be created for this session.")
(register-error 7006 :ERROR_CTX_SERVICE_NAME_COLLISION "A service with the same name already exists on the system.")
(register-error 7007 :ERROR_CTX_CLOSE_PENDING "A close operation is pending on the session.")
(register-error 7008 :ERROR_CTX_NO_OUTBUF "There are no free output buffers available.")
(register-error 7009 :ERROR_CTX_MODEM_INF_NOT_FOUND "The MODEM.INF file was not found.")
(register-error 7010 :ERROR_CTX_INVALID_MODEMNAME "The modem name was not found in MODEM.INF.")
(register-error 7011 :ERROR_CTX_MODEM_RESPONSE_ERROR "The modem did not accept the command sent to it. Verify that the configured modem name matches the attached modem.")
(register-error 7012 :ERROR_CTX_MODEM_RESPONSE_TIMEOUT "The modem did not respond to the command sent to it. Verify that the modem is properly cabled and powered on.")
(register-error 7013 :ERROR_CTX_MODEM_RESPONSE_NO_CARRIER "Carrier detect has failed or carrier has been dropped due to disconnect.")
(register-error 7014 :ERROR_CTX_MODEM_RESPONSE_NO_DIALTONE "Dial tone not detected within the required time. Verify that the phone cable is properly attached and functional.")
(register-error 7015 :ERROR_CTX_MODEM_RESPONSE_BUSY "Busy signal detected at remote site on callback.")
(register-error 7016 :ERROR_CTX_MODEM_RESPONSE_VOICE "Voice detected at remote site on callback.")
(register-error 7017 :ERROR_CTX_TD_ERROR "Transport driver error.")
(register-error 7022 :ERROR_CTX_WINSTATION_NOT_FOUND "The specified session cannot be found.")
(register-error 7023 :ERROR_CTX_WINSTATION_ALREADY_EXISTS "The specified session name is already in use.")
(register-error 7024 :ERROR_CTX_WINSTATION_BUSY "The task you are trying to do can't be completed because Remote Desktop Services is currently busy. Please try again in a few minutes. Other users should still be able to log on.")
(register-error 7025 :ERROR_CTX_BAD_VIDEO_MODE "An attempt has been made to connect to a session whose video mode is not supported by the current client.")
(register-error 7035 :ERROR_CTX_GRAPHICS_INVALID "The application attempted to enable DOS graphics mode. DOS graphics mode is not supported.")
(register-error 7037 :ERROR_CTX_LOGON_DISABLED "Your interactive logon privilege has been disabled. Please contact your administrator.")
(register-error 7038 :ERROR_CTX_NOT_CONSOLE "The requested operation can be performed only on the system console. This is most often the result of a driver or system DLL requiring direct console access.")
(register-error 7040 :ERROR_CTX_CLIENT_QUERY_TIMEOUT "The client failed to respond to the server connect message.")
(register-error 7041 :ERROR_CTX_CONSOLE_DISCONNECT "Disconnecting the console session is not supported.")
(register-error 7042 :ERROR_CTX_CONSOLE_CONNECT "Reconnecting a disconnected session to the console is not supported.")
(register-error 7044 :ERROR_CTX_SHADOW_DENIED "The request to control another session remotely was denied.")
(register-error 7045 :ERROR_CTX_WINSTATION_ACCESS_DENIED "The requested session access is denied.")
(register-error 7049 :ERROR_CTX_INVALID_WD "The specified terminal connection driver is invalid.")
(register-error 7050 :ERROR_CTX_SHADOW_INVALID "The requested session cannot be controlled remotely. This may be because the session is disconnected or does not currently have a user logged on.")
(register-error 7051 :ERROR_CTX_SHADOW_DISABLED "The requested session is not configured to allow remote control.")
(register-error 7052 :ERROR_CTX_CLIENT_LICENSE_IN_USE "Your request to connect to this Terminal Server has been rejected. Your Terminal Server client license number is currently being used by another user. Please call your system administrator to obtain a unique license number.")
(register-error 7053 :ERROR_CTX_CLIENT_LICENSE_NOT_SET "Your request to connect to this Terminal Server has been rejected. Your Terminal Server client license number has not been entered for this copy of the Terminal Server client. Please contact your system administrator.")
(register-error 7054 :ERROR_CTX_LICENSE_NOT_AVAILABLE "The number of connections to this computer is limited and all connections are in use right now. Try connecting later or contact your system administrator.")
(register-error 7055 :ERROR_CTX_LICENSE_CLIENT_INVALID "The client you are using is not licensed to use this system. Your logon request is denied.")
(register-error 7056 :ERROR_CTX_LICENSE_EXPIRED "The system license has expired. Your logon request is denied.")
(register-error 7057 :ERROR_CTX_SHADOW_NOT_RUNNING "Remote control could not be terminated because the specified session is not currently being remotely controlled.")
(register-error 7058 :ERROR_CTX_SHADOW_ENDED_BY_MODE_CHANGE "The remote control of the console was terminated because the display mode was changed. Changing the display mode in a remote control session is not supported.")
(register-error 7059 :ERROR_ACTIVATION_COUNT_EXCEEDED "Activation has already been reset the maximum number of times for this installation. Your activation timer will not be cleared.")
(register-error 7060 :ERROR_CTX_WINSTATIONS_DISABLED "Remote logins are currently disabled.")
(register-error 7061 :ERROR_CTX_ENCRYPTION_LEVEL_REQUIRED "You do not have the proper encryption level to access this Session.")
(register-error 7062 :ERROR_CTX_SESSION_IN_USE "The user %s\\%s is currently logged on to this computer. Only the current user or an administrator can log on to this computer.")
(register-error 7063 :ERROR_CTX_NO_FORCE_LOGOFF "The user %s\\%s is already logged on to the console of this computer. You do not have permission to log in at this time. To resolve this issue, contact %s\\%s and have them log off.")
(register-error 7064 :ERROR_CTX_ACCOUNT_RESTRICTION "Unable to log you on because of an account restriction.")
(register-error 7065 :ERROR_RDP_PROTOCOL_ERROR "The RDP protocol component %2 detected an error in the protocol stream and has disconnected the client.")
(register-error 7066 :ERROR_CTX_CDM_CONNECT "The Client Drive Mapping Service Has Connected on Terminal Connection.")
(register-error 7067 :ERROR_CTX_CDM_DISCONNECT "The Client Drive Mapping Service Has Disconnected on Terminal Connection.")
(register-error 7068 :ERROR_CTX_SECURITY_LAYER_ERROR "The Terminal Server security layer detected an error in the protocol stream and has disconnected the client.")
(register-error 7069 :ERROR_TS_INCOMPATIBLE_SESSIONS "The target session is incompatible with the current session.")
(register-error 7070 :ERROR_TS_VIDEO_SUBSYSTEM_ERROR "Windows can't connect to your session because a problem occurred in the Windows video subsystem. Try connecting again later, or contact the server administrator for assistance.")

;;;--------------------------------------------------------------------------
;;; File Replication Service (FRS) Errors (8001-8017)
;;;--------------------------------------------------------------------------

(register-error 8001 :FRS_ERR_INVALID_API_SEQUENCE "The file replication service API was called incorrectly.")
(register-error 8002 :FRS_ERR_STARTING_SERVICE "The file replication service cannot be started.")
(register-error 8003 :FRS_ERR_STOPPING_SERVICE "The file replication service cannot be stopped.")
(register-error 8004 :FRS_ERR_INTERNAL_API "The file replication service API terminated the request. The event log may have more information.")
(register-error 8005 :FRS_ERR_INTERNAL "The file replication service terminated the request. The event log may have more information.")
(register-error 8006 :FRS_ERR_SERVICE_COMM "The file replication service cannot be contacted. The event log may have more information.")
(register-error 8007 :FRS_ERR_INSUFFICIENT_PRIV "The file replication service cannot satisfy the request because the user has insufficient privileges. The event log may have more information.")
(register-error 8008 :FRS_ERR_AUTHENTICATION "The file replication service cannot satisfy the request because authenticated RPC is not available. The event log may have more information.")
(register-error 8009 :FRS_ERR_PARENT_INSUFFICIENT_PRIV "The file replication service cannot satisfy the request because the user has insufficient privileges on the domain controller. The event log may have more information.")
(register-error 8010 :FRS_ERR_PARENT_AUTHENTICATION "The file replication service cannot satisfy the request because authenticated RPC is not available on the domain controller. The event log may have more information.")
(register-error 8011 :FRS_ERR_CHILD_TO_PARENT_COMM "The file replication service cannot communicate with the file replication service on the domain controller. The event log may have more information.")
(register-error 8012 :FRS_ERR_PARENT_TO_CHILD_COMM "The file replication service on the domain controller cannot communicate with the file replication service on this computer. The event log may have more information.")
(register-error 8013 :FRS_ERR_SYSVOL_POPULATE "The file replication service cannot populate the system volume because of an internal error. The event log may have more information.")
(register-error 8014 :FRS_ERR_SYSVOL_POPULATE_TIMEOUT "The file replication service cannot populate the system volume because of an internal timeout. The event log may have more information.")
(register-error 8015 :FRS_ERR_SYSVOL_IS_BUSY "The file replication service cannot process the request. The system volume is busy with a previous request.")
(register-error 8016 :FRS_ERR_SYSVOL_DEMOTE "The file replication service cannot stop replicating the system volume because of an internal error. The event log may have more information.")
(register-error 8017 :FRS_ERR_INVALID_SERVICE_PARAMETER "The file replication service detected an invalid parameter.")

;;;--------------------------------------------------------------------------
;;; WINS, WMI, etc.
;;;--------------------------------------------------------------------------

(register-error 4000 :ERROR_WINS_INTERNAL "WINS encountered an error while processing the command.")
(register-error 4001 :ERROR_CAN_NOT_DEL_LOCAL_WINS "The local WINS cannot be deleted.")
(register-error 4002 :ERROR_STATIC_INIT "The importation from the file failed.")
(register-error 4003 :ERROR_INC_BACKUP "The backup failed. Was a full backup done before?")
(register-error 4004 :ERROR_FULL_BACKUP "The backup failed. Check the directory to which you are backing the database.")
(register-error 4005 :ERROR_REC_NON_EXISTENT "The name does not exist in the WINS database.")
(register-error 4006 :ERROR_RPL_NOT_ALLOWED "Replication with a nonconfigured partner is not allowed.")
(register-error 4050 :PEERDIST_ERROR_CONTENTINFO_VERSION_UNSUPPORTED "The version of the supplied content information is not supported.")
(register-error 4051 :PEERDIST_ERROR_CANNOT_PARSE_CONTENTINFO "The supplied content information is malformed.")
(register-error 4052 :PEERDIST_ERROR_MISSING_DATA "The requested data cannot be found in local or peer caches.")
(register-error 4053 :PEERDIST_ERROR_NO_MORE "No more data is available or required.")
(register-error 4054 :PEERDIST_ERROR_NOT_INITIALIZED "The supplied object has not been initialized.")
(register-error 4055 :PEERDIST_ERROR_ALREADY_INITIALIZED "The supplied object has already been initialized.")
(register-error 4056 :PEERDIST_ERROR_SHUTDOWN_IN_PROGRESS "A shutdown operation is already in progress.")
(register-error 4057 :PEERDIST_ERROR_INVALIDATED "The supplied object has already been invalidated.")
(register-error 4058 :PEERDIST_ERROR_ALREADY_EXISTS "An element already exists and was not replaced.")
(register-error 4059 :PEERDIST_ERROR_OPERATION_NOTFOUND "Cannot cancel the requested operation as it has already been completed.")
(register-error 4060 :PEERDIST_ERROR_ALREADY_COMPLETED "Can not perform the requested operation because it has already been carried out.")
(register-error 4061 :PEERDIST_ERROR_OUT_OF_BOUNDS "An operation accessed data beyond the bounds of valid data.")
(register-error 4062 :PEERDIST_ERROR_VERSION_UNSUPPORTED "The requested version is not supported.")
(register-error 4063 :PEERDIST_ERROR_INVALID_CONFIGURATION "A configuration value is invalid.")
(register-error 4064 :PEERDIST_ERROR_NOT_LICENSED "The SKU is not licensed.")
(register-error 4065 :PEERDIST_ERROR_SERVICE_UNAVAILABLE "PeerDist Service is still initializing and will be available shortly.")
(register-error 4066 :PEERDIST_ERROR_TRUST_FAILURE "Communication with one or more computers will be temporarily blocked due to recent errors.")
(register-error 4100 :ERROR_DHCP_ADDRESS_CONFLICT "The DHCP client has obtained an IP address that is already in use on the network. The local interface will be disabled until the DHCP client can obtain a new address.")
(register-error 4200 :ERROR_WMI_GUID_NOT_FOUND "The GUID passed was not recognized as valid by a WMI data provider.")
(register-error 4201 :ERROR_WMI_INSTANCE_NOT_FOUND "The instance name passed was not recognized as valid by a WMI data provider.")
(register-error 4202 :ERROR_WMI_ITEMID_NOT_FOUND "The data item ID passed was not recognized as valid by a WMI data provider.")
(register-error 4203 :ERROR_WMI_TRY_AGAIN "The WMI request could not be completed and should be retried.")
(register-error 4204 :ERROR_WMI_DP_NOT_FOUND "The WMI data provider could not be located.")
(register-error 4205 :ERROR_WMI_UNRESOLVED_INSTANCE_REF "The WMI data provider references an instance set that has not been registered.")
(register-error 4206 :ERROR_WMI_ALREADY_ENABLED "The WMI data block or event notification has already been enabled.")
(register-error 4207 :ERROR_WMI_GUID_DISCONNECTED "The WMI data block is no longer available.")
(register-error 4208 :ERROR_WMI_SERVER_UNAVAILABLE "The WMI data service is not available.")
(register-error 4209 :ERROR_WMI_DP_FAILED "The WMI data provider failed to carry out the request.")
(register-error 4210 :ERROR_WMI_INVALID_MOF "The WMI MOF information is not valid.")
(register-error 4211 :ERROR_WMI_INVALID_REGINFO "The WMI registration information is not valid.")
(register-error 4212 :ERROR_WMI_ALREADY_DISABLED "The WMI data block or event notification has already been disabled.")
(register-error 4213 :ERROR_WMI_READ_ONLY "The WMI data item or data block is read only.")
(register-error 4214 :ERROR_WMI_SET_FAILURE "The WMI data item or data block could not be changed.")
(register-error 4250 :ERROR_NOT_APPCONTAINER "This operation is only valid in the context of an app container.")
(register-error 4251 :ERROR_APPCONTAINER_REQUIRED "This application can only run in the context of an app container.")
(register-error 4252 :ERROR_NOT_SUPPORTED_IN_APPCONTAINER "This functionality is not supported in the context of an app container.")
(register-error 4253 :ERROR_INVALID_PACKAGE_SID_LENGTH "The length of the SID supplied is not a valid length for app container SIDs.")
(register-error 4300 :ERROR_INVALID_MEDIA "The media identifier does not represent a valid medium.")
(register-error 4301 :ERROR_INVALID_LIBRARY "The library identifier does not represent a valid library.")
(register-error 4302 :ERROR_INVALID_MEDIA_POOL "The media pool identifier does not represent a valid media pool.")
(register-error 4303 :ERROR_DRIVE_MEDIA_MISMATCH "The drive and medium are not compatible or exist in different libraries.")
(register-error 4304 :ERROR_MEDIA_OFFLINE "The medium currently exists in an offline library and must be online to perform this operation.")
(register-error 4305 :ERROR_LIBRARY_OFFLINE "The operation cannot be performed on an offline library.")
(register-error 4306 :ERROR_EMPTY "The library, drive, or media pool is empty.")
(register-error 4307 :ERROR_NOT_EMPTY "The library, drive, or media pool must be empty to perform this operation.")
(register-error 4308 :ERROR_MEDIA_UNAVAILABLE "No media is currently available in this media pool or library.")
(register-error 4309 :ERROR_RESOURCE_DISABLED "A resource required for this operation is disabled.")
(register-error 4310 :ERROR_INVALID_CLEANER "The media identifier does not represent a valid cleaner.")
(register-error 4311 :ERROR_UNABLE_TO_CLEAN "The drive cannot be cleaned or does not support cleaning.")
(register-error 4312 :ERROR_OBJECT_NOT_FOUND "The object identifier does not represent a valid object.")
(register-error 4313 :ERROR_DATABASE_FAILURE "Unable to read from or write to the database.")
(register-error 4314 :ERROR_DATABASE_FULL "The database is full.")
(register-error 4315 :ERROR_MEDIA_INCOMPATIBLE "The medium is not compatible with the device or media pool.")
(register-error 4316 :ERROR_RESOURCE_NOT_PRESENT "The resource required for this operation does not exist.")
(register-error 4317 :ERROR_INVALID_OPERATION "The operation identifier is not valid.")
(register-error 4318 :ERROR_MEDIA_NOT_AVAILABLE "The media is not mounted or ready for use.")
(register-error 4319 :ERROR_DEVICE_NOT_AVAILABLE "The device is not ready for use.")
(register-error 4320 :ERROR_REQUEST_REFUSED "The operator or administrator has refused the request.")
(register-error 4321 :ERROR_INVALID_DRIVE_OBJECT "The drive identifier does not represent a valid drive.")
(register-error 4322 :ERROR_LIBRARY_FULL "Library is full. No slot is available for use.")
(register-error 4323 :ERROR_MEDIUM_NOT_ACCESSIBLE "The transport cannot access the medium.")
(register-error 4324 :ERROR_UNABLE_TO_LOAD_MEDIUM "Unable to load the medium into the drive.")
(register-error 4325 :ERROR_UNABLE_TO_INVENTORY_DRIVE "Unable to retrieve the drive status.")
(register-error 4326 :ERROR_UNABLE_TO_INVENTORY_SLOT "Unable to retrieve the slot status.")
(register-error 4327 :ERROR_UNABLE_TO_INVENTORY_TRANSPORT "Unable to retrieve status about the transport.")
(register-error 4328 :ERROR_TRANSPORT_FULL "Cannot use the transport because it is already in use.")
(register-error 4329 :ERROR_CONTROLLING_IEPORT "Unable to open or close the inject/eject port.")
(register-error 4330 :ERROR_UNABLE_TO_EJECT_MOUNTED_MEDIA "Unable to eject the medium because it is in a drive.")
(register-error 4331 :ERROR_CLEANER_SLOT_SET "A cleaner slot is already reserved.")
(register-error 4332 :ERROR_CLEANER_SLOT_NOT_SET "A cleaner slot is not reserved.")
(register-error 4333 :ERROR_CLEANER_CARTRIDGE_SPENT "The cleaner cartridge has performed the maximum number of drive cleanings.")
(register-error 4334 :ERROR_UNEXPECTED_OMID "Unexpected on-medium identifier.")
(register-error 4335 :ERROR_CANT_DELETE_LAST_ITEM "The last remaining item in this group or resource cannot be deleted.")
(register-error 4336 :ERROR_MESSAGE_EXCEEDS_MAX_SIZE "The message provided exceeds the maximum size allowed for this parameter.")
(register-error 4337 :ERROR_VOLUME_CONTAINS_SYS_FILES "The volume contains system or paging files.")
(register-error 4338 :ERROR_INDIGENOUS_TYPE "The media type cannot be removed from this library since at least one drive in the library reports it can support this media type.")
(register-error 4339 :ERROR_NO_SUPPORTING_DRIVES "This offline media cannot be mounted on this system since no enabled drives are present which can be used.")
(register-error 4340 :ERROR_CLEANER_CARTRIDGE_INSTALLED "A cleaner cartridge is present in the tape library.")
(register-error 4341 :ERROR_IEPORT_FULL "Cannot use the inject/eject port because it is not empty.")
(register-error 4350 :ERROR_FILE_OFFLINE "This file is currently not available for use on this computer.")
(register-error 4351 :ERROR_REMOTE_STORAGE_NOT_ACTIVE "The remote storage service is not operational at this time.")
(register-error 4352 :ERROR_REMOTE_STORAGE_MEDIA_ERROR "The remote storage service encountered a media error.")
(register-error 4390 :ERROR_NOT_A_REPARSE_POINT "The file or directory is not a reparse point.")
(register-error 4391 :ERROR_REPARSE_ATTRIBUTE_CONFLICT "The reparse point attribute cannot be set because it conflicts with an existing attribute.")
(register-error 4392 :ERROR_INVALID_REPARSE_DATA "The data present in the reparse point buffer is invalid.")
(register-error 4393 :ERROR_REPARSE_TAG_INVALID "The tag present in the reparse point buffer is invalid.")
(register-error 4394 :ERROR_REPARSE_TAG_MISMATCH "There is a mismatch between the tag specified in the request and the tag present in the reparse point.")
(register-error 4400 :ERROR_APP_DATA_NOT_FOUND "Fast Cache data not found.")
(register-error 4401 :ERROR_APP_DATA_EXPIRED "Fast Cache data expired.")
(register-error 4402 :ERROR_APP_DATA_CORRUPT "Fast Cache data corrupt.")
(register-error 4403 :ERROR_APP_DATA_LIMIT_EXCEEDED "Fast Cache data has exceeded its max size and cannot be updated.")
(register-error 4404 :ERROR_APP_DATA_REBOOT_REQUIRED "Fast Cache has been ReArmed and requires a reboot until it can be updated.")
(register-error 4420 :ERROR_SECUREBOOT_ROLLBACK_DETECTED "Secure Boot detected that rollback of protected data has been attempted.")
(register-error 4421 :ERROR_SECUREBOOT_POLICY_VIOLATION "The value is protected by Secure Boot policy and cannot be modified or deleted.")
(register-error 4422 :ERROR_SECUREBOOT_INVALID_POLICY "The Secure Boot policy is invalid.")
(register-error 4423 :ERROR_SECUREBOOT_POLICY_PUBLISHER_NOT_FOUND "A new Secure Boot policy did not contain the current publisher on its update list.")
(register-error 4424 :ERROR_SECUREBOOT_POLICY_NOT_SIGNED "The Secure Boot policy is either not signed or is signed by a non-trusted signer.")
(register-error 4425 :ERROR_SECUREBOOT_NOT_ENABLED "Secure Boot is not enabled on this machine.")
(register-error 4426 :ERROR_SECUREBOOT_FILE_REPLACED "Secure Boot requires that certain files and drivers are not replaced by other files or drivers.")
(register-error 4440 :ERROR_OFFLOAD_READ_FLT_NOT_SUPPORTED "The copy offload read operation is not supported by a filter.")
(register-error 4441 :ERROR_OFFLOAD_WRITE_FLT_NOT_SUPPORTED "The copy offload write operation is not supported by a filter.")
(register-error 4442 :ERROR_OFFLOAD_READ_FILE_NOT_SUPPORTED "The copy offload read operation is not supported for the file.")
(register-error 4443 :ERROR_OFFLOAD_WRITE_FILE_NOT_SUPPORTED "The copy offload write operation is not supported for the file.")
(register-error 4500 :ERROR_VOLUME_NOT_SIS_ENABLED "Single Instance Storage is not available on this volume.")

