;;;; src/ipsec.lisp
;;;
;;; Contains IPsec (Internet Protocol Security) and IKE (Internet Key Exchange)
;;; related error codes.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; IPsec Policy and Filter Errors (13000-13025)
;;;--------------------------------------------------------------------------

(register-error 13000 :ERROR_IPSEC_QM_POLICY_EXISTS "The specified quick mode policy already exists.")
(register-error 13001 :ERROR_IPSEC_QM_POLICY_NOT_FOUND "The specified quick mode policy was not found.")
(register-error 13002 :ERROR_IPSEC_QM_POLICY_IN_USE "The specified quick mode policy is being used.")
(register-error 13003 :ERROR_IPSEC_MM_POLICY_EXISTS "The specified main mode policy already exists.")
(register-error 13004 :ERROR_IPSEC_MM_POLICY_NOT_FOUND "The specified main mode policy was not found.")
(register-error 13005 :ERROR_IPSEC_MM_POLICY_IN_USE "The specified main mode policy is being used.")
(register-error 13006 :ERROR_IPSEC_MM_FILTER_EXISTS "The specified main mode filter already exists.")
(register-error 13007 :ERROR_IPSEC_MM_FILTER_NOT_FOUND "The specified main mode filter was not found.")
(register-error 13008 :ERROR_IPSEC_TRANSPORT_FILTER_EXISTS "The specified transport mode filter already exists.")
(register-error 13009 :ERROR_IPSEC_TRANSPORT_FILTER_NOT_FOUND "The specified transport mode filter does not exist.")
(register-error 13010 :ERROR_IPSEC_MM_AUTH_EXISTS "The specified main mode authentication list exists.")
(register-error 13011 :ERROR_IPSEC_MM_AUTH_NOT_FOUND "The specified main mode authentication list was not found.")
(register-error 13012 :ERROR_IPSEC_MM_AUTH_IN_USE "The specified main mode authentication list is being used.")
(register-error 13013 :ERROR_IPSEC_DEFAULT_MM_POLICY_NOT_FOUND "The specified default main mode policy was not found.")
(register-error 13014 :ERROR_IPSEC_DEFAULT_MM_AUTH_NOT_FOUND "The specified default main mode authentication list was not found.")
(register-error 13015 :ERROR_IPSEC_DEFAULT_QM_POLICY_NOT_FOUND "The specified default quick mode policy was not found.")
(register-error 13016 :ERROR_IPSEC_TUNNEL_FILTER_EXISTS "The specified tunnel mode filter exists.")
(register-error 13017 :ERROR_IPSEC_TUNNEL_FILTER_NOT_FOUND "The specified tunnel mode filter was not found.")
(register-error 13018 :ERROR_IPSEC_MM_FILTER_PENDING_DELETION "The Main Mode filter is pending deletion.")
(register-error 13019 :ERROR_IPSEC_TRANSPORT_FILTER_PENDING_DELETION "The transport filter is pending deletion.")
(register-error 13020 :ERROR_IPSEC_TUNNEL_FILTER_PENDING_DELETION "The tunnel filter is pending deletion.")
(register-error 13021 :ERROR_IPSEC_MM_POLICY_PENDING_DELETION "The Main Mode policy is pending deletion.")
(register-error 13022 :ERROR_IPSEC_MM_AUTH_PENDING_DELETION "The Main Mode authentication bundle is pending deletion.")
(register-error 13023 :ERROR_IPSEC_QM_POLICY_PENDING_DELETION "The Quick Mode policy is pending deletion.")
(register-error 13024 :WARNING_IPSEC_MM_POLICY_PRUNED "The Main Mode policy was successfully added, but some of the requested offers are not supported.")
(register-error 13025 :WARNING_IPSEC_QM_POLICY_PRUNED "The Quick Mode policy was successfully added, but some of the requested offers are not supported.")

;;;--------------------------------------------------------------------------
;;; IKE (Internet Key Exchange) Errors (13800-13932)
;;;--------------------------------------------------------------------------

(register-error 13800 :ERROR_IPSEC_IKE_NEG_STATUS_BEGIN "ERROR_IPSEC_IKE_NEG_STATUS_BEGIN")
(register-error 13801 :ERROR_IPSEC_IKE_AUTH_FAIL "IKE authentication credentials are unacceptable.")
(register-error 13802 :ERROR_IPSEC_IKE_ATTRIB_FAIL "IKE security attributes are unacceptable.")
(register-error 13803 :ERROR_IPSEC_IKE_NEGOTIATION_PENDING "IKE Negotiation in progress.")
(register-error 13804 :ERROR_IPSEC_IKE_GENERAL_PROCESSING_ERROR "General processing error.")
(register-error 13805 :ERROR_IPSEC_IKE_TIMED_OUT "Negotiation timed out.")
(register-error 13806 :ERROR_IPSEC_IKE_NO_CERT "IKE failed to find valid machine certificate. Contact your Network Security Administrator about installing a valid certificate in the appropriate Certificate Store.")
(register-error 13807 :ERROR_IPSEC_IKE_SA_DELETED "IKE SA deleted by peer before establishment completed.")
(register-error 13808 :ERROR_IPSEC_IKE_SA_REAPED "IKE SA deleted before establishment completed.")
(register-error 13809 :ERROR_IPSEC_IKE_MM_ACQUIRE_DROP "Negotiation request sat in Queue too long.")
(register-error 13810 :ERROR_IPSEC_IKE_QM_ACQUIRE_DROP "Negotiation request sat in Queue too long.")
(register-error 13811 :ERROR_IPSEC_IKE_QUEUE_DROP_MM "Negotiation request sat in Queue too long.")
(register-error 13812 :ERROR_IPSEC_IKE_QUEUE_DROP_NO_MM "Negotiation request sat in Queue too long.")
(register-error 13813 :ERROR_IPSEC_IKE_DROP_NO_RESPONSE "No response from peer.")
(register-error 13814 :ERROR_IPSEC_IKE_MM_DELAY_DROP "Negotiation took too long.")
(register-error 13815 :ERROR_IPSEC_IKE_QM_DELAY_DROP "Negotiation took too long.")
(register-error 13816 :ERROR_IPSEC_IKE_ERROR "Unknown error occurred.")
(register-error 13817 :ERROR_IPSEC_IKE_CRL_FAILED "Certificate Revocation Check failed.")
(register-error 13818 :ERROR_IPSEC_IKE_INVALID_KEY_USAGE "Invalid certificate key usage.")
(register-error 13819 :ERROR_IPSEC_IKE_INVALID_CERT_TYPE "Invalid certificate type.")
(register-error 13820 :ERROR_IPSEC_IKE_NO_PRIVATE_KEY "IKE negotiation failed because the machine certificate used does not have a private key. IPsec certificates require a private key. Contact your Network Security administrator about replacing with a certificate that has a private key.")
(register-error 13821 :ERROR_IPSEC_IKE_SIMULTANEOUS_REKEY "Simultaneous rekeys were detected.")
(register-error 13822 :ERROR_IPSEC_IKE_DH_FAIL "Failure in Diffie-Hellman computation.")
(register-error 13823 :ERROR_IPSEC_IKE_CRITICAL_PAYLOAD_NOT_RECOGNIZED "Don't know how to process critical payload.")
(register-error 13824 :ERROR_IPSEC_IKE_INVALID_HEADER "Invalid header.")
(register-error 13825 :ERROR_IPSEC_IKE_NO_POLICY "No policy configured.")
(register-error 13826 :ERROR_IPSEC_IKE_INVALID_SIGNATURE "Failed to verify signature.")
(register-error 13827 :ERROR_IPSEC_IKE_KERBEROS_ERROR "Failed to authenticate using Kerberos.")
(register-error 13828 :ERROR_IPSEC_IKE_NO_PUBLIC_KEY "Peer's certificate did not have a public key.")
(register-error 13829 :ERROR_IPSEC_IKE_PROCESS_ERR "Error processing error payload.")
(register-error 13830 :ERROR_IPSEC_IKE_PROCESS_ERR_SA "Error processing SA payload.")
(register-error 13831 :ERROR_IPSEC_IKE_PROCESS_ERR_PROP "Error processing Proposal payload.")
(register-error 13832 :ERROR_IPSEC_IKE_PROCESS_ERR_TRANS "Error processing Transform payload.")
(register-error 13833 :ERROR_IPSEC_IKE_PROCESS_ERR_KE "Error processing KE payload.")
(register-error 13834 :ERROR_IPSEC_IKE_PROCESS_ERR_ID "Error processing ID payload.")
(register-error 13835 :ERROR_IPSEC_IKE_PROCESS_ERR_CERT "Error processing Cert payload.")
(register-error 13836 :ERROR_IPSEC_IKE_PROCESS_ERR_CERT_REQ "Error processing Certificate Request payload.")
(register-error 13837 :ERROR_IPSEC_IKE_PROCESS_ERR_HASH "Error processing Hash payload.")
(register-error 13838 :ERROR_IPSEC_IKE_PROCESS_ERR_SIG "Error processing Signature payload.")
(register-error 13839 :ERROR_IPSEC_IKE_PROCESS_ERR_NONCE "Error processing Nonce payload.")
(register-error 13840 :ERROR_IPSEC_IKE_PROCESS_ERR_NOTIFY "Error processing Notify payload.")
(register-error 13841 :ERROR_IPSEC_IKE_PROCESS_ERR_DELETE "Error processing Delete Payload.")
(register-error 13842 :ERROR_IPSEC_IKE_PROCESS_ERR_VENDOR "Error processing VendorId payload.")
(register-error 13843 :ERROR_IPSEC_IKE_INVALID_PAYLOAD "Invalid payload received.")
(register-error 13844 :ERROR_IPSEC_IKE_LOAD_SOFT_SA "Soft SA loaded.")
(register-error 13845 :ERROR_IPSEC_IKE_SOFT_SA_TORN_DOWN "Soft SA torn down.")
(register-error 13846 :ERROR_IPSEC_IKE_INVALID_COOKIE "Invalid cookie received.")
(register-error 13847 :ERROR_IPSEC_IKE_NO_PEER_CERT "Peer failed to send valid machine certificate.")
(register-error 13848 :ERROR_IPSEC_IKE_PEER_CRL_FAILED "Certification Revocation check of peer's certificate failed.")
(register-error 13849 :ERROR_IPSEC_IKE_POLICY_CHANGE "New policy invalidated SAs formed with old policy.")
(register-error 13850 :ERROR_IPSEC_IKE_NO_MM_POLICY "There is no available Main Mode IKE policy.")
(register-error 13851 :ERROR_IPSEC_IKE_NOTCBPRIV "Failed to enabled TCB privilege.")
(register-error 13852 :ERROR_IPSEC_IKE_SECLOADFAIL "Failed to load SECURITY.DLL.")
(register-error 13853 :ERROR_IPSEC_IKE_FAILSSPINIT "Failed to obtain security function table dispatch address from SSPI.")
(register-error 13854 :ERROR_IPSEC_IKE_FAILQUERYSSP "Failed to query Kerberos package to obtain max token size.")
(register-error 13855 :ERROR_IPSEC_IKE_SRVACQFAIL "Failed to obtain Kerberos server credentials for ISAKMP/ERROR_IPSEC_IKE service. Kerberos authentication will not function. The most likely reason for this is lack of domain membership. This is normal if your computer is a member of a workgroup.")
(register-error 13856 :ERROR_IPSEC_IKE_SRVQUERYCRED "Failed to determine SSPI principal name for ISAKMP/ERROR_IPSEC_IKE service ([QueryCredentialsAttributes]).")
(register-error 13857 :ERROR_IPSEC_IKE_GETSPIFAIL "Failed to obtain new SPI for the inbound SA from IPsec driver. The most common cause for this is that the driver does not have the correct filter. Check your policy to verify the filters.")
(register-error 13858 :ERROR_IPSEC_IKE_INVALID_FILTER "Given filter is invalid.")
(register-error 13859 :ERROR_IPSEC_IKE_OUT_OF_MEMORY "Memory allocation failed.")
(register-error 13860 :ERROR_IPSEC_IKE_ADD_UPDATE_KEY_FAILED "Failed to add Security Association to IPsec Driver. The most common cause for this is if the IKE negotiation took too long to complete. If the problem persists, reduce the load on the faulting machine.")
(register-error 13861 :ERROR_IPSEC_IKE_INVALID_POLICY "Invalid policy.")
(register-error 13862 :ERROR_IPSEC_IKE_UNKNOWN_DOI "Invalid DOI.")
(register-error 13863 :ERROR_IPSEC_IKE_INVALID_SITUATION "Invalid situation.")
(register-error 13864 :ERROR_IPSEC_IKE_DH_FAILURE "Diffie-Hellman failure.")
(register-error 13865 :ERROR_IPSEC_IKE_INVALID_GROUP "Invalid Diffie-Hellman group.")
(register-error 13866 :ERROR_IPSEC_IKE_ENCRYPT "Error encrypting payload.")
(register-error 13867 :ERROR_IPSEC_IKE_DECRYPT "Error decrypting payload.")
(register-error 13868 :ERROR_IPSEC_IKE_POLICY_MATCH "Policy match error.")
(register-error 13869 :ERROR_IPSEC_IKE_UNSUPPORTED_ID "Unsupported ID.")
(register-error 13870 :ERROR_IPSEC_IKE_INVALID_HASH "Hash verification failed.")
(register-error 13871 :ERROR_IPSEC_IKE_INVALID_HASH_ALG "Invalid hash algorithm.")
(register-error 13872 :ERROR_IPSEC_IKE_INVALID_HASH_SIZE "Invalid hash size.")
(register-error 13873 :ERROR_IPSEC_IKE_INVALID_ENCRYPT_ALG "Invalid encryption algorithm.")
(register-error 13874 :ERROR_IPSEC_IKE_INVALID_AUTH_ALG "Invalid authentication algorithm.")
(register-error 13875 :ERROR_IPSEC_IKE_INVALID_SIG "Invalid certificate signature.")
(register-error 13876 :ERROR_IPSEC_IKE_LOAD_FAILED "Load failed.")
(register-error 13877 :ERROR_IPSEC_IKE_RPC_DELETE "Deleted via RPC call.")
(register-error 13878 :ERROR_IPSEC_IKE_BENIGN_REINIT "Temporary state created to perform reinitialization. This is not a real failure.")
(register-error 13879 :ERROR_IPSEC_IKE_INVALID_RESPONDER_LIFETIME_NOTIFY "The lifetime value received in the Responder Lifetime Notify is below the Windows 2000 configured minimum value. Please fix the policy on the peer machine.")
(register-error 13881 :ERROR_IPSEC_IKE_INVALID_CERT_KEYLEN "Key length in certificate is too small for configured security requirements.")
(register-error 13882 :ERROR_IPSEC_IKE_MM_LIMIT "Max number of established MM SAs to peer exceeded.")
(register-error 13883 :ERROR_IPSEC_IKE_NEGOTIATION_DISABLED "IKE received a policy that disables negotiation.")
(register-error 13884 :ERROR_IPSEC_IKE_QM_LIMIT "Reached maximum quick mode limit for the main mode. New main mode will be started.")
(register-error 13885 :ERROR_IPSEC_IKE_MM_EXPIRED "Main mode SA lifetime expired or peer sent a main mode delete.")
(register-error 13886 :ERROR_IPSEC_IKE_PEER_MM_ASSUMED_INVALID "Main mode SA assumed to be invalid because peer stopped responding.")
(register-error 13887 :ERROR_IPSEC_IKE_CERT_CHAIN_POLICY_MISMATCH "Certificate doesn't chain to a trusted root in IPsec policy.")
(register-error 13888 :ERROR_IPSEC_IKE_UNEXPECTED_MESSAGE_ID "Received unexpected message ID.")
(register-error 13889 :ERROR_IPSEC_IKE_INVALID_AUTH_PAYLOAD "Received invalid authentication offers.")
(register-error 13890 :ERROR_IPSEC_IKE_DOS_COOKIE_SENT "Sent DoS cookie notify to initiator.")
(register-error 13891 :ERROR_IPSEC_IKE_SHUTTING_DOWN "IKE service is shutting down.")
(register-error 13892 :ERROR_IPSEC_IKE_CGA_AUTH_FAILED "Could not verify binding between CGA address and certificate.")
(register-error 13893 :ERROR_IPSEC_IKE_PROCESS_ERR_NATOA "Error processing NatOA payload.")
(register-error 13894 :ERROR_IPSEC_IKE_INVALID_MM_FOR_QM "Parameters of the main mode are invalid for this quick mode.")
(register-error 13895 :ERROR_IPSEC_IKE_QM_EXPIRED "Quick mode SA was expired by IPsec driver.")
(register-error 13896 :ERROR_IPSEC_IKE_TOO_MANY_FILTERS "Too many dynamically added IKEEXT filters were detected.")
(register-error 13897 :ERROR_IPSEC_IKE_NEG_STATUS_END "ERROR_IPSEC_IKE_NEG_STATUS_END")
(register-error 13898 :ERROR_IPSEC_IKE_KILL_DUMMY_NAP_TUNNEL "NAP reauth succeeded and must delete the dummy NAP IKEv2 tunnel.")
(register-error 13899 :ERROR_IPSEC_IKE_INNER_IP_ASSIGNMENT_FAILURE "Error in assigning inner IP address to initiator in tunnel mode.")
(register-error 13900 :ERROR_IPSEC_IKE_REQUIRE_CP_PAYLOAD_MISSING "Require configuration payload missing.")
(register-error 13901 :ERROR_IPSEC_KEY_MODULE_IMPERSONATION_NEGOTIATION_PENDING "A negotiation running as the security principle who issued the connection is in progress.")
(register-error 13902 :ERROR_IPSEC_IKE_COEXISTENCE_SUPPRESS "SA was deleted due to IKEv1/AuthIP co-existence suppress check.")
(register-error 13903 :ERROR_IPSEC_IKE_RATELIMIT_DROP "Incoming SA request was dropped due to peer IP address rate limiting.")
(register-error 13904 :ERROR_IPSEC_IKE_PEER_DOESNT_SUPPORT_MOBIKE "Peer does not support MOBIKE.")
(register-error 13905 :ERROR_IPSEC_IKE_AUTHORIZATION_FAILURE "SA establishment is not authorized.")
(register-error 13906 :ERROR_IPSEC_IKE_STRONG_CRED_AUTHORIZATION_FAILURE "SA establishment is not authorized because there is not a sufficiently strong PKINIT-based credential.")
(register-error 13907 :ERROR_IPSEC_IKE_AUTHORIZATION_FAILURE_WITH_OPTIONAL_RETRY "SA establishment is not authorized. You may need to enter updated or different credentials such as a smartcard.")
(register-error 13908 :ERROR_IPSEC_IKE_STRONG_CRED_AUTHORIZATION_AND_CERTMAP_FAILURE "SA establishment is not authorized because there is not a sufficiently strong PKINIT-based credential. This might be related to certificate-to-account mapping failure for the SA.")
(register-error 13909 :ERROR_IPSEC_IKE_NEG_STATUS_EXTENDED_END "ERROR_IPSEC_IKE_NEG_STATUS_EXTENDED_END")
(register-error 13910 :ERROR_IPSEC_BAD_SPI "The SPI in the packet does not match a valid IPsec SA.")
(register-error 13911 :ERROR_IPSEC_SA_LIFETIME_EXPIRED "Packet was received on an IPsec SA whose lifetime has expired.")
(register-error 13912 :ERROR_IPSEC_WRONG_SA "Packet was received on an IPsec SA that does not match the packet characteristics.")
(register-error 13913 :ERROR_IPSEC_REPLAY_CHECK_FAILED "Packet sequence number replay check failed.")
(register-error 13914 :ERROR_IPSEC_INVALID_PACKET "IPsec header and/or trailer in the packet is invalid.")
(register-error 13915 :ERROR_IPSEC_INTEGRITY_CHECK_FAILED "IPsec integrity check failed.")
(register-error 13916 :ERROR_IPSEC_CLEAR_TEXT_DROP "IPsec dropped a clear text packet.")
(register-error 13917 :ERROR_IPSEC_AUTH_FIREWALL_DROP "IPsec dropped an incoming ESP packet in authenticated firewall mode. This drop is benign.")
(register-error 13918 :ERROR_IPSEC_THROTTLE_DROP "IPsec dropped a packet due to DoS throttling.")
(register-error 13925 :ERROR_IPSEC_DOSP_BLOCK "IPsec DoS Protection matched an explicit block rule.")
(register-error 13926 :ERROR_IPSEC_DOSP_RECEIVED_MULTICAST "IPsec DoS Protection received an IPsec specific multicast packet which is not allowed.")
(register-error 13927 :ERROR_IPSEC_DOSP_INVALID_PACKET "IPsec DoS Protection received an incorrectly formatted packet.")
(register-error 13928 :ERROR_IPSEC_DOSP_STATE_LOOKUP_FAILED "IPsec DoS Protection failed to look up state.")
(register-error 13929 :ERROR_IPSEC_DOSP_MAX_ENTRIES "IPsec DoS Protection failed to create state because the maximum number of entries allowed by policy has been reached.")
(register-error 13930 :ERROR_IPSEC_DOSP_KEYMOD_NOT_ALLOWED "IPsec DoS Protection received an IPsec negotiation packet for a keying module which is not allowed by policy.")
(register-error 13931 :ERROR_IPSEC_DOSP_NOT_INSTALLED "IPsec DoS Protection has not been enabled.")
(register-error 13932 :ERROR_IPSEC_DOSP_MAX_PER_IP_RATELIMIT_QUEUES "IPsec DoS Protection failed to create a per internal IP rate limit queue because the maximum number of queues allowed by policy has been reached.")

