;;;; src/network.lisp
;;;
;;; Contains network-related system error codes (WNet, etc.).

(in-package #:cl-win32-errors)

(register-error 1200 :ERROR_BAD_DEVICE "The specified device name is invalid.")
(register-error 1201 :ERROR_CONNECTION_UNAVAIL "The device is not currently connected but it is a remembered connection.")
(register-error 1202 :ERROR_DEVICE_ALREADY_REMEMBERED "The local device name has a remembered connection to another network resource.")
(register-error 1203 :ERROR_NO_NET_OR_BAD_PATH "The network path was either typed incorrectly, does not exist, or the network provider is not currently available. Please try retyping the path or contact your network administrator.")
(register-error 1204 :ERROR_BAD_PROVIDER "The specified network provider name is invalid.")
(register-error 1205 :ERROR_CANNOT_OPEN_PROFILE "Unable to open the network connection profile.")
(register-error 1206 :ERROR_BAD_PROFILE "The network connection profile is corrupted.")
(register-error 1207 :ERROR_NOT_CONTAINER "Cannot enumerate a noncontainer.")
(register-error 1208 :ERROR_EXTENDED_ERROR "An extended error has occurred.")
(register-error 1209 :ERROR_INVALID_GROUPNAME "The format of the specified group name is invalid.")
(register-error 1210 :ERROR_INVALID_COMPUTERNAME "The format of the specified computer name is invalid.")
(register-error 1211 :ERROR_INVALID_EVENTNAME "The format of the specified event name is invalid.")
(register-error 1212 :ERROR_INVALID_DOMAINNAME "The format of the specified domain name is invalid.")
(register-error 1213 :ERROR_INVALID_SERVICENAME "The format of the specified service name is invalid.")
(register-error 1214 :ERROR_INVALID_NETNAME "The format of the specified network name is invalid.")
(register-error 1215 :ERROR_INVALID_SHARENAME "The format of the specified share name is invalid.")
(register-error 1216 :ERROR_INVALID_PASSWORDNAME "The format of the specified password is invalid.")
(register-error 1217 :ERROR_INVALID_MESSAGENAME "The format of the specified message name is invalid.")
(register-error 1218 :ERROR_INVALID_MESSAGEDEST "The format of the specified message destination is invalid.")
(register-error 1219 :ERROR_SESSION_CREDENTIAL_CONFLICT "Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.")
(register-error 1220 :ERROR_REMOTE_SESSION_LIMIT_EXCEEDED "An attempt was made to establish a session to a network server, but there are already too many sessions established to that server.")
(register-error 1221 :ERROR_DUP_DOMAINNAME "The workgroup or domain name is already in use by another computer on the network.")
(register-error 1222 :ERROR_NO_NETWORK "The network is not present or not started.")
(register-error 1223 :ERROR_CANCELLED "The operation was canceled by the user.")
(register-error 1224 :ERROR_USER_MAPPED_FILE "The requested operation cannot be performed on a file with a user-mapped section open.")
(register-error 1225 :ERROR_CONNECTION_REFUSED "The remote computer refused the network connection.")
(register-error 1226 :ERROR_GRACEFUL_DISCONNECT "The network connection was gracefully closed.")
(register-error 1227 :ERROR_ADDRESS_ALREADY_ASSOCIATED "The network transport endpoint already has an address associated with it.")
(register-error 1228 :ERROR_ADDRESS_NOT_ASSOCIATED "An address has not yet been associated with the network endpoint.")
(register-error 1229 :ERROR_CONNECTION_INVALID "An operation was attempted on a nonexistent network connection.")
(register-error 1230 :ERROR_CONNECTION_ACTIVE "An invalid operation was attempted on an active network connection.")
(register-error 1231 :ERROR_NETWORK_UNREACHABLE "The network location cannot be reached. For information about network troubleshooting, see Windows Help.")
(register-error 1232 :ERROR_HOST_UNREACHABLE "The network location cannot be reached. For information about network troubleshooting, see Windows Help.")
(register-error 1233 :ERROR_PROTOCOL_UNREACHABLE "The network location cannot be reached. For information about network troubleshooting, see Windows Help.")
(register-error 1234 :ERROR_PORT_UNREACHABLE "No service is operating at the destination network endpoint on the remote system.")
(register-error 1235 :ERROR_REQUEST_ABORTED "The request was aborted.")
(register-error 1236 :ERROR_CONNECTION_ABORTED "The network connection was aborted by the local system.")
(register-error 1237 :ERROR_RETRY "The operation could not be completed. A retry should be performed.")
(register-error 1238 :ERROR_CONNECTION_COUNT_LIMIT "A connection to the server could not be made because the limit on the number of concurrent connections for this account has been reached.")
(register-error 1239 :ERROR_LOGIN_TIME_RESTRICTION "Attempting to log in during an unauthorized time of day for this account.")
(register-error 1240 :ERROR_LOGIN_WKSTA_RESTRICTION "The account is not authorized to log in from this station.")
(register-error 1241 :ERROR_INCORRECT_ADDRESS "The network address could not be used for the operation requested.")
(register-error 1242 :ERROR_ALREADY_REGISTERED "The service is already registered.")
(register-error 1243 :ERROR_SERVICE_NOT_FOUND "The specified service does not exist.")
(register-error 1244 :ERROR_NOT_AUTHENTICATED "The operation being requested was not performed because the user has not been authenticated.")
(register-error 1245 :ERROR_NOT_LOGGED_ON "The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist.")
(register-error 1246 :ERROR_CONTINUE "Continue with work in progress.")
(register-error 1247 :ERROR_ALREADY_INITIALIZED "An attempt was made to perform an initialization operation when initialization has already been completed.")
(register-error 1248 :ERROR_NO_MORE_DEVICES "No more local devices.")
(register-error 1249 :ERROR_NO_SUCH_SITE "The specified site does not exist.")
(register-error 1250 :ERROR_DOMAIN_CONTROLLER_EXISTS "A domain controller with the specified name already exists.")
(register-error 1251 :ERROR_ONLY_IF_CONNECTED "This operation is supported only when you are connected to the server.")
(register-error 1252 :ERROR_OVERRIDE_NOCHANGES "The group policy framework should call the extension even if there are no changes.")
(register-error 1253 :ERROR_BAD_USER_PROFILE "The specified user does not have a valid profile.")
(register-error 1254 :ERROR_NOT_SUPPORTED_ON_SBS "This operation is not supported on a computer running Windows Server 2003 for Small Business Server.")
(register-error 1255 :ERROR_SERVER_SHUTDOWN_IN_PROGRESS "The server machine is shutting down.")
(register-error 1256 :ERROR_HOST_DOWN "The remote system is not available. For information about network troubleshooting, see Windows Help.")
(register-error 1257 :ERROR_NON_ACCOUNT_SID "The security identifier provided is not from an account domain.")
(register-error 1258 :ERROR_NON_DOMAIN_SID "The security identifier provided does not have a domain component.")
(register-error 1259 :ERROR_APPHELP_BLOCK "AppHelp dialog canceled thus preventing the application from starting.")
(register-error 1260 :ERROR_ACCESS_DISABLED_BY_POLICY "This program is blocked by group policy. For more information, contact your system administrator.")
(register-error 1261 :ERROR_REG_NAT_CONSUMPTION "A program attempt to use an invalid register value. Normally caused by an uninitialized register. This error is Itanium specific.")
(register-error 1262 :ERROR_CSCSHARE_OFFLINE "The share is currently offline or does not exist.")
(register-error 1263 :ERROR_PKINIT_FAILURE "The Kerberos protocol encountered an error while validating the KDC certificate during smartcard logon. There is more information in the system event log.")
(register-error 1264 :ERROR_SMARTCARD_SUBSYSTEM_FAILURE "The Kerberos protocol encountered an error while attempting to utilize the smartcard subsystem.")
(register-error 1265 :ERROR_DOWNGRADE_DETECTED "The system cannot contact a domain controller to service the authentication request. Please try again later.")
(register-error 1271 :ERROR_MACHINE_LOCKED "The machine is locked and cannot be shut down without the force option.")
(register-error 1273 :ERROR_CALLBACK_SUPPLIED_INVALID_DATA "An application-defined callback gave invalid data when called.")
(register-error 1274 :ERROR_SYNC_FOREGROUND_REFRESH_REQUIRED "The group policy framework should call the extension in the synchronous foreground policy refresh.")
(register-error 1275 :ERROR_DRIVER_BLOCKED "This driver has been blocked from loading.")
(register-error 1276 :ERROR_INVALID_IMPORT_OF_NON_DLL "A dynamic link library (DLL) referenced a module that was neither a DLL nor the process's executable image.")
(register-error 1277 :ERROR_ACCESS_DISABLED_WEBBLADE "Windows cannot open this program since it has been disabled.")
(register-error 1278 :ERROR_ACCESS_DISABLED_WEBBLADE_TAMPER "Windows cannot open this program because the license enforcement system has been tampered with or become corrupted.")
(register-error 1279 :ERROR_RECOVERY_FAILURE "A transaction recover failed.")
(register-error 1280 :ERROR_ALREADY_FIBER "The current thread has already been converted to a fiber.")
(register-error 1281 :ERROR_ALREADY_THREAD "The current thread has already been converted from a fiber.")
(register-error 1282 :ERROR_STACK_BUFFER_OVERRUN "The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.")
(register-error 1283 :ERROR_PARAMETER_QUOTA_EXCEEDED "Data present in one of the parameters is more than the function can operate on.")
(register-error 1284 :ERROR_DEBUGGER_INACTIVE "An attempt to do an operation on a debug object failed because the object is in the process of being deleted.")
(register-error 1285 :ERROR_DELAY_LOAD_FAILED "An attempt to delay-load a .dll or get a function address in a delay-loaded .dll failed.")
(register-error 1286 :ERROR_VDM_DISALLOWED "%1 is a 16-bit application. You do not have permissions to execute 16-bit applications. Check your permissions with your system administrator.")
(register-error 1287 :ERROR_UNIDENTIFIED_ERROR "Insufficient information exists to identify the cause of failure.")
(register-error 1288 :ERROR_INVALID_CRUNTIME_PARAMETER "The parameter passed to a C runtime function is incorrect.")
(register-error 1289 :ERROR_BEYOND_VDL "The operation occurred beyond the valid data length of the file.")
(register-error 1290 :ERROR_INCOMPATIBLE_SERVICE_SID_TYPE "The service start failed since one or more services in the same process have an incompatible service SID type setting. A service with restricted service SID type can only coexist in the same process with other services with a restricted SID type. If the service SID type for this service was just configured, the hosting process must be restarted in order to start this service.")
(register-error 1291 :ERROR_DRIVER_PROCESS_TERMINATED "The process hosting the driver for this device has been terminated.")
(register-error 1292 :ERROR_IMPLEMENTATION_LIMIT "An operation attempted to exceed an implementation-defined limit.")
(register-error 1293 :ERROR_PROCESS_IS_PROTECTED "Either the target process, or the target thread's containing process, is a protected process.")
(register-error 1294 :ERROR_SERVICE_NOTIFY_CLIENT_LAGGING "The service notification client is lagging too far behind the current state of services in the machine.")
(register-error 1295 :ERROR_DISK_QUOTA_EXCEEDED "The requested file operation failed because the storage quota was exceeded. To free up disk space, move files to a different location or delete unnecessary files. For more information, contact your system administrator.")
(register-error 1296 :ERROR_CONTENT_BLOCKED "The requested file operation failed because the storage policy blocks that type of file. For more information, contact your system administrator.")
(register-error 1297 :ERROR_INCOMPATIBLE_SERVICE_PRIVILEGE "A privilege that the service requires to function properly does not exist in the service account configuration. You may use the Services Microsoft Management Console (MMC) snap-in (services.msc) and the Local Security Settings MMC snap-in (secpol.msc) to view the service configuration and the account configuration.")
(register-error 1298 :ERROR_APP_HANG "A thread involved in this operation appears to be unresponsive.")
(register-error 1299 :ERROR_INVALID_LABEL "Indicates a particular Security ID may not be assigned as the label of an object.")
