;;;; src/rpc.lisp
;;;
;;; Contains Remote Procedure Call (RPC) and other system error codes.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; RPC Errors (1700-1938)
;;;--------------------------------------------------------------------------

(register-error 1700 :RPC_S_INVALID_STRING_BINDING "The string binding is invalid.")
(register-error 1701 :RPC_S_WRONG_KIND_OF_BINDING "The binding handle is not the correct type.")
(register-error 1702 :RPC_S_INVALID_BINDING "The binding handle is invalid.")
(register-error 1703 :RPC_S_PROTSEQ_NOT_SUPPORTED "The RPC protocol sequence is not supported.")
(register-error 1704 :RPC_S_INVALID_RPC_PROTSEQ "The RPC protocol sequence is invalid.")
(register-error 1705 :RPC_S_INVALID_STRING_UUID "The string universal unique identifier (UUID) is invalid.")
(register-error 1706 :RPC_S_INVALID_ENDPOINT_FORMAT "The endpoint format is invalid.")
(register-error 1707 :RPC_S_INVALID_NET_ADDR "The network address is invalid.")
(register-error 1708 :RPC_S_NO_ENDPOINT_FOUND "No endpoint was found.")
(register-error 1709 :RPC_S_INVALID_TIMEOUT "The timeout value is invalid.")
(register-error 1710 :RPC_S_OBJECT_NOT_FOUND "The object universal unique identifier (UUID) was not found.")
(register-error 1711 :RPC_S_ALREADY_REGISTERED "The object universal unique identifier (UUID) has already been registered.")
(register-error 1712 :RPC_S_TYPE_ALREADY_REGISTERED "The type universal unique identifier (UUID) has already been registered.")
(register-error 1713 :RPC_S_ALREADY_LISTENING "The RPC server is already listening.")
(register-error 1714 :RPC_S_NO_PROTSEQS_REGISTERED "No protocol sequences have been registered.")
(register-error 1715 :RPC_S_NOT_LISTENING "The RPC server is not listening.")
(register-error 1716 :RPC_S_UNKNOWN_MGR_TYPE "The manager type is unknown.")
(register-error 1717 :RPC_S_UNKNOWN_IF "The interface is unknown.")
(register-error 1718 :RPC_S_NO_BINDINGS "There are no bindings.")
(register-error 1719 :RPC_S_NO_PROTSEQS "There are no protocol sequences.")
(register-error 1720 :RPC_S_CANT_CREATE_ENDPOINT "The endpoint cannot be created.")
(register-error 1721 :RPC_S_OUT_OF_RESOURCES "Not enough resources are available to complete this operation.")
(register-error 1722 :RPC_S_SERVER_UNAVAILABLE "The RPC server is unavailable.")
(register-error 1723 :RPC_S_SERVER_TOO_BUSY "The RPC server is too busy to complete this operation.")
(register-error 1724 :RPC_S_INVALID_NETWORK_OPTIONS "The network options are invalid.")
(register-error 1725 :RPC_S_NO_CALL_ACTIVE "There are no remote procedure calls active on this thread.")
(register-error 1726 :RPC_S_CALL_FAILED "The remote procedure call failed.")
(register-error 1727 :RPC_S_CALL_FAILED_DNE "The remote procedure call failed and did not execute.")
(register-error 1728 :RPC_S_PROTOCOL_ERROR "A remote procedure call (RPC) protocol error occurred.")
(register-error 1729 :RPC_S_PROXY_ACCESS_DENIED "Access to the HTTP proxy is denied.")
(register-error 1730 :RPC_S_UNSUPPORTED_TRANS_SYN "The transfer syntax is not supported by the RPC server.")
(register-error 1732 :RPC_S_UNSUPPORTED_TYPE "The universal unique identifier (UUID) type is not supported.")
(register-error 1733 :RPC_S_INVALID_TAG "The tag is invalid.")
(register-error 1734 :RPC_S_INVALID_BOUND "The array bounds are invalid.")
(register-error 1735 :RPC_S_NO_ENTRY_NAME "The binding does not contain an entry name.")
(register-error 1736 :RPC_S_INVALID_NAME_SYNTAX "The name syntax is invalid.")
(register-error 1737 :RPC_S_UNSUPPORTED_NAME_SYNTAX "The name syntax is not supported.")
(register-error 1739 :RPC_S_UUID_NO_ADDRESS "No network address is available to use to construct a universal unique identifier (UUID).")
(register-error 1740 :RPC_S_DUPLICATE_ENDPOINT "The endpoint is a duplicate.")
(register-error 1741 :RPC_S_UNKNOWN_AUTHN_TYPE "The authentication type is unknown.")
(register-error 1742 :RPC_S_MAX_CALLS_TOO_SMALL "The maximum number of calls is too small.")
(register-error 1743 :RPC_S_STRING_TOO_LONG "The string is too long.")
(register-error 1744 :RPC_S_PROTSEQ_NOT_FOUND "The RPC protocol sequence was not found.")
(register-error 1745 :RPC_S_PROCNUM_OUT_OF_RANGE "The procedure number is out of range.")
(register-error 1746 :RPC_S_BINDING_HAS_NO_AUTH "The binding does not contain any authentication information.")
(register-error 1747 :RPC_S_UNKNOWN_AUTHN_SERVICE "The authentication service is unknown.")
(register-error 1748 :RPC_S_UNKNOWN_AUTHN_LEVEL "The authentication level is unknown.")
(register-error 1749 :RPC_S_INVALID_AUTH_IDENTITY "The security context is invalid.")
(register-error 1750 :RPC_S_UNKNOWN_AUTHZ_SERVICE "The authorization service is unknown.")
(register-error 1751 :EPT_S_INVALID_ENTRY "The entry is invalid.")
(register-error 1752 :EPT_S_CANT_PERFORM_OP "The server endpoint cannot perform the operation.")
(register-error 1753 :EPT_S_NOT_REGISTERED "There are no more endpoints available from the endpoint mapper.")
(register-error 1754 :RPC_S_NOTHING_TO_EXPORT "No interfaces have been exported.")
(register-error 1755 :RPC_S_INCOMPLETE_NAME "The entry name is incomplete.")
(register-error 1756 :RPC_S_INVALID_VERS_OPTION "The version option is invalid.")
(register-error 1757 :RPC_S_NO_MORE_MEMBERS "There are no more members.")
(register-error 1758 :RPC_S_NOT_ALL_OBJS_UNEXPORTED "There is nothing to unexport.")
(register-error 1759 :RPC_S_INTERFACE_NOT_FOUND "The interface was not found.")
(register-error 1760 :RPC_S_ENTRY_ALREADY_EXISTS "The entry already exists.")
(register-error 1761 :RPC_S_ENTRY_NOT_FOUND "The entry is not found.")
(register-error 1762 :RPC_S_NAME_SERVICE_UNAVAILABLE "The name service is unavailable.")
(register-error 1763 :RPC_S_INVALID_NAF_ID "The network address family is invalid.")
(register-error 1764 :RPC_S_CANNOT_SUPPORT "The requested operation is not supported.")
(register-error 1765 :RPC_S_NO_CONTEXT_AVAILABLE "No security context is available to allow impersonation.")
(register-error 1766 :RPC_S_INTERNAL_ERROR "An internal error occurred in a remote procedure call (RPC).")
(register-error 1767 :RPC_S_ZERO_DIVIDE "The RPC server attempted an integer division by zero.")
(register-error 1768 :RPC_S_ADDRESS_ERROR "An addressing error occurred in the RPC server.")
(register-error 1769 :RPC_S_FP_DIV_ZERO "A floating-point operation at the RPC server caused a division by zero.")
(register-error 1770 :RPC_S_FP_UNDERFLOW "A floating-point underflow occurred at the RPC server.")
(register-error 1771 :RPC_S_FP_OVERFLOW "A floating-point overflow occurred at the RPC server.")
(register-error 1772 :RPC_X_NO_MORE_ENTRIES "The list of RPC servers available for the binding of auto handles has been exhausted.")
(register-error 1773 :RPC_X_SS_CHAR_TRANS_OPEN_FAIL "Unable to open the character translation table file.")
(register-error 1774 :RPC_X_SS_CHAR_TRANS_SHORT_FILE "The file containing the character translation table has fewer than 512 bytes.")
(register-error 1775 :RPC_X_SS_IN_NULL_CONTEXT "A null context handle was passed from the client to the host during a remote procedure call.")
(register-error 1777 :RPC_X_SS_CONTEXT_DAMAGED "The context handle changed during a remote procedure call.")
(register-error 1778 :RPC_X_SS_HANDLES_MISMATCH "The binding handles passed to a remote procedure call do not match.")
(register-error 1779 :RPC_X_SS_CANNOT_GET_CALL_HANDLE "The stub is unable to get the remote procedure call handle.")
(register-error 1780 :RPC_X_NULL_REF_POINTER "A null reference pointer was passed to the stub.")
(register-error 1781 :RPC_X_ENUM_VALUE_OUT_OF_RANGE "The enumeration value is out of range.")
(register-error 1782 :RPC_X_BYTE_COUNT_TOO_SMALL "The byte count is too small.")
(register-error 1783 :RPC_X_BAD_STUB_DATA "The stub received bad data.")
(register-error 1784 :ERROR_INVALID_USER_BUFFER "The supplied user buffer is not valid for the requested operation.")
(register-error 1785 :ERROR_UNRECOGNIZED_MEDIA "The disk media is not recognized. It may not be formatted.")
(register-error 1786 :ERROR_NO_TRUST_LSA_SECRET "The workstation does not have a trust secret.")
(register-error 1787 :ERROR_NO_TRUST_SAM_ACCOUNT "The security database on the server does not have a computer account for this workstation trust relationship.")
(register-error 1788 :ERROR_TRUSTED_DOMAIN_FAILURE "The trust relationship between the primary domain and the trusted domain failed.")
(register-error 1789 :ERROR_TRUSTED_RELATIONSHIP_FAILURE "The trust relationship between this workstation and the primary domain failed.")
(register-error 1790 :ERROR_TRUST_FAILURE "The network logon failed.")
(register-error 1791 :RPC_S_CALL_IN_PROGRESS "A remote procedure call is already in progress for this thread.")
(register-error 1792 :ERROR_NETLOGON_NOT_STARTED "An attempt was made to logon, but the network logon service was not started.")
(register-error 1793 :ERROR_ACCOUNT_EXPIRED "The user's account has expired.")
(register-error 1794 :ERROR_REDIRECTOR_HAS_OPEN_HANDLES "The redirector is in use and cannot be unloaded.")
(register-error 1795 :ERROR_PRINTER_DRIVER_ALREADY_INSTALLED "The specified printer driver is already installed.")
(register-error 1796 :ERROR_UNKNOWN_PORT "The specified port is unknown.")
(register-error 1797 :ERROR_UNKNOWN_PRINTER_DRIVER "The printer driver is unknown.")
(register-error 1798 :ERROR_UNKNOWN_PRINTPROCESSOR "The print processor is unknown.")
(register-error 1799 :ERROR_INVALID_SEPARATOR_FILE "The specified separator file is invalid.")
(register-error 1800 :ERROR_INVALID_PRIORITY "The specified priority is invalid.")
(register-error 1801 :ERROR_INVALID_PRINTER_NAME "The printer name is invalid.")
(register-error 1802 :ERROR_PRINTER_ALREADY_EXISTS "The printer already exists.")
(register-error 1803 :ERROR_INVALID_PRINTER_COMMAND "The printer command is invalid.")
(register-error 1804 :ERROR_INVALID_DATATYPE "The specified datatype is invalid.")
(register-error 1805 :ERROR_INVALID_ENVIRONMENT "The environment specified is invalid.")
(register-error 1806 :RPC_S_NO_MORE_BINDINGS "There are no more bindings.")
(register-error 1807 :ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT "The account used is an interdomain trust account. Use your global user account or local user account to access this server.")
(register-error 1808 :ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT "The account used is a computer account. Use your global user account or local user account to access this server.")
(register-error 1809 :ERROR_NOLOGON_SERVER_TRUST_ACCOUNT "The account used is a server trust account. Use your global user account or local user account to access this server.")
(register-error 1810 :ERROR_DOMAIN_TRUST_INCONSISTENT "The name or security ID (SID) of the domain specified is inconsistent with the trust information for that domain.")
(register-error 1811 :ERROR_SERVER_HAS_OPEN_HANDLES "The server is in use and cannot be unloaded.")
(register-error 1812 :ERROR_RESOURCE_DATA_NOT_FOUND "The specified image file did not contain a resource section.")
(register-error 1813 :ERROR_RESOURCE_TYPE_NOT_FOUND "The specified resource type cannot be found in the image file.")
(register-error 1814 :ERROR_RESOURCE_NAME_NOT_FOUND "The specified resource name cannot be found in the image file.")
(register-error 1815 :ERROR_RESOURCE_LANG_NOT_FOUND "The specified resource language ID cannot be found in the image file.")
(register-error 1816 :ERROR_NOT_ENOUGH_QUOTA "Not enough quota is available to process this command.")
(register-error 1817 :RPC_S_NO_INTERFACES "No interfaces have been registered.")
(register-error 1818 :RPC_S_CALL_CANCELLED "The remote procedure call was cancelled.")
(register-error 1819 :RPC_S_BINDING_INCOMPLETE "The binding handle does not contain all required information.")
(register-error 1820 :RPC_S_COMM_FAILURE "A communications failure occurred during a remote procedure call.")
(register-error 1821 :RPC_S_UNSUPPORTED_AUTHN_LEVEL "The requested authentication level is not supported.")
(register-error 1822 :RPC_S_NO_PRINC_NAME "No principal name registered.")
(register-error 1823 :RPC_S_NOT_RPC_ERROR "The error specified is not a valid Windows RPC error code.")
(register-error 1824 :RPC_S_UUID_LOCAL_ONLY "A UUID that is valid only on this computer has been allocated.")
(register-error 1825 :RPC_S_SEC_PKG_ERROR "A security package specific error occurred.")
(register-error 1826 :RPC_S_NOT_CANCELLED "Thread is not canceled.")
(register-error 1827 :RPC_X_INVALID_ES_ACTION "Invalid operation on the encoding/decoding handle.")
(register-error 1828 :RPC_X_WRONG_ES_VERSION "Incompatible version of the serializing package.")
(register-error 1829 :RPC_X_WRONG_STUB_VERSION "Incompatible version of the RPC stub.")
(register-error 1830 :RPC_X_INVALID_PIPE_OBJECT "The RPC pipe object is invalid or corrupted.")
(register-error 1831 :RPC_X_WRONG_PIPE_ORDER "An invalid operation was attempted on an RPC pipe object.")
(register-error 1832 :RPC_X_WRONG_PIPE_VERSION "Unsupported RPC pipe version.")
(register-error 1833 :RPC_S_COOKIE_AUTH_FAILED "HTTP proxy server rejected the connection because the cookie authentication failed.")
(register-error 1898 :RPC_S_GROUP_MEMBER_NOT_FOUND "The group member was not found.")
(register-error 1899 :EPT_S_CANT_CREATE "The endpoint mapper database entry could not be created.")
(register-error 1900 :RPC_S_INVALID_OBJECT "The object universal unique identifier (UUID) is the nil UUID.")
(register-error 1901 :ERROR_INVALID_TIME "The specified time is invalid.")
(register-error 1902 :ERROR_INVALID_FORM_NAME "The specified form name is invalid.")
(register-error 1903 :ERROR_INVALID_FORM_SIZE "The specified form size is invalid.")
(register-error 1904 :ERROR_ALREADY_WAITING "The specified printer handle is already being waited on.")
(register-error 1905 :ERROR_PRINTER_DELETED "The specified printer has been deleted.")
(register-error 1906 :ERROR_INVALID_PRINTER_STATE "The state of the printer is invalid.")
(register-error 1907 :ERROR_PASSWORD_MUST_CHANGE "The user's password must be changed before signing in.")
(register-error 1908 :ERROR_DOMAIN_CONTROLLER_NOT_FOUND "Could not find the domain controller for this domain.")
(register-error 1909 :ERROR_ACCOUNT_LOCKED_OUT "The referenced account is currently locked out and may not be logged on to.")
(register-error 1910 :OR_INVALID_OXID "The object exporter specified was not found.")
(register-error 1911 :OR_INVALID_OID "The object specified was not found.")
(register-error 1912 :OR_INVALID_SET "The object resolver set specified was not found.")
(register-error 1913 :RPC_S_SEND_INCOMPLETE "Some data remains to be sent in the request buffer.")
(register-error 1914 :RPC_S_INVALID_ASYNC_HANDLE "Invalid asynchronous remote procedure call handle.")
(register-error 1915 :RPC_S_INVALID_ASYNC_CALL "Invalid asynchronous RPC call handle for this operation.")
(register-error 1916 :RPC_X_PIPE_CLOSED "The RPC pipe object has already been closed.")
(register-error 1917 :RPC_X_PIPE_DISCIPLINE_ERROR "The RPC call completed before all pipes were processed.")
(register-error 1918 :RPC_X_PIPE_EMPTY "No more data is available from the RPC pipe.")
(register-error 1919 :ERROR_NO_SITENAME "No site name is available for this machine.")
(register-error 1920 :ERROR_CANT_ACCESS_FILE "The file cannot be accessed by the system.")
(register-error 1921 :ERROR_CANT_RESOLVE_FILENAME "The name of the file cannot be resolved by the system.")
(register-error 1922 :RPC_S_ENTRY_TYPE_MISMATCH "The entry is not of the expected type.")
(register-error 1923 :RPC_S_NOT_ALL_OBJS_EXPORTED "Not all object UUIDs could be exported to the specified entry.")
(register-error 1924 :RPC_S_INTERFACE_NOT_EXPORTED "Interface could not be exported to the specified entry.")
(register-error 1925 :RPC_S_PROFILE_NOT_ADDED "The specified profile entry could not be added.")
(register-error 1926 :RPC_S_PRF_ELT_NOT_ADDED "The specified profile element could not be added.")
(register-error 1927 :RPC_S_PRF_ELT_NOT_REMOVED "The specified profile element could not be removed.")
(register-error 1928 :RPC_S_GRP_ELT_NOT_ADDED "The group element could not be added.")
(register-error 1929 :RPC_S_GRP_ELT_NOT_REMOVED "The group element could not be removed.")
(register-error 1930 :ERROR_KM_DRIVER_BLOCKED "The printer driver is not compatible with a policy enabled on your computer that blocks NT 4.0 drivers.")
(register-error 1931 :ERROR_CONTEXT_EXPIRED "The context has expired and can no longer be used.")
(register-error 1932 :ERROR_PER_USER_TRUST_QUOTA_EXCEEDED "The current user's delegated trust creation quota has been exceeded.")
(register-error 1933 :ERROR_ALL_USER_TRUST_QUOTA_EXCEEDED "The total delegated trust creation quota has been exceeded.")
(register-error 1934 :ERROR_USER_DELETE_TRUST_QUOTA_EXCEEDED "The current user's delegated trust deletion quota has been exceeded.")
(register-error 1935 :ERROR_AUTHENTICATION_FIREWALL_FAILED "The computer you are signing into is protected by an authentication firewall. The specified account is not allowed to authenticate to the computer.")
(register-error 1936 :ERROR_REMOTE_PRINT_CONNECTIONS_BLOCKED "Remote connections to the Print Spooler are blocked by a policy set on your machine.")
(register-error 1937 :ERROR_NTLM_BLOCKED "Authentication failed because NTLM authentication has been disabled.")
(register-error 1938 :ERROR_PASSWORD_CHANGE_REQUIRED "Logon Failure: EAS policy requires that the user change their password before this operation can be performed.")

;;;--------------------------------------------------------------------------
;;; Graphics and Display Errors (2000-2023)
;;;--------------------------------------------------------------------------

(register-error 2000 :ERROR_INVALID_PIXEL_FORMAT "The pixel format is invalid.")
(register-error 2001 :ERROR_BAD_DRIVER "The specified driver is invalid.")
(register-error 2002 :ERROR_INVALID_WINDOW_STYLE "The window style or class attribute is invalid for this operation.")
(register-error 2003 :ERROR_METAFILE_NOT_SUPPORTED "The requested metafile operation is not supported.")
(register-error 2004 :ERROR_TRANSFORM_NOT_SUPPORTED "The requested transformation operation is not supported.")
(register-error 2005 :ERROR_CLIPPING_NOT_SUPPORTED "The requested clipping operation is not supported.")
(register-error 2010 :ERROR_INVALID_CMM "The specified color management module is invalid.")
(register-error 2011 :ERROR_INVALID_PROFILE "The specified color profile is invalid.")
(register-error 2012 :ERROR_TAG_NOT_FOUND "The specified tag was not found.")
(register-error 2013 :ERROR_TAG_NOT_PRESENT "A required tag is not present.")
(register-error 2014 :ERROR_DUPLICATE_TAG "The specified tag is already present.")
(register-error 2015 :ERROR_PROFILE_NOT_ASSOCIATED_WITH_DEVICE "The specified color profile is not associated with the specified device.")
(register-error 2016 :ERROR_PROFILE_NOT_FOUND "The specified color profile was not found.")
(register-error 2017 :ERROR_INVALID_COLORSPACE "The specified color space is invalid.")
(register-error 2018 :ERROR_ICM_NOT_ENABLED "Image Color Management is not enabled.")
(register-error 2019 :ERROR_DELETING_ICM_XFORM "There was an error while deleting the color transform.")
(register-error 2020 :ERROR_INVALID_TRANSFORM "The specified color transform is invalid.")
(register-error 2021 :ERROR_COLORSPACE_MISMATCH "The specified transform does not match the bitmap's color space.")
(register-error 2022 :ERROR_INVALID_COLORINDEX "The specified named color index is not present in the profile.")
(register-error 2023 :ERROR_PROFILE_DOES_NOT_MATCH_DEVICE "The specified profile is intended for a device of a different type than the specified device.")

;;;--------------------------------------------------------------------------
;;; Network and Connection Errors (2108-2404)
;;;--------------------------------------------------------------------------

(register-error 2108 :ERROR_CONNECTED_OTHER_PASSWORD "The network connection was made successfully, but the user had to be prompted for a password other than the one originally specified.")
(register-error 2109 :ERROR_CONNECTED_OTHER_PASSWORD_DEFAULT "The network connection was made successfully using default credentials.")
(register-error 2202 :ERROR_BAD_USERNAME "The specified username is invalid.")
(register-error 2250 :ERROR_NOT_CONNECTED "This network connection does not exist.")
(register-error 2401 :ERROR_OPEN_FILES "This network connection has files open or requests pending.")
(register-error 2402 :ERROR_ACTIVE_CONNECTIONS "Active connections still exist.")
(register-error 2404 :ERROR_DEVICE_IN_USE "The device is in use by an active process and cannot be disconnected.")

;;;--------------------------------------------------------------------------
;;; Print Spooler Errors (3000-3022)
;;;--------------------------------------------------------------------------

(register-error 3000 :ERROR_UNKNOWN_PRINT_MONITOR "The specified print monitor is unknown.")
(register-error 3001 :ERROR_PRINTER_DRIVER_IN_USE "The specified printer driver is currently in use.")
(register-error 3002 :ERROR_SPOOL_FILE_NOT_FOUND "The spool file was not found.")
(register-error 3003 :ERROR_SPL_NO_STARTDOC "A StartDocPrinter call was not issued.")
(register-error 3004 :ERROR_SPL_NO_ADDJOB "An AddJob call was not issued.")
(register-error 3005 :ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED "The specified print processor has already been installed.")
(register-error 3006 :ERROR_PRINT_MONITOR_ALREADY_INSTALLED "The specified print monitor has already been installed.")
(register-error 3007 :ERROR_INVALID_PRINT_MONITOR "The specified print monitor does not have the required functions.")
(register-error 3008 :ERROR_PRINT_MONITOR_IN_USE "The specified print monitor is currently in use.")
(register-error 3009 :ERROR_PRINTER_HAS_JOBS_QUEUED "The requested operation is not allowed when there are jobs queued to the printer.")
(register-error 3010 :ERROR_SUCCESS_REBOOT_REQUIRED "The requested operation is successful. Changes will not be effective until the system is rebooted.")
(register-error 3011 :ERROR_SUCCESS_RESTART_REQUIRED "The requested operation is successful. Changes will not be effective until the service is restarted.")
(register-error 3012 :ERROR_PRINTER_NOT_FOUND "No printers were found.")
(register-error 3013 :ERROR_PRINTER_DRIVER_WARNED "The printer driver is known to be unreliable.")
(register-error 3014 :ERROR_PRINTER_DRIVER_BLOCKED "The printer driver is known to harm the system.")
(register-error 3015 :ERROR_PRINTER_DRIVER_PACKAGE_IN_USE "The specified printer driver package is currently in use.")
(register-error 3016 :ERROR_CORE_DRIVER_PACKAGE_NOT_FOUND "Unable to find a core driver package that is required by the printer driver package.")
(register-error 3017 :ERROR_FAIL_REBOOT_REQUIRED "The requested operation failed. A system reboot is required to roll back changes made.")
(register-error 3018 :ERROR_FAIL_REBOOT_INITIATED "The requested operation failed. A system reboot has been initiated to roll back changes made.")
(register-error 3019 :ERROR_PRINTER_DRIVER_DOWNLOAD_NEEDED "The specified printer driver was not found on the system and needs to be downloaded.")
(register-error 3020 :ERROR_PRINT_JOB_RESTART_REQUIRED "The requested print job has failed to print. A print system update requires the job to be resubmitted.")
(register-error 3021 :ERROR_INVALID_PRINTER_DRIVER_MANIFEST "The printer driver does not contain a valid manifest, or contains too many manifests.")
(register-error 3022 :ERROR_PRINTER_NOT_SHAREABLE "The specified printer cannot be shared.")

;;;--------------------------------------------------------------------------
;;; Miscellaneous Errors (3050-3950)
;;;--------------------------------------------------------------------------

(register-error 3050 :ERROR_REQUEST_PAUSED "The operation was paused.")
(register-error 3950 :ERROR_IO_REISSUE_AS_CACHED "Reissue the given operation as a cached IO operation.")

