;;;; src/security.lisp
;;;
;;; Contains security-related system error codes (LSA, SAM, etc.).

(in-package #:cl-win32-errors)

(register-error 1300 :ERROR_NOT_ALL_ASSIGNED "Not all privileges or groups referenced are assigned to the caller.")
(register-error 1301 :ERROR_SOME_NOT_MAPPED "Some mapping between account names and security IDs was not done.")
(register-error 1302 :ERROR_NO_QUOTAS_FOR_ACCOUNT "No system quota limits are specifically set for this account.")
(register-error 1303 :ERROR_LOCAL_USER_SESSION_KEY "No encryption key is available. A well-known encryption key was returned.")
(register-error 1304 :ERROR_NULL_LM_PASSWORD "The password is too complex to be converted to a LAN Manager password. The LAN Manager password returned is a NULL string.")
(register-error 1305 :ERROR_UNKNOWN_REVISION "The revision level is unknown.")
(register-error 1306 :ERROR_REVISION_MISMATCH "Indicates two revision levels are incompatible.")
(register-error 1307 :ERROR_INVALID_OWNER "This security ID may not be assigned as the owner of this object.")
(register-error 1308 :ERROR_INVALID_PRIMARY_GROUP "This security ID may not be assigned as the primary group of an object.")
(register-error 1309 :ERROR_NO_IMPERSONATION_TOKEN "An attempt has been made to operate on an impersonation token by a thread that is not currently impersonating a client.")
(register-error 1310 :ERROR_CANT_DISABLE_MANDATORY "The group may not be disabled.")
(register-error 1311 :ERROR_NO_LOGON_SERVERS "There are currently no logon servers available to service the logon request.")
(register-error 1312 :ERROR_NO_SUCH_LOGON_SESSION "A specified logon session does not exist. It may already have been terminated.")
(register-error 1313 :ERROR_NO_SUCH_PRIVILEGE "A specified privilege does not exist.")
(register-error 1314 :ERROR_PRIVILEGE_NOT_HELD "A required privilege is not held by the client.")
(register-error 1315 :ERROR_INVALID_ACCOUNT_NAME "The name provided is not a properly formed account name.")
(register-error 1316 :ERROR_USER_EXISTS "The specified account already exists.")
(register-error 1317 :ERROR_NO_SUCH_USER "The specified account does not exist.")
(register-error 1318 :ERROR_GROUP_EXISTS "The specified group already exists.")
(register-error 1319 :ERROR_NO_SUCH_GROUP "The specified group does not exist.")
(register-error 1320 :ERROR_MEMBER_IN_GROUP "Either the specified user account is already a member of the specified group, or the specified group cannot be deleted because it contains a member.")
(register-error 1321 :ERROR_MEMBER_NOT_IN_GROUP "The specified user account is not a member of the specified group account.")
(register-error 1322 :ERROR_LAST_ADMIN "This operation is disallowed as it could result in an administration account being disabled, deleted or unable to log on.")
(register-error 1323 :ERROR_WRONG_PASSWORD "Unable to update the password. The value provided as the current password is incorrect.")
(register-error 1324 :ERROR_ILL_FORMED_PASSWORD "Unable to update the password. The value provided for the new password contains values that are not allowed in passwords.")
(register-error 1325 :ERROR_PASSWORD_RESTRICTION "Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain.")
(register-error 1326 :ERROR_LOGON_FAILURE "The user name or password is incorrect.")
(register-error 1327 :ERROR_ACCOUNT_RESTRICTION "Account restrictions are preventing this user from signing in. For example: blank passwords aren't allowed, sign-in times are limited, or a policy restriction has been enforced.")
(register-error 1328 :ERROR_INVALID_LOGON_HOURS "Your account has time restrictions that keep you from signing in right now.")
(register-error 1329 :ERROR_INVALID_WORKSTATION "This user isn't allowed to sign in to this computer.")
(register-error 1330 :ERROR_PASSWORD_EXPIRED "The password for this account has expired.")
(register-error 1331 :ERROR_ACCOUNT_DISABLED "This user can't sign in because this account is currently disabled.")
(register-error 1332 :ERROR_NONE_MAPPED "No mapping between account names and security IDs was done.")
(register-error 1333 :ERROR_TOO_MANY_LUIDS_REQUESTED "Too many local user identifiers (LUIDs) were requested at one time.")
(register-error 1334 :ERROR_LUIDS_EXHAUSTED "No more local user identifiers (LUIDs) are available.")
(register-error 1335 :ERROR_INVALID_SUB_AUTHORITY "The subauthority part of a security ID is invalid for this particular use.")
(register-error 1336 :ERROR_INVALID_ACL "The access control list (ACL) structure is invalid.")
(register-error 1337 :ERROR_INVALID_SID "The security ID structure is invalid.")
(register-error 1338 :ERROR_INVALID_SECURITY_DESCR "The security descriptor structure is invalid.")
(register-error 1340 :ERROR_BAD_INHERITANCE_ACL "The inherited access control list (ACL) or access control entry (ACE) could not be built.")
(register-error 1341 :ERROR_SERVER_DISABLED "The server is currently disabled.")
(register-error 1342 :ERROR_SERVER_NOT_DISABLED "The server is currently enabled.")
(register-error 1343 :ERROR_INVALID_ID_AUTHORITY "The value provided was an invalid value for an identifier authority.")
(register-error 1344 :ERROR_ALLOTTED_SPACE_EXCEEDED "No more memory is available for security information updates.")
(register-error 1345 :ERROR_INVALID_GROUP_ATTRIBUTES "The specified attributes are invalid, or incompatible with the attributes for the group as a whole.")
(register-error 1346 :ERROR_BAD_IMPERSONATION_LEVEL "Either a required impersonation level was not provided, or the provided impersonation level is invalid.")
(register-error 1347 :ERROR_CANT_OPEN_ANONYMOUS "Cannot open an anonymous level security token.")
(register-error 1348 :ERROR_BAD_VALIDATION_CLASS "The validation information class requested was invalid.")
(register-error 1349 :ERROR_BAD_TOKEN_TYPE "The type of the token is inappropriate for its attempted use.")
(register-error 1350 :ERROR_NO_SECURITY_ON_OBJECT "Unable to perform a security operation on an object that has no associated security.")
(register-error 1351 :ERROR_CANT_ACCESS_DOMAIN_INFO "Configuration information could not be read from the domain controller, either because the machine is unavailable, or access has been denied.")
(register-error 1352 :ERROR_INVALID_SERVER_STATE "The security account manager (SAM) or local security authority (LSA) server was in the wrong state to perform the security operation.")
(register-error 1353 :ERROR_INVALID_DOMAIN_STATE "The domain was in the wrong state to perform the security operation.")
(register-error 1354 :ERROR_INVALID_DOMAIN_ROLE "This operation is only allowed for the Primary Domain Controller of the domain.")
(register-error 1355 :ERROR_NO_SUCH_DOMAIN "The specified domain either does not exist or could not be contacted.")
(register-error 1356 :ERROR_DOMAIN_EXISTS "The specified domain already exists.")
(register-error 1357 :ERROR_DOMAIN_LIMIT_EXCEEDED "An attempt was made to exceed the limit on the number of domains per server.")
(register-error 1358 :ERROR_INTERNAL_DB_CORRUPTION "Unable to complete the requested operation because of either a catastrophic media failure or a data structure corruption on the disk.")
(register-error 1359 :ERROR_INTERNAL_ERROR "An internal error occurred.")
(register-error 1360 :ERROR_GENERIC_NOT_MAPPED "Generic access types were contained in an access mask which should already be mapped to nongeneric types.")
(register-error 1361 :ERROR_BAD_DESCRIPTOR_FORMAT "A security descriptor is not in the right format (absolute or self-relative).")
(register-error 1362 :ERROR_NOT_LOGON_PROCESS "The requested action is restricted for use by logon processes only. The calling process has not registered as a logon process.")
(register-error 1363 :ERROR_LOGON_SESSION_EXISTS "Cannot start a new logon session with an ID that is already in use.")
(register-error 1364 :ERROR_NO_SUCH_PACKAGE "A specified authentication package is unknown.")
(register-error 1365 :ERROR_BAD_LOGON_SESSION_STATE "The logon session is not in a state that is consistent with the requested operation.")
(register-error 1366 :ERROR_LOGON_SESSION_COLLISION "The logon session ID is already in use.")
(register-error 1367 :ERROR_INVALID_LOGON_TYPE "A logon request contained an invalid logon type value.")
(register-error 1368 :ERROR_CANNOT_IMPERSONATE "Unable to impersonate using a named pipe until data has been read from that pipe.")
(register-error 1369 :ERROR_RXACT_INVALID_STATE "The transaction state of a registry subtree is incompatible with the requested operation.")
(register-error 1370 :ERROR_RXACT_COMMIT_FAILURE "An internal security database corruption has been encountered.")
(register-error 1371 :ERROR_SPECIAL_ACCOUNT "Cannot perform this operation on built-in accounts.")
(register-error 1372 :ERROR_SPECIAL_GROUP "Cannot perform this operation on this built-in special group.")
(register-error 1373 :ERROR_SPECIAL_USER "Cannot perform this operation on this built-in special user.")
(register-error 1374 :ERROR_MEMBERS_PRIMARY_GROUP "The user cannot be removed from a group because the group is currently the user's primary group.")
(register-error 1375 :ERROR_TOKEN_ALREADY_IN_USE "The token is already in use as a primary token.")
(register-error 1376 :ERROR_NO_SUCH_ALIAS "The specified local group does not exist.")
(register-error 1377 :ERROR_MEMBER_NOT_IN_ALIAS "The specified account name is not a member of the group.")
(register-error 1378 :ERROR_MEMBER_IN_ALIAS "The specified account name is already a member of the group.")
(register-error 1379 :ERROR_ALIAS_EXISTS "The specified local group already exists.")
(register-error 1380 :ERROR_LOGON_NOT_GRANTED "Logon failure: the user has not been granted the requested logon type at this computer.")
(register-error 1381 :ERROR_TOO_MANY_SECRETS "The maximum number of secrets that may be stored in a single system has been exceeded.")
(register-error 1382 :ERROR_SECRET_TOO_LONG "The length of a secret exceeds the maximum length allowed.")
(register-error 1383 :ERROR_INTERNAL_DB_ERROR "The local security authority database contains an internal inconsistency.")
(register-error 1384 :ERROR_TOO_MANY_CONTEXT_IDS "During a logon attempt, the user's security context accumulated too many security IDs.")
(register-error 1385 :ERROR_LOGON_TYPE_NOT_GRANTED "Logon failure: the user has not been granted the requested logon type at this computer.")
(register-error 1386 :ERROR_NT_CROSS_ENCRYPTION_REQUIRED "A cross-encrypted password is necessary to change a user password.")
(register-error 1387 :ERROR_NO_SUCH_MEMBER "A member could not be added to or removed from the local group because the member does not exist.")
(register-error 1388 :ERROR_INVALID_MEMBER "A new member could not be added to a local group because the member has the wrong account type.")
(register-error 1389 :ERROR_TOO_MANY_SIDS "Too many security IDs have been specified.")
(register-error 1390 :ERROR_LM_CROSS_ENCRYPTION_REQUIRED "A cross-encrypted password is necessary to change this user password.")
(register-error 1391 :ERROR_NO_INHERITANCE "Indicates an ACL contains no inheritable components.")
(register-error 1392 :ERROR_FILE_CORRUPT "The file or directory is corrupted and unreadable.")
(register-error 1393 :ERROR_DISK_CORRUPT "The disk structure is corrupted and unreadable.")
(register-error 1394 :ERROR_NO_USER_SESSION_KEY "There is no user session key for the specified logon session.")
(register-error 1395 :ERROR_LICENSE_QUOTA_EXCEEDED "The service being accessed is licensed for a particular number of connections. No more connections can be made to the service at this time because there are already as many connections as the service can accept.")
(register-error 1396 :ERROR_WRONG_TARGET_NAME "The target account name is incorrect.")
(register-error 1397 :ERROR_MUTUAL_AUTH_FAILED "Mutual Authentication failed. The server's password is out of date at the domain controller.")
(register-error 1398 :ERROR_TIME_SKEW "There is a time and/or date difference between the client and server.")
(register-error 1399 :ERROR_CURRENT_DOMAIN_NOT_ALLOWED "This operation cannot be performed on the current domain.")
