;;;; src/transactional.lisp
;;;
;;; Contains error codes for the Kernel Transaction Manager (KTM),
;;; Transactional NTFS (TxF), and the Common Log File System (CLFS).

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; Common Log File System (CLFS) Errors (6600-6648)
;;;--------------------------------------------------------------------------

(register-error 6600 :ERROR_LOG_SECTOR_INVALID "Log service encountered an invalid log sector.")
(register-error 6601 :ERROR_LOG_SECTOR_PARITY_INVALID "Log service encountered a log sector with invalid block parity.")
(register-error 6602 :ERROR_LOG_SECTOR_REMAPPED "Log service encountered a remapped log sector.")
(register-error 6603 :ERROR_LOG_BLOCK_INCOMPLETE "Log service encountered a partial or incomplete log block.")
(register-error 6604 :ERROR_LOG_INVALID_RANGE "Log service encountered an attempt access data outside the active log range.")
(register-error 6605 :ERROR_LOG_BLOCKS_EXHAUSTED "Log service user marshalling buffers are exhausted.")
(register-error 6606 :ERROR_LOG_READ_CONTEXT_INVALID "Log service encountered an attempt read from a marshalling area with an invalid read context.")
(register-error 6607 :ERROR_LOG_RESTART_INVALID "Log service encountered an invalid log restart area.")
(register-error 6608 :ERROR_LOG_BLOCK_VERSION "Log service encountered an invalid log block version.")
(register-error 6609 :ERROR_LOG_BLOCK_INVALID "Log service encountered an invalid log block.")
(register-error 6610 :ERROR_LOG_READ_MODE_INVALID "Log service encountered an attempt to read the log with an invalid read mode.")
(register-error 6611 :ERROR_LOG_NO_RESTART "Log service encountered a log stream with no restart area.")
(register-error 6612 :ERROR_LOG_METADATA_CORRUPT "Log service encountered a corrupted metadata file.")
(register-error 6613 :ERROR_LOG_METADATA_INVALID "Log service encountered a metadata file that could not be created by the log file system.")
(register-error 6614 :ERROR_LOG_METADATA_INCONSISTENT "Log service encountered a metadata file with inconsistent data.")
(register-error 6615 :ERROR_LOG_RESERVATION_INVALID "Log service encountered an attempt to erroneous allocate or dispose reservation space.")
(register-error 6616 :ERROR_LOG_CANT_DELETE "Log service cannot delete log file or file system container.")
(register-error 6617 :ERROR_LOG_CONTAINER_LIMIT_EXCEEDED "Log service has reached the maximum allowable containers allocated to a log file.")
(register-error 6618 :ERROR_LOG_START_OF_LOG "Log service has attempted to read or write backward past the start of the log.")
(register-error 6619 :ERROR_LOG_POLICY_ALREADY_INSTALLED "Log policy could not be installed because a policy of the same type is already present.")
(register-error 6620 :ERROR_LOG_POLICY_NOT_INSTALLED "Log policy in question was not installed at the time of the request.")
(register-error 6621 :ERROR_LOG_POLICY_INVALID "The installed set of policies on the log is invalid.")
(register-error 6622 :ERROR_LOG_POLICY_CONFLICT "A policy on the log in question prevented the operation from completing.")
(register-error 6623 :ERROR_LOG_PINNED_ARCHIVE_TAIL "Log space cannot be reclaimed because the log is pinned by the archive tail.")
(register-error 6624 :ERROR_LOG_RECORD_NONEXISTENT "Log record is not a record in the log file.")
(register-error 6625 :ERROR_LOG_RECORDS_RESERVED_INVALID "Number of reserved log records or the adjustment of the number of reserved log records is invalid.")
(register-error 6626 :ERROR_LOG_SPACE_RESERVED_INVALID "Reserved log space or the adjustment of the log space is invalid.")
(register-error 6627 :ERROR_LOG_TAIL_INVALID "An new or existing archive tail or base of the active log is invalid.")
(register-error 6628 :ERROR_LOG_FULL "Log space is exhausted.")
(register-error 6629 :ERROR_COULD_NOT_RESIZE_LOG "The log could not be set to the requested size.")
(register-error 6630 :ERROR_LOG_MULTIPLEXED "Log is multiplexed, no direct writes to the physical log is allowed.")
(register-error 6631 :ERROR_LOG_DEDICATED "The operation failed because the log is a dedicated log.")
(register-error 6632 :ERROR_LOG_ARCHIVE_NOT_IN_PROGRESS "The operation requires an archive context.")
(register-error 6633 :ERROR_LOG_ARCHIVE_IN_PROGRESS "Log archival is in progress.")
(register-error 6634 :ERROR_LOG_EPHEMERAL "The operation requires a non-ephemeral log, but the log is ephemeral.")
(register-error 6635 :ERROR_LOG_NOT_ENOUGH_CONTAINERS "The log must have at least two containers before it can be read from or written to.")
(register-error 6636 :ERROR_LOG_CLIENT_ALREADY_REGISTERED "A log client has already registered on the stream.")
(register-error 6637 :ERROR_LOG_CLIENT_NOT_REGISTERED "A log client has not been registered on the stream.")
(register-error 6638 :ERROR_LOG_FULL_HANDLER_IN_PROGRESS "A request has already been made to handle the log full condition.")
(register-error 6639 :ERROR_LOG_CONTAINER_READ_FAILED "Log service encountered an error when attempting to read from a log container.")
(register-error 6640 :ERROR_LOG_CONTAINER_WRITE_FAILED "Log service encountered an error when attempting to write to a log container.")
(register-error 6641 :ERROR_LOG_CONTAINER_OPEN_FAILED "Log service encountered an error when attempting open a log container.")
(register-error 6642 :ERROR_LOG_CONTAINER_STATE_INVALID "Log service encountered an invalid container state when attempting a requested action.")
(register-error 6643 :ERROR_LOG_STATE_INVALID "Log service is not in the correct state to perform a requested action.")
(register-error 6644 :ERROR_LOG_PINNED "Log space cannot be reclaimed because the log is pinned.")
(register-error 6645 :ERROR_LOG_METADATA_FLUSH_FAILED "Log metadata flush failed.")
(register-error 6646 :ERROR_LOG_INCONSISTENT_SECURITY "Security on the log and its containers is inconsistent.")
(register-error 6647 :ERROR_LOG_APPENDED_FLUSH_FAILED "Records were appended to the log or reservation changes were made, but the log could not be flushed.")
(register-error 6648 :ERROR_LOG_PINNED_RESERVATION "The log is pinned due to reservation consuming most of the log space. Free some reserved records to make space available.")

;;;--------------------------------------------------------------------------
;;; Kernel Transaction Manager (KTM) and Transactional NTFS (TxF) Errors (6700-6855)
;;;--------------------------------------------------------------------------

(register-error 6700 :ERROR_INVALID_TRANSACTION "The transaction handle associated with this operation is not valid.")
(register-error 6701 :ERROR_TRANSACTION_NOT_ACTIVE "The requested operation was made in the context of a transaction that is no longer active.")
(register-error 6702 :ERROR_TRANSACTION_REQUEST_NOT_VALID "The requested operation is not valid on the Transaction object in its current state.")
(register-error 6703 :ERROR_TRANSACTION_NOT_REQUESTED "The caller has called a response API, but the response is not expected because the TM did not issue the corresponding request to the caller.")
(register-error 6704 :ERROR_TRANSACTION_ALREADY_ABORTED "It is too late to perform the requested operation, since the Transaction has already been aborted.")
(register-error 6705 :ERROR_TRANSACTION_ALREADY_COMMITTED "It is too late to perform the requested operation, since the Transaction has already been committed.")
(register-error 6706 :ERROR_TM_INITIALIZATION_FAILED "The Transaction Manager was unable to be successfully initialized. Transacted operations are not supported.")
(register-error 6707 :ERROR_RESOURCEMANAGER_READ_ONLY "The specified ResourceManager made no changes or updates to the resource under this transaction.")
(register-error 6708 :ERROR_TRANSACTION_NOT_JOINED "The resource manager has attempted to prepare a transaction that it has not successfully joined.")
(register-error 6709 :ERROR_TRANSACTION_SUPERIOR_EXISTS "The Transaction object already has a superior enlistment, and the caller attempted an operation that would have created a new superior. Only a single superior enlistment is allow.")
(register-error 6710 :ERROR_CRM_PROTOCOL_ALREADY_EXISTS "The RM tried to register a protocol that already exists.")
(register-error 6711 :ERROR_TRANSACTION_PROPAGATION_FAILED "The attempt to propagate the Transaction failed.")
(register-error 6712 :ERROR_CRM_PROTOCOL_NOT_FOUND "The requested propagation protocol was not registered as a CRM.")
(register-error 6713 :ERROR_TRANSACTION_INVALID_MARSHALL_BUFFER "The buffer passed in to PushTransaction or PullTransaction is not in a valid format.")
(register-error 6714 :ERROR_CURRENT_TRANSACTION_NOT_VALID "The current transaction context associated with the thread is not a valid handle to a transaction object.")
(register-error 6715 :ERROR_TRANSACTION_NOT_FOUND "The specified Transaction object could not be opened, because it was not found.")
(register-error 6716 :ERROR_RESOURCEMANAGER_NOT_FOUND "The specified ResourceManager object could not be opened, because it was not found.")
(register-error 6717 :ERROR_ENLISTMENT_NOT_FOUND "The specified Enlistment object could not be opened, because it was not found.")
(register-error 6718 :ERROR_TRANSACTIONMANAGER_NOT_FOUND "The specified TransactionManager object could not be opened, because it was not found.")
(register-error 6719 :ERROR_TRANSACTIONMANAGER_NOT_ONLINE "The object specified could not be created or opened, because its associated TransactionManager is not online. The TransactionManager must be brought fully Online by calling RecoverTransactionManager to recover to the end of its LogFile before objects in its Transaction or ResourceManager namespaces can be opened. In addition, errors in writing records to its LogFile can cause a TransactionManager to go offline.")
(register-error 6720 :ERROR_TRANSACTIONMANAGER_RECOVERY_NAME_COLLISION "The specified TransactionManager was unable to create the objects contained in its logfile in the Ob namespace. Therefore, the TransactionManager was unable to recover.")
(register-error 6721 :ERROR_TRANSACTION_NOT_ROOT "The call to create a superior Enlistment on this Transaction object could not be completed, because the Transaction object specified for the enlistment is a subordinate branch of the Transaction. Only the root of the Transaction can be enlisted on as a superior.")
(register-error 6722 :ERROR_TRANSACTION_OBJECT_EXPIRED "Because the associated transaction manager or resource manager has been closed, the handle is no longer valid.")
(register-error 6723 :ERROR_TRANSACTION_RESPONSE_NOT_ENLISTED "The specified operation could not be performed on this Superior enlistment, because the enlistment was not created with the corresponding completion response in the NotificationMask.")
(register-error 6724 :ERROR_TRANSACTION_RECORD_TOO_LONG "The specified operation could not be performed, because the record that would be logged was too long. This can occur because of two conditions: either there are too many Enlistments on this Transaction, or the combined RecoveryInformation being logged on behalf of those Enlistments is too long.")
(register-error 6725 :ERROR_IMPLICIT_TRANSACTION_NOT_SUPPORTED "Implicit transaction are not supported.")
(register-error 6726 :ERROR_TRANSACTION_INTEGRITY_VIOLATED "The kernel transaction manager had to abort or forget the transaction because it blocked forward progress.")
(register-error 6727 :ERROR_TRANSACTIONMANAGER_IDENTITY_MISMATCH "The TransactionManager identity that was supplied did not match the one recorded in the TransactionManager's log file.")
(register-error 6728 :ERROR_RM_CANNOT_BE_FROZEN_FOR_SNAPSHOT "This snapshot operation cannot continue because a transactional resource manager cannot be frozen in its current state. Please try again.")
(register-error 6729 :ERROR_TRANSACTION_MUST_WRITETHROUGH "The transaction cannot be enlisted on with the specified EnlistmentMask, because the transaction has already completed the PrePrepare phase. In order to ensure correctness, the ResourceManager must switch to a write- through mode and cease caching data within this transaction. Enlisting for only subsequent transaction phases may still succeed.")
(register-error 6730 :ERROR_TRANSACTION_NO_SUPERIOR "The transaction does not have a superior enlistment.")
(register-error 6731 :ERROR_HEURISTIC_DAMAGE_POSSIBLE "The attempt to commit the Transaction completed, but it is possible that some portion of the transaction tree did not commit successfully due to heuristics. Therefore it is possible that some data modified in the transaction may not have committed, resulting in transactional inconsistency. If possible, check the consistency of the associated data.")
(register-error 6800 :ERROR_TRANSACTIONAL_CONFLICT "The function attempted to use a name that is reserved for use by another transaction.")
(register-error 6801 :ERROR_RM_NOT_ACTIVE "Transaction support within the specified resource manager is not started or was shut down due to an error.")
(register-error 6802 :ERROR_RM_METADATA_CORRUPT "The metadata of the RM has been corrupted. The RM will not function.")
(register-error 6803 :ERROR_DIRECTORY_NOT_RM "The specified directory does not contain a resource manager.")
(register-error 6805 :ERROR_TRANSACTIONS_UNSUPPORTED_REMOTE "The remote server or share does not support transacted file operations.")
(register-error 6806 :ERROR_LOG_RESIZE_INVALID_SIZE "The requested log size is invalid.")
(register-error 6807 :ERROR_OBJECT_NO_LONGER_EXISTS "The object (file, stream, link) corresponding to the handle has been deleted by a Transaction Savepoint Rollback.")
(register-error 6808 :ERROR_STREAM_MINIVERSION_NOT_FOUND "The specified file miniversion was not found for this transacted file open.")
(register-error 6809 :ERROR_STREAM_MINIVERSION_NOT_VALID "The specified file miniversion was found but has been invalidated. Most likely cause is a transaction savepoint rollback.")
(register-error 6810 :ERROR_MINIVERSION_INACCESSIBLE_FROM_SPECIFIED_TRANSACTION "A miniversion may only be opened in the context of the transaction that created it.")
(register-error 6811 :ERROR_CANT_OPEN_MINIVERSION_WITH_MODIFY_INTENT "It is not possible to open a miniversion with modify access.")
(register-error 6812 :ERROR_CANT_CREATE_MORE_STREAM_MINIVERSIONS "It is not possible to create any more miniversions for this stream.")
(register-error 6814 :ERROR_REMOTE_FILE_VERSION_MISMATCH "The remote server sent mismatching version number or Fid for a file opened with transactions.")
(register-error 6815 :ERROR_HANDLE_NO_LONGER_VALID "The handle has been invalidated by a transaction. The most likely cause is the presence of memory mapping on a file or an open handle when the transaction ended or rolled back to savepoint.")
(register-error 6816 :ERROR_NO_TXF_METADATA "There is no transaction metadata on the file.")
(register-error 6817 :ERROR_LOG_CORRUPTION_DETECTED "The log data is corrupt.")
(register-error 6818 :ERROR_CANT_RECOVER_WITH_HANDLE_OPEN "The file can't be recovered because there is a handle still open on it.")
(register-error 6819 :ERROR_RM_DISCONNECTED "The transaction outcome is unavailable because the resource manager responsible for it has disconnected.")
(register-error 6820 :ERROR_ENLISTMENT_NOT_SUPERIOR "The request was rejected because the enlistment in question is not a superior enlistment.")
(register-error 6821 :ERROR_RECOVERY_NOT_NEEDED "The transactional resource manager is already consistent. Recovery is not needed.")
(register-error 6822 :ERROR_RM_ALREADY_STARTED "The transactional resource manager has already been started.")
(register-error 6823 :ERROR_FILE_IDENTITY_NOT_PERSISTENT "The file cannot be opened transactionally, because its identity depends on the outcome of an unresolved transaction.")
(register-error 6824 :ERROR_CANT_BREAK_TRANSACTIONAL_DEPENDENCY "The operation cannot be performed because another transaction is depending on the fact that this property will not change.")
(register-error 6825 :ERROR_CANT_CROSS_RM_BOUNDARY "The operation would involve a single file with two transactional resource managers and is therefore not allowed.")
(register-error 6826 :ERROR_TXF_DIR_NOT_EMPTY "The $Txf directory must be empty for this operation to succeed.")
(register-error 6827 :ERROR_INDOUBT_TRANSACTIONS_EXIST "The operation would leave a transactional resource manager in an inconsistent state and is therefore not allowed.")
(register-error 6828 :ERROR_TM_VOLATILE "The operation could not be completed because the transaction manager does not have a log.")
(register-error 6829 :ERROR_ROLLBACK_TIMER_EXPIRED "A rollback could not be scheduled because a previously scheduled rollback has already executed or been queued for execution.")
(register-error 6830 :ERROR_TXF_ATTRIBUTE_CORRUPT "The transactional metadata attribute on the file or directory is corrupt and unreadable.")
(register-error 6831 :ERROR_EFS_NOT_ALLOWED_IN_TRANSACTION "The encryption operation could not be completed because a transaction is active.")
(register-error 6832 :ERROR_TRANSACTIONAL_OPEN_NOT_ALLOWED "This object is not allowed to be opened in a transaction.")
(register-error 6833 :ERROR_LOG_GROWTH_FAILED "An attempt to create space in the transactional resource manager's log failed. The failure status has been recorded in the event log.")
(register-error 6834 :ERROR_TRANSACTED_MAPPING_UNSUPPORTED_REMOTE "Memory mapping (creating a mapped section) a remote file under a transaction is not supported.")
(register-error 6835 :ERROR_TXF_METADATA_ALREADY_PRESENT "Transaction metadata is already present on this file and cannot be superseded.")
(register-error 6836 :ERROR_TRANSACTION_SCOPE_CALLBACKS_NOT_SET "A transaction scope could not be entered because the scope handler has not been initialized.")
(register-error 6837 :ERROR_TRANSACTION_REQUIRED_PROMOTION "Promotion was required in order to allow the resource manager to enlist, but the transaction was set to disallow it.")
(register-error 6838 :ERROR_CANNOT_EXECUTE_FILE_IN_TRANSACTION "This file is open for modification in an unresolved transaction and may be opened for execute only by a transacted reader.")
(register-error 6839 :ERROR_TRANSACTIONS_NOT_FROZEN "The request to thaw frozen transactions was ignored because transactions had not previously been frozen.")
(register-error 6840 :ERROR_TRANSACTION_FREEZE_IN_PROGRESS "Transactions cannot be frozen because a freeze is already in progress.")
(register-error 6841 :ERROR_NOT_SNAPSHOT_VOLUME "The target volume is not a snapshot volume. This operation is only valid on a volume mounted as a snapshot.")
(register-error 6842 :ERROR_NO_SAVEPOINT_WITH_OPEN_FILES "The savepoint operation failed because files are open on the transaction. This is not permitted.")
(register-error 6843 :ERROR_DATA_LOST_REPAIR "Windows has discovered corruption in a file, and that file has since been repaired. Data loss may have occurred.")
(register-error 6844 :ERROR_SPARSE_NOT_ALLOWED_IN_TRANSACTION "The sparse operation could not be completed because a transaction is active on the file.")
(register-error 6845 :ERROR_TM_IDENTITY_MISMATCH "The call to create a TransactionManager object failed because the Tm Identity stored in the logfile does not match the Tm Identity that was passed in as an argument.")
(register-error 6846 :ERROR_FLOATED_SECTION "I/O was attempted on a section object that has been floated as a result of a transaction ending. There is no valid data.")
(register-error 6847 :ERROR_CANNOT_ACCEPT_TRANSACTED_WORK "The transactional resource manager cannot currently accept transacted work due to a transient condition such as low resources.")
(register-error 6848 :ERROR_CANNOT_ABORT_TRANSACTIONS "The transactional resource manager had too many transactions outstanding that could not be aborted. The transactional resource manger has been shut down.")
(register-error 6849 :ERROR_BAD_CLUSTERS "The operation could not be completed due to bad clusters on disk.")
(register-error 6850 :ERROR_COMPRESSION_NOT_ALLOWED_IN_TRANSACTION "The compression operation could not be completed because a transaction is active on the file.")
(register-error 6851 :ERROR_VOLUME_DIRTY "The operation could not be completed because the volume is dirty. Please run chkdsk and try again.")
(register-error 6852 :ERROR_NO_LINK_TRACKING_IN_TRANSACTION "The link tracking operation could not be completed because a transaction is active.")
(register-error 6853 :ERROR_OPERATION_NOT_SUPPORTED_IN_TRANSACTION "This operation cannot be performed in a transaction.")
(register-error 6854 :ERROR_EXPIRED_HANDLE "The handle is no longer properly associated with its transaction. It may have been opened in a transactional resource manager that was subsequently forced to restart. Please close the handle and open a new one.")
(register-error 6855 :ERROR_TRANSACTION_NOT_ENLISTED "The specified operation could not be performed because the resource manager is not enlisted in the transaction.")

