;;;; src/winsock.lisp
;;;
;;; Contains Windows Sockets (Winsock) related error codes.

(in-package #:cl-win32-errors)

;;;--------------------------------------------------------------------------
;;; Windows Sockets (Winsock) Errors (10004-11033)
;;;--------------------------------------------------------------------------

(register-error 10004 :WSAEINTR "A blocking operation was interrupted by a call to WSACancelBlockingCall.")
(register-error 10009 :WSAEBADF "The file handle supplied is not valid.")
(register-error 10013 :WSAEACCES "An attempt was made to access a socket in a way forbidden by its access permissions.")
(register-error 10014 :WSAEFAULT "The system detected an invalid pointer address in attempting to use a pointer argument in a call.")
(register-error 10022 :WSAEINVAL "An invalid argument was supplied.")
(register-error 10024 :WSAEMFILE "Too many open sockets.")
(register-error 10035 :WSAEWOULDBLOCK "A non-blocking socket operation could not be completed immediately.")
(register-error 10036 :WSAEINPROGRESS "A blocking operation is currently executing.")
(register-error 10037 :WSAEALREADY "An operation was attempted on a non-blocking socket that already had an operation in progress.")
(register-error 10038 :WSAENOTSOCK "An operation was attempted on something that is not a socket.")
(register-error 10039 :WSAEDESTADDRREQ "A required address was omitted from an operation on a socket.")
(register-error 10040 :WSAEMSGSIZE "A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.")
(register-error 10041 :WSAEPROTOTYPE "A protocol was specified in the socket function call that does not support the semantics of the socket type requested.")
(register-error 10042 :WSAENOPROTOOPT "An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call.")
(register-error 10043 :WSAEPROTONOSUPPORT "The requested protocol has not been configured into the system, or no implementation for it exists.")
(register-error 10044 :WSAESOCKTNOSUPPORT "The support for the specified socket type does not exist in this address family.")
(register-error 10045 :WSAEOPNOTSUPP "The attempted operation is not supported for the type of object referenced.")
(register-error 10046 :WSAEPFNOSUPPORT "The protocol family has not been configured into the system or no implementation for it exists.")
(register-error 10047 :WSAEAFNOSUPPORT "An address incompatible with the requested protocol was used.")
(register-error 10048 :WSAEADDRINUSE "Only one usage of each socket address (protocol/network address/port) is normally permitted.")
(register-error 10049 :WSAEADDRNOTAVAIL "The requested address is not valid in its context.")
(register-error 10050 :WSAENETDOWN "A socket operation encountered a dead network.")
(register-error 10051 :WSAENETUNREACH "A socket operation was attempted to an unreachable network.")
(register-error 10052 :WSAENETRESET "The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.")
(register-error 10053 :WSAECONNABORTED "An established connection was aborted by the software in your host machine.")
(register-error 10054 :WSAECONNRESET "An existing connection was forcibly closed by the remote host.")
(register-error 10055 :WSAENOBUFS "An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.")
(register-error 10056 :WSAEISCONN "A connect request was made on an already connected socket.")
(register-error 10057 :WSAENOTCONN "A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.")
(register-error 10058 :WSAESHUTDOWN "A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call.")
(register-error 10059 :WSAETOOMANYREFS "Too many references to some kernel object.")
(register-error 10060 :WSAETIMEDOUT "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.")
(register-error 10061 :WSAECONNREFUSED "No connection could be made because the target machine actively refused it.")
(register-error 10062 :WSAELOOP "Cannot translate name.")
(register-error 10063 :WSAENAMETOOLONG "Name component or name was too long.")
(register-error 10064 :WSAEHOSTDOWN "A socket operation failed because the destination host was down.")
(register-error 10065 :WSAEHOSTUNREACH "A socket operation was attempted to an unreachable host.")
(register-error 10066 :WSAENOTEMPTY "Cannot remove a directory that is not empty.")
(register-error 10067 :WSAEPROCLIM "A Windows Sockets implementation may have a limit on the number of applications that may use it simultaneously.")
(register-error 10068 :WSAEUSERS "Ran out of quota.")
(register-error 10069 :WSAEDQUOT "Ran out of disk quota.")
(register-error 10070 :WSAESTALE "File handle reference is no longer available.")
(register-error 10071 :WSAEREMOTE "Item is not available locally.")
(register-error 10091 :WSASYSNOTREADY "WSAStartup cannot function at this time because the underlying system it uses to provide network services is currently unavailable.")
(register-error 10092 :WSAVERNOTSUPPORTED "The Windows Sockets version requested is not supported.")
(register-error 10093 :WSANOTINITIALISED "Either the application has not called WSAStartup, or WSAStartup failed.")
(register-error 10101 :WSAEDISCON "Returned by WSARecv or WSARecvFrom to indicate the remote party has initiated a graceful shutdown sequence.")
(register-error 10102 :WSAENOMORE "No more results can be returned by WSALookupServiceNext.")
(register-error 10103 :WSAECANCELLED "A call to WSALookupServiceEnd was made while this call was still processing. The call has been canceled.")
(register-error 10104 :WSAEINVALIDPROCTABLE "The procedure call table is invalid.")
(register-error 10105 :WSAEINVALIDPROVIDER "The requested service provider is invalid.")
(register-error 10106 :WSAEPROVIDERFAILEDINIT "The requested service provider could not be loaded or initialized.")
(register-error 10107 :WSASYSCALLFAILURE "A system call has failed.")
(register-error 10108 :WSASERVICE_NOT_FOUND "No such service is known. The service cannot be found in the specified name space.")
(register-error 10109 :WSATYPE_NOT_FOUND "The specified class was not found.")
(register-error 10110 :WSA_E_NO_MORE "No more results can be returned by WSALookupServiceNext.")
(register-error 10111 :WSA_E_CANCELLED "A call to WSALookupServiceEnd was made while this call was still processing. The call has been canceled.")
(register-error 10112 :WSAEREFUSED "A database query failed because it was actively refused.")
(register-error 11001 :WSAHOST_NOT_FOUND "No such host is known.")
(register-error 11002 :WSATRY_AGAIN "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.")
(register-error 11003 :WSANO_RECOVERY "A non-recoverable error occurred during a database lookup.")
(register-error 11004 :WSANO_DATA "The requested name is valid, but no data of the requested type was found.")
(register-error 11005 :WSA_QOS_RECEIVERS "At least one reserve has arrived.")
(register-error 11006 :WSA_QOS_SENDERS "At least one path has arrived.")
(register-error 11007 :WSA_QOS_NO_SENDERS "There are no senders.")
(register-error 11008 :WSA_QOS_NO_RECEIVERS "There are no receivers.")
(register-error 11009 :WSA_QOS_REQUEST_CONFIRMED "Reserve has been confirmed.")
(register-error 11010 :WSA_QOS_ADMISSION_FAILURE "Error due to lack of resources.")
(register-error 11011 :WSA_QOS_POLICY_FAILURE "Rejected for administrative reasons - bad credentials.")
(register-error 11012 :WSA_QOS_BAD_STYLE "Unknown or conflicting style.")
(register-error 11013 :WSA_QOS_BAD_OBJECT "Problem with some part of the filterspec or providerspecific buffer in general.")
(register-error 11014 :WSA_QOS_TRAFFIC_CTRL_ERROR "Problem with some part of the flowspec.")
(register-error 11015 :WSA_QOS_GENERIC_ERROR "General QOS error.")
(register-error 11016 :WSA_QOS_ESERVICETYPE "An invalid or unrecognized service type was found in the flowspec.")
(register-error 11017 :WSA_QOS_EFLOWSPEC "An invalid or inconsistent flowspec was found in the QOS structure.")
(register-error 11018 :WSA_QOS_EPROVSPECBUF "Invalid QOS provider-specific buffer.")
(register-error 11019 :WSA_QOS_EFILTERSTYLE "An invalid QOS filter style was used.")
(register-error 11020 :WSA_QOS_EFILTERTYPE "An invalid QOS filter type was used.")
(register-error 11021 :WSA_QOS_EFILTERCOUNT "An incorrect number of QOS FILTERSPECs were specified in the FLOWDESCRIPTOR.")
(register-error 11022 :WSA_QOS_EOBJLENGTH "An object with an invalid ObjectLength field was specified in the QOS provider-specific buffer.")
(register-error 11023 :WSA_QOS_EFLOWCOUNT "An incorrect number of flow descriptors was specified in the QOS structure.")
(register-error 11024 :WSA_QOS_EUNKOWNPSOBJ "An unrecognized object was found in the QOS provider-specific buffer.")
(register-error 11025 :WSA_QOS_EPOLICYOBJ "An invalid policy object was found in the QOS provider-specific buffer.")
(register-error 11026 :WSA_QOS_EFLOWDESC "An invalid QOS flow descriptor was found in the flow descriptor list.")
(register-error 11027 :WSA_QOS_EPSFLOWSPEC "An invalid or inconsistent flowspec was found in the QOS provider specific buffer.")
(register-error 11028 :WSA_QOS_EPSFILTERSPEC "An invalid FILTERSPEC was found in the QOS provider-specific buffer.")
(register-error 11029 :WSA_QOS_ESDMODEOBJ "An invalid shape discard mode object was found in the QOS provider specific buffer.")
(register-error 11030 :WSA_QOS_ESHAPERATEOBJ "An invalid shaping rate object was found in the QOS provider-specific buffer.")
(register-error 11031 :WSA_QOS_RESERVED_PETYPE "A reserved policy element was found in the QOS provider-specific buffer.")
(register-error 11032 :WSA_SECURE_HOST_NOT_FOUND "No such host is known securely.")
(register-error 11033 :WSA_IPSEC_NAME_POLICY_ERROR "Name based IPSEC policy could not be added.")

